eth-cscs/production

easybuild/easyconfigs/a/Amber/Amber-16-2016.11-CrayGNU-2016.11-cuda-8.0.eb
easybuild/easyconfigs/a/Amber/Amber-16-2016.11-CrayGNU-2016.11-parallel.eb
easybuild/easyconfigs/a/Amber/Amber-16-2016.11-CrayGNU-2016.11-serial.eb
jenkins-builds/6.0.UP02-2016.11-gpu
jenkins-builds/6.0.UP02-2016.11-mc

This version contains two specific patches provided by David Case
in order to run Amber16 using Tesla Pascal GPUs.
In order to guarantee consistency among the GPU and CPU versions
the year-month was added to all versions. In the future Amber16
will contain these patches and this specific build should no
longer be needed.
Probably a year-month version control won't be needed as well.
Still it is hard to know which Amber and AmberTools patches were
applied.

Amber16+Tesla GPU and year-month version control

---

easybuild/easybuild.d/system_wide.cfg
easybuild/easyconfigs/e/EasyBuild-cscs-default.eb
easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb
easybuild/module/Easybuild
jenkins-builds/6.0.UP02-2016.11-gpu

This easybuild module should replace the setup.sh script
The module depends on two environment variables:
EB_CUSTOM_REPOSITORY
EB_CUSTOM_PREFIX
EB_CUSTOM_REPOSITORY defines the position of this repository. If
not set before module load, then by default the jenkins repository
is used. One can use this variable to point to private clones of
this repository.
The following easybuild variables depend on it
EASYBUILD_ROBOT_PATHS
EASYBUILD_INCLUDE_EASYBLOCKS
EASYBUILD_EXTERNAL_MODULES_METADATA (if on cray)
EB_CUSTOM_PREFIX defines the installation directory. This variable
sets the EASYBUILD_PREFIX variable. If not set before module load,
then by default it points to $HOME/easybuild/$host_machine, where
host_machine is filtered version of $HOSTNAME.
The following easybuild variables depend on it …

Adding Easybuild module

---

easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb
easybuild/module/Easybuild
jenkins-builds/production_builds-dom.sh
jenkins-builds/production_builds.sh

Changes to EasyBuild-Custom and EasyBuild modules
- The following variables were set to use the /dev/shm folders (improving performance)
EASYBUILD_TMPDIR            /dev/shm/$USER/easybuild/stage/tmp
EASYBUILD_BUILDPATH         /dev/shm/$USER/easybuild/stage/build
- $CRAY_CPU_TARGET added to the default user EASYBUILD installation folder.
This allows the user to know for which system he installed his own EB configfiles.
This change only affects CRAY systems.
- Removed the definition of EASYBUILD_TMP_LOGDIR. This flag definition was unnecessary.
BUGFIX:
- The MODULEPATH now depends on the EASYBUILD_INSTALLPATH variable, as it should be.
- Updated the jenkins production scripts to use the module EasyBuild.
This removes the need of `setup.sh`. Which is incompatible with the EasyBuild …

Improved EasyBuild-custom and production scripts

---

easybuild/easybuild.d/system_wide.cfg
easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb
easybuild/module/Easybuild

This broke our setup on daint, since we unload PrgEnv-cray before our builds. 
@victorusu maybe we should use the hostname for testing if we're on kesch/escha.

Revert "Improved Kesch suport on Easybuild module"

---

jenkins-builds/6.0.UP02-2016.11-gpu

Several users required the non CUDA version of Amber, QuantumESPRESSO and VASP to run on the hybrid XC50, as they need these versions for their simulations and they can't access the multicore XC40.

amber qe vasp

---

easybuild/easyblocks/tinker.py
easybuild/easyconfigs/c/CrayIntel/CrayIntel-2016.11-intel16.eb
easybuild/easyconfigs/o/OpenMM/OpenMM-7.0.1-CrayIntel-2016.11-intel16-cuda-8.0.eb
easybuild/easyconfigs/t/TINKER/TINKER-7.1.3-CrayIntel-2016.11-intel16-OpenMM-7.0.1-cuda-8.0.eb

Due to a bug on intel 17 compilers, one cannot install TINKER using
the current CrayIntel-2016.11 toolchain. Therefore I am adding the
CrayIntel-2016.11-intel16 toolchain.
Important aspects of this commit:
* Installation of TINKER + OpenMM (dynamic_omm program) and *pure TINKER*
programs are performed. One can compile *pure TINKER* only but setting
the openmm flag to False.
* It is not possible to install only TINKER+OpenMM with this release.
* OpenMM is cuda only and has *NO* python wrappers

Adding Tinker + OpenMM with cuda support

---

easybuild/easyconfigs/a/Amber/Amber-16-2016.11-CrayGNU-2016.11-cuda-8.0.54.eb
easybuild/easyconfigs/c/CP2K/CP2K-4.1-CrayGNU-2016.11-cuda-8.0.54.eb
easybuild/easyconfigs/g/GROMACS/GROMACS-5.1.4-CrayGNU-2016.11-cuda-8.0.54.eb
easybuild/easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-cuda-8.0.54.eb
easybuild/easyconfigs/n/NAMD/NAMD-2.11-CrayIntel-2016.11-cuda-8.0.54.eb
easybuild/easyconfigs/p/pycuda/pycuda-2016.1.2-CrayGNU-2016.11-Python-2.7.12-cuda-8.0.54.eb
easybuild/easyconfigs/p/pycuda/pycuda-2016.1.2-CrayGNU-2016.11-Python-3.5.2-cuda-8.0.54.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.11-cuda-8.0.54.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.1-CrayIntel-2016.11-cuda-8.0.54.eb

This removes the runtime dependency of cuda modules on the 'default' version of cudatoolkit.

fix dependency on cray defaults: added cray_ld_libpath to $LD_LIBRARY_PATH

---

easybuild/easyblocks/qt.py
easybuild/easyconfigs/q/Qt/Qt-5.8.0-CrayGNU-2016.11.eb
easybuild/easyconfigs/q/Qt/Qt-5.8.0.eb

Qt release 5.8.0 accepts '-prefix installdir' in place of '--prefix=installdir', therefore a change in the easyblock qt.py was necessary in order to check if the easyblock specific variable 'prefix_opt' is defined in the easyconfig file.

Adding Qt-5.8.0 easyconfigs with updated easyblock

---

easybuild/easyblocks/qt.py
easybuild/easyconfigs/q/Qt/Qt-5.7.0-debug.eb
easybuild/easyconfigs/q/Qt/Qt-5.8.0-CrayGNU-2016.11.eb
easybuild/easyconfigs/q/Qt/Qt-5.8.0.eb

I have inserted the following version check in the easyblock `qt.py`:
`LooseVersion(self.version) >= LooseVersion('5.8')`
It will make the configuration straightforward and avoid the error prone definitition of `prefix_opt`, which I left in the easyblock though, to comply with the help screen `eb -a -e EB_Qt` (as in ConfigureMake):
`prefix_opt*             Prefix command line option for configure script ('--prefix=' if None) [default: None]`

Updated Qt files: easyconfis and easyblock

---

jenkins-builds/common-RH6.7-2016.10

This commit adds `PyRegression-2.0.2.eb` to the list of installable packages

Adding PyRegression-2.0.2

---

easybuild/easyconfigs/g/GMP/GMP-6.1.2-CrayIntel-2016.11.eb

The output of config.guess is used by default and can be changed with --build. E.g:
`configopts = ' --build=haswell-pc-linux-gnu' `

Gmp crayintel

---

easybuild/easyconfigs/e/embree/embree-2.14.0-CrayGNU-2016.11.eb
easybuild/easyconfigs/o/ospray/ospray-1.2.0-CrayGNU-2016.11.eb

These two libraries provided by Intel are used by ParaView for real-time raytracing. This will be the first version on daint (v5.3) to support it.

ray tracing libraries used by ParaView (5.3 and above)

---

easybuild/easyconfigs/f/freetype/freetype-2.7.1-gmvolf-15.11.eb
easybuild/easyconfigs/l/libpng/libpng-1.6.28-gmvolf-15.11.eb
easybuild/easyconfigs/m/matplotlib/matplotlib-1.4.3-gmvolf-15.11-Python-3.5.0.eb
easybuild/easyconfigs/z/zlib/zlib-1.2.11-gmvolf-15.11.eb

The request includes the easyconfig files for matplotlib-1.4.3, freetype-2.7.1 and libpng-1.6.28 and zlib-1.2.11 with the toolchain gmvolf-15.11.
The latter is updated but not used to build libpng-1.6.28, keeping instead the old dependency zlib-1.2.8 for compatibility with the other modules built using the toolchain gmvolf-15.11.

Update matplotlib-1.4.3 with Python-3.5.0 and dependencies

---

jenkins-builds/6.0.UP02-2016.11-gpu

According with Marcel, users need non-gpu version as well.

adding TF multicore to production

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.11-pat-645-nogpu.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.1-CrayIntel-2016.11-cuda-8.0.54-pat-645-cuda.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.1-CrayIntel-2016.11-pat-645-nogpu.eb

QuantumESPRESSO recipe: non-GPU only, as the it is in production on daint-gpu while the GPU port of the code is not functional with most testcases.

QuantumESPRESSO pat

---

easybuild/easyconfigs/v/VASP/VASP-5.4.1-CrayIntel-2016.11-cuda-8.0.54-pat-645-cuda.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.1-CrayIntel-2016.11-pat-645-nogpu.eb

VASP recipes, CUDA and non-GPU as both are available in production on `daint-gpu`

VASP with perftools-cscs/645-cuda and perftools-cscs/645-nogpu

---

jenkins-builds/production_builds.sh

This adds xalt to production build. It will be called only by Jenkins and on daint.
Since we do not have any mechanism to capture if there was a new build we __always__ perform the reverseMap operation.
But we do it in a different folder and then, copy it on top of the production one.

Adding xalt to production build

---

jenkins-builds/production_builds.sh

Some modules on the xalt table are being saved with the ending (Easybuild), instead of (daint-gpu) or (daint-mc)

Removing module Easybuild before reverseMapD

---

easybuild/easyconfigs/v/VASP/VASP-5.4.1-CrayIntel-2016.11-cuda-8.0.54-pat-645-cuda.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.1-CrayIntel-2016.11-pat-645-nogpu.eb

Using perftools-cscs as a build dependency with variable `%patversion`

Updating VASP recipes with perftools

---

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.0.0-CrayGNU-2016.11-Python-3.5.2.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.0.0-CrayGNU-2016.11-cuda-8.0-Python-2.7.12.eb
easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.0.0-CrayGNU-2016.11-cuda-8.0-Python-3.5.2.eb

Addressing ticket #27402
TensorFlow builds keep bazel workspace after successful builds and this change should fix this problem.
Failed builds will stay anyway on the temporary folder (as expected).

cleaning up bazel workspace after successful build

---

easybuild/easyconfigs/k/Keras/Keras-2.0.3-CrayGNU-2016.11-Python-3.5.2.eb
easybuild/easyconfigs/l/libyaml/libyaml-0.1.6-CrayGNU-2016.11.eb
easybuild/easyconfigs/p/PyYAML/PyYAML-3.12-CrayGNU-2016.11-Python-3.5.2.eb

Test (TF backend) on Daint:
```
perettig@daint102:/scratch/snx3000/perettig> wget https://github.com/fchollet/keras/raw/master/examples/mnist_mlp.py
perettig@daint102:/scratch/snx3000/perettig> srun python mnist_mlp.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] …
```

adding keras (TF + Theano) and deps

---

jenkins-builds/6.0.UP02-2016.11-mc

QuantumESPRESSO 5.4.0 is relatively old and shows bugs (e.g.: https://webrt.cscs.ch/Ticket/Display.html?id=27467), therefore I propose to build the more recent release 6.1.0 in the software stack: not yet as default, but that would be the next step to be properly announced to the users in the News section of the User Portal.
Requires #158

QuantumESPRESSO-6.1.0 on daint-mc software stack

---

jenkins-builds/6.0.UP02-2016.11-gpu

QuantumESPRESSO 5.4.0 is relatively old and shows bugs (e.g.: https://webrt.cscs.ch/Ticket/Display.html?id=27467), therefore I propose to build the more recent release 6.1.0 in the software stack: not yet as default, but that would be the next step to be properly announced to the users in the News section of the User Portal. 
At the same time, I propose to remove the cuda build of release 5.4.0, which is not working.
Requires #158

Add QuantumESPRESSO-6.1.0 to daint-gpu software stack

---

easybuild/easyconfigs/c/CP2K/CP2K-5.0r17753-CrayGNU-2016.11-cuda-8.0.54-pat-645-cuda.eb
easybuild/easyconfigs/c/CP2K/CP2K-5.0r17753-CrayGNU-2016.11-cuda-8.0.54.eb

The official release of CP2K is still 4.1: however some bugs have been fixed only in the development version 5.0, which is available through the SVN.
Here I add a recipe to build CP2K 5.0 SVN revision r17753 of February 7th 2017:
https://sourceforge.net/p/cp2k/code/commit_browser
I have packaged the source to make it available for this EasyBuild recipe:
```bash
svn checkout http://svn.code.sf.net/p/cp2k/code/trunk@r17753 cp2k-5.0r17753
cd cp2k-5.0r17753
tar cjvf cp2k-5.0r17753.tar.bz2 cp2k 
cp cp2k-5.0r17753.tar.bz2 /apps/common/easybuild/sources/c/CP2K
```

Adding support for CP2K development version 5.0 (SVN revision r17753)

---

jenkins-builds/6.0.UP02-2016.11-mc

VMD should only be available on the GPU partition (either OGL or EGL version).
I'm deleting as well the existing module as agreed with @jfavre.

Removing VMD from mc partition

---

easybuild/easyconfigs/a/APR-util/APR-util-1.5.4-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/a/APR/APR-1.5.2-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/e/expat/expat-2.2.0-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/l/libreadline/libreadline-7.0-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/p/Python-bare/Python-bare-2.7.13-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/s/SCons/SCons-2.5.1-GCC-5.4.0-2.26-Python-bare-2.7.13.eb
easybuild/easyconfigs/s/SQLite/SQLite-3.9.2-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/s/Serf/Serf-1.3.9-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/s/Subversion/Subversion-1.9.6-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/t/Tcl/Tcl-8.6.6-GCC-5.4.0-2.26.eb

Subversion 1.7 provided by rpm should be enough for the users, I'm just adding this in case it is requested.
This should work on the node with RH7.3 and it should replace the dummy version (that does not work on the new OS).

[kesch] Subversion 1.9.6

---

easybuild/__init__.py
easybuild/tools/__init__.py
easybuild/tools/module_naming_scheme/__init__.py
easybuild/tools/module_naming_scheme/lowercase_module_naming_scheme.py

This is an attempt to answer the insisting MCH request to have lowercase module files. 
Here's how to test this:
```
$ export PYTHONPATH=$PYTHONPATH:/path/to/production
$ eb --avail-module-naming-schemes
List of supported module naming schemes:
CategorizedHMNS
CategorizedModuleNamingScheme
HierarchicalMNS
LowercaseModuleNamingScheme
EasyBuildMNS
MigrateFromEBToHMNS
$ export EASYBUILD_MODULE_NAMING_SCHEME=LowercaseModuleNamingScheme
```

Adding lowercase naming scheme (for kesch)

---

easybuild/easyconfigs/c/CP2K/CP2K-5.0r17753-CrayGNU-2016.11-cuda-8.0.54.eb

I have copied the library file that we link for Broadwell and Haswell architectures to: 
`/apps/common/UES/easybuild/sources/c/CP2K/libsmm_dnn_cray.gnu.a`

[daint-gpu] Fixing path to libsmm in architecture file

---

easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-17.06-gmvolf.eb
jenkins-builds/monch-RH6.9-17.06

Since gmvolf is now hidden, we could provide this PrgEnv-gnu module (standard name at CSCS).

[monch] Adding PrgEnv-gnu module wrappers

---

jenkins-builds/production.sh
login/daint-gpu
login/daint-gpu.h
login/daint-mc
login/daint-mc.h
login/xalt

The folder contains the modules needed to load the architecture dependent software stack on Piz Daint, together with the EasyBuild headers used to build production modulefiles and a link to the xalt modulefile:
- daint-gpu
- daint-gpu.h
- daint-mc
- daint-mc.h
- xalt

[daint] Adding login folder to production

---

jenkins-builds/production.sh

I have updated the script `production.sh` to use absolute paths, in order to let us call it from arbitrary locations. 
I have also inserted a `module purge` instruction to clean the environment on Dom and Piz Daint before starting the build, loading the necessary modulefiles in place of the previous `module use` command:
`module load craype craype-network-aries modules`
Finally, I set `EB_CUSTOM_REPOSITORY=/apps/common/UES/jenkins/production/easybuild`, since the latter is always up to date for production builds. We can add later a flag to define this variable as a command line argument or check if it is already defined in the environment, in case we would like to use the script for testing new recipes: in fact, in that case one cannot use the master branch of the production repository, …

[daint dom] Module purge in production on Piz Daint/Dom

---

jenkins-builds/6.0.UP02-2016.11-gpu
jenkins-builds/6.0.UP02-2016.11-mc

Following CSCS request #28403, still keeping the previous NCO release as default (until the review of supported applications at the end of the summer) both in `daint-gpu` and `daint-mc` software stacks.

[daint] Adding new NCO release with ncap2 in production

---

jenkins-builds/leone-RHEL6.7EUS-17.06

So that the user finds all the dependencies on the modulepath when building ESyS

[leone] adding boost for ESyS

---

easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb
easybuild/module/Easybuild

The environment variables `EASYBUILD_BUILDPATH` and `EASYBUILD_TMPDIR` will be defined only if the `$USER` has not previously set these varialbes in the environment.

[daint dom kesch leone monch] Define BUILDPATH and TMPDIR only if not set

---

jenkins-builds/6.0.UP02-2016.11-gpu
jenkins-builds/6.0.UP02-2016.11-mc

We currently have a release candidate for CDO in production, while the EasyBuild configuration file for release 1.8.1 is already available for `CrayGNU-2016.11`. 
Furthermore, the change should make the download work automatically.

[daint-gpu] CDO update

---

easybuild/cray_external_modules_metadata.cfg

New Cray modules available:
- `cray-fftw`
- `cray-python`
- `cray-R`
New versions of existing modules:
- `cudatoolkit`
- `fftw`

[dom] Update cray_external_modules_metadata.cfg

---

easybuild/easyconfigs/c/CDO/CDO-1.8.1-CrayGNU-2016.11.eb

The link given in the configuration file is not valid anymore, see the error message in the output below:
https://jenkins.cscs.ch/job/RegressionEB/label=daint/25/consoleFull
The current download link https://code.mpimet.mpg.de/projects/cdo/files does not provide release `1.8.1`, therefore we need to use the absolute path for this release.

[daint] Fixing CDO sources

---

easybuild/easyconfigs/l/libreadline/libreadline-7.0.eb

Jenkins project `RegressionEB` returned a download error: 
https://jenkins.cscs.ch/view/RegressionEB/job/RegressionEB/label=monch04/25/console
As a matter of fact, release 7.0 was not available for download in the link given in the configuration file.

[monch] Fixing download link for libreadline-7.0

---

easybuild/easyconfigs/v/Visit/Visit-2.12.0-CrayGNU-2016.11.eb

The build of `VisIt` would fail on compute nodes as its configuration calls the environment variable `$HOSTNAME`, which is defined with the $SLURM_SUBMIT_HOST and not with the real host. 
The fix makes use instead of the command `hostname`: other variables hold the name of the compute host, e.g. `SLURMD_NODENAME`; for a full list, please have a look at the output pasted below.
```
$ srun --constraint=gpu --nodes=1 --time=01:00:00 --pty /bin/bash -l
srun: job 3444144 queued and waiting for resources
srun: job 3444144 has been allocated resources
$ echo $HOSTNAME
daint103
$ echo $SLURM_SUBMIT_HOST 
daint103
$ echo $(hostname)
nid04027
$ env | grep nid
SLURM_NODELIST=nid04027
SLURMD_NODENAME=nid04027
SLURM_TOPOLOGY_ADDR=s19.s9.nid04027
SLURM_JOB_NODELIST=nid04027
SLURM_STEP_NODELIST=nid04027 …
```

[daint] Fix VisIt build on compute nodes

---

jenkins-builds/6.0.UP02-2016.11-gpu
jenkins-builds/6.0.UP02-2016.11-mc

Their builds fail on Piz Daint compute nodes. However the build of Scalasca with `17.08` is successful on Dom compute nodes.

Removing Scalasca and Score-P

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-17.08.eb
jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc

EasyBuild configuration file for QuantumESPRESSO and updated production lists: version 6.1.0 does not have a GPU port, so the same module will be built on both software stacks `gpu` and `mc`.

[dom] QuantumESPRESSO 6.1.0 with updated production lists

---

jenkins-builds/production.sh

I do not understand why we have this module purge. 
It hurts on the builds when attempting to build with craypat support. 
See:
https://github.com/eth-cscs/production/pull/326
https://jenkins.cscs.ch/view/ProductionEB/job/TestingEB/551/label=dom/console
IMHO, there are two solutions, one is to remove the `module purge` and the other is to recover the needed folder by adding `module use ...`. I am choosing the first one if there is no other problem, that I cannot foresee.

Removing module purge from daint and dom

---

easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7-CrayGNU-17.08.eb
easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.5-CrayGNU-17.08.eb

I propose the name `PyExtensions-%(version)s`, where `%(version)s` is the two digit Python version:
- I don't mention python in the name, the name itself suggests that it is based on Python
- the toolchain name `CrayGNU` clarifies that we are on a Cray system, hinting at `cray-python`
- the toolchain version `17.08` identifies uniquely the version of `cray-python` used as dependency
The extensions built in this recipe are the ones missing from `cray-python` with respect to Python modules built on the Cray so far: the list can be extended if needed (we already added new modules).

[dom] Python extensions for cray-python

---

easybuild/easyconfigs/n/NAMD/NAMD-2.12-CrayIntel-17.08-cuda-8.0.eb
easybuild/easyconfigs/n/NAMD/NAMD-2.12-CrayIntel-17.08.eb
easybuild/easyconfigs/n/NAMD/NAMD-2.12.patch
easybuild/easyconfigs/t/Tcl/Tcl-8.6.7-CrayIntel-17.08.eb

I have uploaded here the new recipes of `NAMD` release 2.12 with `Cray PE 17.08` that make use of the updated dependencies (`Charm++` and `Tcl`).

[dom-gpu] NAMD with PE 17.08

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-17.08-pat-6.5.1.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-cuda-8.0.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08.eb

New EasyBuild configuration file for `QuantumESPRESSO` with `perftools-lite/6.5.1` and minor edits for two `VASP` standard recipes.

[dom-gpu] QuantumESPRESSO with perftools-lite/6.5.1

---

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-cuda-8.0-pat-6.5.1.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-pat-6.5.1.eb

New EasyBuild configuration files for `VASP` release `5.4.4` using `perftools/6.5.1'.

[dom-gpu] VASP 5.4.4 recipes using 17.08 and perftools/6.5.1

---

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-cuda-8.0-pat-6.5.1.eb

I had forgotten to load `perftools-lite` as a `builddependency`.

[dom-gpu] Fixing VASP gpu recipe with perftools-lite

---

jenkins-builds/6.0.UP04-17.08-mc

Build `CMake` release `3.9.1` (dummy) to have it listed as a visible modulefile in the `mc` software stack as well.

[dom-mc] CMake in 6.0.UP04-17.08-mc

---

jenkins-builds/6.0.UP04-17.08-gpu

Inserting `CMake-3.9.1.eb` (dummy) to make it visible in the software stack

[dom-gpu] CMake in 6.0.UP04-17.08-gpu

---

easybuild/easyconfigs/r/reframe/reframe-2.6.1-hpl_hpcg.patch
easybuild/easyconfigs/r/reframe/reframe-2.6.1.eb

This provides an updated package for 2.6.1 that applies a patch for removing the maintenance tag from the HPL and HPCG tests.

[dom] Reframe 2.6.1 patch

---

easybuild/cray_external_modules_metadata.cfg

the name for cray-python should be Python, so that easyblocks can find it.

[dom] Update cray-python name

---

jenkins-builds/production.sh

I have changed the name of the `force` variable in agreement with the naming scheme adopted in the script (now `force_list`) and reset the index `idx` before the loop.

[dom] Fixing force list in production

---

jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc

As discussed with @jgphpc, only modules that are requested by users or known to be used should be on this list.

[daint] cleanup production list

---

jenkins-builds/production.sh

The EasyBuild force flag `-f` is appended only after testing the match with the production list

[daint, dom, kesch, monch, leone] Fixing forcelist for non matching items

---

easybuild/easyconfigs/p/python-graph-dot/python-graph-dot-1.8.2-Python-2.7.13.eb

To be used on ela, it can be tested here:
```
module use /apps/ela/UES/SLES11/easybuild/modules/all
```

[ela] python package for eb dependency graph

---

easybuild/easyconfigs/g/geeqie/geeqie-1.3.eb

I use a `dummy`toolchain as the module should be in the `generic` path.

[kesch] Adding geeqie for MCH generic modules

---

easybuild/easyconfigs/u/Understand/Understand-4.0.913.eb

* Change the source url which doesn't work since the new release `4.0.914` came out.

[dom daint] Fix the source url of the archive for Understand-4.0.913

---

jenkins/JenkinsfileRegressionEB

Removing `EASYBUILD_SOURCEPATH=$prefix/sources` to use packages already available in `jenscscs` cache (currently `/users/jenscscs/sources`) and thus avoid the recent download errors.

[daint dom kesch leone monch] Update JenkinsfileRegressionEB

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-17.08.eb

The current executable `pw.x` links `cray-libsci` for linear algebra routines, which cause the code to fail during `CG style diagonalization` within the QuantumESPRESSO testcase reported by CSCS ticket 29516.
The configuration file should link `MKL` libraries for linear algebra routines, therefore I unload `cray-libsci` and let EasyBuild print a `module list` in the build log for cross-checking.

[daint dom] QuantumESPRESSO: remove cray-libsci from linked libraries

---

jenkins-builds/production.sh

* Use 6.0.UP04 when updating the xalt table of modulefiles

[daint dom] Use 6.0.UP04 instead of 6.0.UP02 in xalt table of production.sh

---

easybuild/easyconfigs/c/CMake/CMake-3.10.0-rc5-GCC-5.4.0-2.26.eb
easybuild/easyconfigs/c/CMake/CMake-3.10.0-rc5.eb

Building CMake now requires `-std=c++11`, that is not provided by `GCC 4.4.7` available on the operating system of Kesch, Leone and Monch: therefore on these systems we are forced to build `CMake` using a toolchain providing a more recent version of `GCC` with respect to the `dummy` toolchain.

[kesch leone monch] CMake 3.10.0 rc5

---

jenkins/JenkinsfileRegressionEB

* If the unusePath is empty then do not use the corresponding option.
* If the unusePath is not empty then use the unusePath option making
the necessary replacements if architectures are defined.

[dom daint kesch monch leone] Check for empty unuse path

---

easybuild/easyconfigs/m/matlab/matlab-r2016a.eb

Since this package is only used for kesch, I am replacing it to point to
the escha matlab folder, which does not require users to be added to the
matlab group.

[kesch] Changing matlab's path

---

easybuild/easyconfigs/c/CMake/CMake-3.10.1.eb

Operating system gcc compilers on `Leone` and `Monch` are version `4.4.7`, too old to have `--std=c++11` which is now required to build `CMake`. Therefore we cannot use `dummy` on these systems for `CMake`.

[daint dom kesch] New CMake version

---

easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-cuda-8.0.eb
easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-parallel.eb
easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-serial.eb

Test to see if using `maxparallel = 1` solves the occasional build issues with `Amber` on Cray systems.

[daint dom] Amber with maxparallel 1

---

easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb

Insert `-fPIC` in GCC `CFLAGS` for `zlib`: it may be required when linking other libraries (e.g.: `binutils-2.28.eb`)

[daint dom kesch leone monch] zlib with fPIC and dummy

---

jenkins/JenkinsfileTestingEB

Insert a check on `EASYBUILD_TMPDIR` after a successful build to avoid exit code 1

[daint, dom] Update JenkinsfileTestingEB

---

easybuild/easyconfigs/a/ASE/ASE-3.15.0-CrayGNU-17.08-python2.eb
easybuild/easyconfigs/g/GPAW/GPAW-1.3.0-CrayGNU-17.08-python2.eb
easybuild/easyconfigs/g/GPAW/gpaw-1.3.0-cray.patch

I have prepared an updated recipe for `GPAW` and the dependency `ASE` using the toolchain `CrayGNU` version `17.08`, based on request number 30693: both recipes load `PyExtensions` as dependency.

[daint, dom] GPAW and ASE python packages for CrayGNU 17.08

---

jenkins/JenkinsfileRegressionEB

Insert a check on `EASYBUILD_TMPDIR` after a successful build to avoid exit code 1

[daint, dom] Update JenkinsfileRegressionEB

---

easybuild/easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08-PLUMED-2.4.0-cuda-8.0.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-CrayGNU-17.08.eb

New recipes to be included in the repository, following CSCS request #30732: the flag `--enable-mpi` with PLUMED is not necessary to patch a mpi parallel code, but only to build a PLUMEd version that is mpi aware. We never used this flag, in order to to avoid the need of running PLUMED with `srun` on compute nodes even for patching the codes.

[daint, dom] PLUMED 2.4.0 to patch LAMMPS 11Aug2017

---

jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc

CP2K 5.1 last stable version in production before changing defaults, following CSCS request #30739.

[daint] CP2K 5.1 in 6.0.UP04-17.08

---

easybuild/easyconfigs/c/CrayGNU/CrayGNU-17.12.eb

Removing dependencies that are already set by cdt (only gcc is kept for compatibility with cuda 8).
Drawback of using cdt currently seems to be only the extra messages displayed:
```
Switching to atp/2.1.1.
Switching to cray-libsci/17.12.1.
Switching to cray-mpich/7.7.0.
Switching to craype/2.5.13.
Switching to gcc/7.2.0.
Switching to java/jdk1.8.0_51.
Switching to modules/3.2.10.6.
Switching to perftools-base/7.0.0.
Switching to pmi/5.0.13.
```

[daint-gpu] Cleaning up duplicated dependencies of CrayGNU-17.12.eb

---

easybuild/easyconfigs/c/CrayGNU/CrayGNU-17.12.eb

I've managed to reproduce TF build problem from jenkins on my terminal and removing CDT seems to have solved the problem.
@victorusu's 1st version (with CDT + explicit dependencies) was working, but had redundant dependencies. 
I propose we don't add CDT until we're sure that it is working nicely (we should also test on other Cray systems).

[dom daint] Removing CDT as dependency from CrayGNU/17.12

---

jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc

Updated files `6.0.UP04-17.08-mc` and  `6.0.UP04-17.08-gpu`, keeping the old release until the end of the current allocation period (June 30th 2018): users selected using `Xalt` have been informed. 
Modules of the new default releases are already available in production and they have been tested successfully using the production tests currently available within the `reframe` testing framework (changing module version manually to run the tests with the new default modules).

[daint dom] New defaults for CP2K and GROMACS in production

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.2.1-CrayIntel-17.08.eb

I have inserted the flag `--disable-xml` in the `configure` step to allow compatibility with the AiiDA parser, as suggested by @toxa81

[daint dom] QuantumESPRESSO 6.2.1 with --disable-xml

---

jenkins/JenkinsfileTestingEB

I have tested the waiting times using the partition `cscsci`: in the worst case I waited for `~ 3` minutes, but the average waiting time is less than a minute on average. Therefore I suggest to use the partition in the project `TestingEB`.

[daint, dom] Updated JenkinsfileTestingEB to use cscsci

---

easybuild/easyconfigs/m/magma/magma-2.3.0-CrayIntel-17.08-cuda-8.0.eb

A small change in the MAGMA recipe to copy ./control/*h header files, which are required by the end user applications.

[daint-gpu, dom-gpu]

---

easybuild/easyconfigs/b/Boost/Boost-1.65.0-CrayGNU-17.08.eb

The following code is not being called for Boost without Python support.
```
def make_module_extra(self):
"""Set up a BOOST_ROOT environment variable to e.g. ease Boost
handling by cmake"""
txt = super(EB_Boost, self).make_module_extra()
txt += self.module_generator.set_environment('BOOST_ROOT',
self.installdir)
return txt
```
There are two possible fixes
1. Fix the easyblock to always run it
2. Add the modextravars to the easyconfig without python
This PR does the number 2

[daint] Adding the BOOST_ROOT to no python version

---

easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.2.9-CrayGNU-17.08-python3.eb

Changed dependency to `cray-python/3.6.1.1` to match the use of `Python 3` and address #611 .

[daint dom] netcdf-python with python 3

---

easybuild/easyconfigs/p/pycuda/pycuda-2017.1.1-CrayGNU-17.08-python3-cuda-8.0.eb

Changed dependency to `cray-python/3.6.1.1` to match the use of `Python 3` and address #613.

[daint dom] Updating python dependency of pycuda with python3

---

easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-parallel.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-serial.eb
easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6-CrayGNU-17.08.eb

Changed dependency to `cray-python/3.6.1.1` to match the use of `Python 3` and address #610 .

[daint] Updating cray-python dependency of h5py

---

jenkins/JenkinsfileProductionEB

Quoting variable ebForceListLocal to force the build of multiple space separated recipes

[daint dom kesch monch leone] Update JenkinsfileProductionEB

---

easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python2-parallel.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python2-serial.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python3-parallel.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python3-serial.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python2-parallel.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python2-serial.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-parallel.eb
easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-serial.eb
jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc

- EB 2.7.0 recipe was copied from latest version 2.7.1
- Added pyextensions (missing 'six' package)
- Enabled sanity checking for the serial versions (only the parallel versions have the `MPI_Init` issue and doing the check on the serial versions will ensure that importing h5py works )

[daint] fix h5py-2.7.x 

---

jenkins-builds/6.0.UP04-17.08-gpu

ParaView 5.5.1 shall supersede 5.5.0 and previous versions.

[daint-gpu] Update 6.0.UP04-17.08-gpu

---

jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc

Remove old version `0.3.0` of `abcpy` as the more recent `0.5.0` is built. 
The old release will still be kept on the system anyway until the next major upgrade.

[daint dom] Remove abcpy-0.3.0 from production lists

---

easybuild/easyconfigs/b/Boost/Boost-1.65.0-CrayGNU-17.08-python2.eb
easybuild/easyconfigs/b/Boost/Boost-1.65.0-CrayGNU-17.08-python3.eb

splitting the use of cray-python/17.06.1 to the newer style version 2 or 3 
cray-python/2.7.13.1
cray-python/3.6.1.1
fixes issue #642

[daint dom] Boost with cray-python/2.7.13.1 and cray-python/3.6.1.1

---

easybuild/easyconfigs/l/LIGGGHTS/LIGGGHTS-4.0.eb
jenkins-builds/leone-RHEL6.7EUS-17.06

(see WebRT https://webrt.cscs.ch/Ticket/Display.html?id=32347)
According to the information, only the version number of LIGGGHTS was adapted.
Version 4.0 of LIGGGHTS was set as default version.

[leone] LIGGGHTS 4.0 build recipe requested by Hilti

---

easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayCCE-18.07.eb
easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayGNU-18.07.eb
easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayIntel-18.07.eb
easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayPGI-18.07.eb

Dependency of PAPI was not updated due to conflict with perftools.
papi (current) 5.5.1.2
papi (latest on dom) 5.6.0.2

[dom] papi-wrap for toolchain version 18.07

---

jenkins-builds/common-SLES12-2016.10

Removing flag `--hidden`: the builds in `common` are not performed by `production.sh`, therefore flags are not applied consistently. We need to fix this in the future, as also the flag `--set-default-module` is not applied as intended to `ReFrame` only.

[daint dom] Remove flag hidden

---

jenkins-builds/production.sh

Inserting EasyBuild dry run in `production.sh`: exit if a dependency is missing.

[daint dom] Dry run

---

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07-cuda-9.1.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07-cuda-9.1.makefile.include
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.07.makefile.include
jenkins-builds/6.0.UP06-18.07-gpu
jenkins-builds/6.0.UP06-18.07-mc

VASP stable release is still `5.4.4` as already available in production.

[dom] VASP recipes for 18.07

---

easybuild/easyconfigs/l/LIGGGHTS/LIGGGHTS-4.0.eb
jenkins-builds/leone-RHEL6.7EUS-17.06

Test by Hilti showed, that the OpenMPI/1.10.2-GCC-5.3.0-2.26 gives better
performance than mvapich2/2.1-gcc-5.3.0. EB-file was adapted accordingly.
Also, LIGGGHTS 3.8 was removed from module list, since the installation
is no longer present
see  webRT ticket number 32590 (https://webrt.cscs.ch/Ticket/Display.html?id=32590)

[Leone] Changing MPI in LIGGGHTS/4.0

---

easybuild/easyconfigs/l/libxc/libxc-4.2.3-CrayIntel-17.08.eb
easybuild/easyconfigs/s/SIRIUS/SIRIUS-5.8-CrayIntel-17.08-cuda-8.0.eb

recipe for sirius-5.8 with CrayIntel; depends on recipe for libxc-4 which has to be merged first

[daint-gpu] SIRIUS-5.8

---

jenkins-builds/6.0.UP07-18.08-gpu
jenkins-builds/6.0.UP07-18.08-mc

Jenkins builds were failing with the error message 
ERROR: Can't find path /scratch/snx3000tds/jenscscs/dom/workspace/ProductionEB/CDO-1.9.4-CrayGNU-18.08.eb
script returned exit code 2

[dom]: correcting dom-build lists (- CDO and ParaView)

---

easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1.eb
easybuild/easyconfigs/p/pycuda/pycuda-2017.1.1-CrayGNU-18.08-python2-cuda-9.1.eb
easybuild/easyconfigs/p/pycuda/pycuda-2017.1.1-CrayGNU-18.08-python3-cuda-9.1.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.08-cuda-9.1.eb

Using dependency `craype-accel-nvidia60` as discussed at today's SCS group meeting, following the advice of the GitLab issue https://git.cscs.ch/scs/doc/issues/355

[dom-gpu] Removing cudatoolkit module

---

easybuild/easyconfigs/a/Amber/Amber-18-9-4-CrayGNU-18.08-cuda-9.1.eb

This PR consolidates three different Amber modules into a single one.
The problem is that once one adds the -cuda flag to Amber compilation
it only compiles applications that CUDA compatible. The same applies
to the -mpi flag.

[dom-gpu] Add Amber 18 with CUDA 9.1

---

easybuild/easyconfigs/a/Amber/Amber-18-9-4-CrayGNU-18.08.eb

This PR consolidates two different Amber modules into a single one.
The problem is that once one adds the -mpi flag to Amber compilation it
only compiles applications that are MPI compatible.

[dom-mc] Add Amber 18

---

easybuild/easyconfigs/g/GDB/GDB-7.10.1-missing-makeinfo.patch
easybuild/easyconfigs/g/GDB/GDB-7.10.1.eb
easybuild/easyconfigs/g/GDB/GDB-8.1.1-missing-makeinfo.patch
easybuild/easyconfigs/g/GDB/GDB-8.1.1.eb

There is a missing patch for GDB 7.10.1

[fulen] Fix GDB 7.10.1 and add GBD 8.1.1

---

easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-CrayGNU-17.08-cuda-8.0.eb
easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-CrayGNU-17.08.eb
jenkins-builds/6.0.UP04-17.08-gpu
jenkins-builds/6.0.UP04-17.08-mc

The reason why I am also changing the default is because the current
GROMACS 2018 has 5 major bugs fixed using version 2018.3
Especially the is a Replica Exchange bug that hinders users from using
RE with GROMACS 2018.

[daint-gpu] Add GROMACS 2018.3

---

easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1-pat-7.0.2.eb
easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1.eb
easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-pat-7.0.2.eb
easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08.eb

New EasyBuild recipes for `CP2K` with `perftools-lite/7.0.2` as `EXTERNAL_MODULE`.

[dom-gpu] CP2K with perftools-lite

---

easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-CrayGNU-18.08-cuda-9.1.eb

This PR attempts to decrease the confusion created by adding the 'cojnfigopts' in order to identify which compilation flags are used by GROMACS. Now, we let EB set the variables.
There should be a small improvement of the CPU side of the code.

[dom-gpu] Improve the compilation flags setup

---

easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-CrayGNU-18.08.eb

This PR attempts to decrease the confusion created by adding the 'cojnfigopts' in order to identify which compilation flags are used by GROMACS. Now, we let EB set the variables.
There should be a small improvement for this version of the code.

[dom-mc] Improve the compilation flags setup

---

easybuild/module/Easybuild

We set a new buildpath by default under `XDG_RUNTIME_DIR`.

[dom-gpu] Adjusting EASYBUILD_BUILDPATH

---

jenkins-builds/6.0.UP07-18.08-mc

Adding missing recipes in `daint-mc` software stack.

[daint-mc] Add netcdf-python in daint-mc

---

easybuild/easyconfigs/g/GREASY/GREASY-2.1-cscs-gmvolf-17.02.eb

I keep a different source file `greasy-2.1-kesch.tar.gz` until we clarify the differences with respect to the tarball for `Piz Daint`.

[kesch] GREASY on Kesch

---

easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1-pat-7.0.2.eb

According to #893 , I'm adapting the recipe that builds the instrumented executable of `CP2K`.

[daint-gpu] CP2K with perftools and without craype-accel-nvidia60

---

easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1.eb
easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-18.08-cuda-9.1.eb

(instead of craype-acel-nvidia60)
Builds were failing (most probably because of the variable `CRAY_TCMALLOC_MEMFS_FORCE=1`, but the issue needs to be confirmed)

[daint-gpu dom-gpu] reverting magma and CP2K to use only cudatoolkit 

---

jenkins-builds/leone-RHEL6.7EUS-17.06

On leone, python default/system version is 2.6.6, which will give:
`ValueError: zero length field name in format`
Using python>=2.7 fixes the issue.

[leone] zero length field name in format

---

easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-18.08-cuda-9.1.eb
easybuild/easyconfigs/m/magma/magma-2.4.0-CrayIntel-18.08-cuda-9.1.eb

@toxa81 why do we use magma 2.2 with GNU and magma 2.4 with Intel ? Is this inconsistency wanted?
The pull request will avoid a separate loading of cudatoolkit.

[dom-gpu daint-gpu] added module cudatoolkit to magma recipe

---

easybuild/easyconfigs/p/Python/Python-2.7.15-gmvolf-18.05.eb

Following a discussion with @victorusu regarding #707 : we have seen that while building [Python-2.7.15-gmvolf-18.05.eb](https://github.com/eth-cscs/production/blob/master/easybuild/easyconfigs/p/Python/Python-2.7.15-gmvolf-18.05.eb), python still needs to download some requirements that are not listed on the easyconfig:
```bash
Downloading https://files.pythonhosted.org/packages/be/2b/beeba583e9877e64db10b52a96915afc0feabf7144dcbf2a0d0ea68bf73d/subprocess32-3.5.3.tar.gz#sha256=6bc82992316eef3ccff319b5033809801c0c3372709c5f6985299c88ac7225c3
Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl#sha256=f0b0e4eba956de51238e17573b7087e852dfe9854afd2e9c873f73fc0ca0a6dd …
```

[fulen] Add extra dependencies to the list of extensions

---

easybuild/easyconfigs/s/scorep_binding_python/scorep_binding_python-b308ab7-CrayGNU-18.08-python3.eb
easybuild/easyconfigs/s/scorep_binding_python/scorep_binding_python-b308ab7.patch

```
Sanity check failed: 
"/opt/python/3.6.5.1/bin/python -c "import scorep_bindings"
```
lib/python3.6/site-packages/scorep/__init__.py
lib/python3.6/site-packages/scorep/__main__.py
lib/python3.6/site-packages/scorep/helper.py
lib/python3.6/site-packages/scorep/trace.py
lib/python3.6/site-packages/scorep/user.py
lib/python3.6/site-packages/scorep/scorep_bindings.cpython-36m-x86_64-linux-gnu.so
lib/python3.6/site-packages/scorep/scorep_bindings_mpi.cpython-36m-x86_64-linux-gnu.so

[dom-gpu] scorep+python

---

easybuild/easyconfigs/d/dask/dask-1.0.0-CrayGNU-18.08-python3.eb

Dask has released version 1.0.0. This easybuild is a dask[complete] which installs everything required for most common uses of Dask (arrays, dataframes, distributed, and so on)

[dom,daint] Create dask-1.0.0-CrayGNU-18.08-python3.eb

---

easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.3-CrayGNU-18.08-python3.eb
jenkins-builds/6.0.UP07-18.08-gpu
jenkins-builds/6.0.UP07-18.08-mc

ipyparallel when a user requests MPI to be set up automatically in their notebook from the jupyterhub spawner page (development).

[dom,daint] Create ipyparallel-6.2.3-CrayGNU-18.08-python3.eb

---

easybuild/easyconfigs/p/ParaView/ParaView-5.6.0-foss-2016b.eb
easybuild/easyconfigs/q/Qt/Qt-5.9.0-foss-2016b-Python-2.7.12.eb
easybuild/easyconfigs/q/Qt/Qt-5.9.0-foss-2016b.eb
jenkins-builds/leone-RHEL6.7EUS-17.06

The commit includes a new Qt necessary for PV5.6
== Results of the build can be found in the log file(s) /scratch/leone/jfavre/leone/software/Qt/5.9.0-foss-2016b/easybuild/easybuild-Qt-5.9.0-20181206.150735.log
and PV5.6 itself
== Results of the build can be found in the log file(s) /scratch/leone/jfavre/leone/software/ParaView/5.6.0-foss-2016b/easybuild/easybuild-ParaView-5.6.0-20181206.155127.log
I have tested inside a VNC desktop and things were running fine.

[leone] PV5.6 comes to Leone with Qt5.9

---

easybuild/easyconfigs/s/Score-P/Score-P-5.0-rc1-CrayGNU-18.08.eb

This PR adds the .eb file that was missing for: https://github.com/eth-cscs/production/blob/master/jenkins-builds/6.0.UP07-18.08-mc#L85

[dom-mc] add scorep/gnu to daint-mc list

---

easybuild/easyconfigs/p/ParaView/ParaView-5.6.0-EGL-CrayGNU-18.08.eb

All users are enabled to use NVIDIA IndeX. We provide the license file in /apps/common/UES/easybuild/sources/p/ParaView. It must be called "nvindex_config.xml" and we provide a default lib path in the same directory.
we updated $LD_LIBRARY_PATH
we defined $NVINDEX_PVPLUGIN_HOME

[daint-gpu] ParaView enable NVIDIA IndeX for all users

---

easybuild/easyconfigs/v/VTK/VTK-8.2.0-EGL-CrayGNU-18.08-python3.eb
jenkins-builds/6.0.UP07-18.08-gpu

eb -f VTK-8.2.0-EGL-CrayGNU-18.08-python3.eb
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VTK/8.2.0-EGL-CrayGNU-18.08/easybuild/easybuild-VTK-8.2.0-EGL-20190201.091555.log

[daint-gpu] new version of VTK with EGL

---

jenkins-builds/production.sh

Insert eval to allow expansion of environment variables in the production file

[dom] Update production.sh

---

easybuild/easyconfigs/g/GREASY/GREASY-19.03-cscs-CrayGNU-18.08.eb
easybuild/easyconfigs/g/GREASY/GREASY-CSCS-19.03-CrayGNU-18.08.eb
jenkins-builds/6.0.UP07-18.08-gpu
jenkins-builds/6.0.UP07-18.08-mc

This is a very disruptive PR for two reasons:
1. GREASY is currently broken, so the module makes no sense to exist
2. The new GREASY has a different usage syntax that is similar to the original GREASY, but on steroids.
So, I am proposing to remove the current (old/broken) GREASY from the production list and update the documentation accordingly.

[daint] Add GREASY version 19.03-cscs

---

easybuild/module/EasyBuild-custom/cscs

Here, the machine daint is specified as a placeholder, since the intended one, Tsa, is not yet in the machines file. Note, however, that the modifications only change the module of EasyBuild.

[daint] Adapt naming scheme for Arolla/Tsa

---

jenkins/JenkinsfileProductionEB
jenkins/Machines.groovy

I propose to remove Dom from production builds until we have a new software list, since the build will keep failing in the meanwhile. 
E.g.: The last failure occurred when building `GREASY` with the error `Unable to locate a modulefile for 'atp/2.1.2'`.
https://jenkins.cscs.ch/blue/rest/organizations/jenkins/pipelines/ProductionEB/runs/580/nodes/37/steps/74/log/?start=0

[dom] Update Machines.groovy

---

login/xalt

Hi,
I have noticed a manual change in the link to the `xalt` folder under `/apps/common/UES/jenkins/production/login`: 
in the mast branch it points to `/apps/daint/UES/xalt/git/cscs/xalt/`, but in the local folder it points to  `/apps/daint/UES/xalt/production/cscs/xalt`.
Could you please confirm that the latter is correct? I have to reset the manul change, otherwise the automatic update of the `production` folder done periodically by `ProductionEBCommon` fails.

[daint] Update xalt path

---

login/xalt

I'm submitting a minor change since in my previous request a trailing slash was missing.

[daint] Fixing symbolic link to xalt folder

---

easybuild/module/EasyBuild-custom/cscs

Re-enable `XDG_CONFIG_DIRS`, otherwise the non-default configuration file `system_wide.cfg` will be ignored: see https://easybuild.readthedocs.io/en/latest/Configuration.html?highlight=XDG_CONFIG_DIRS

[daint] Update EasyBuild-custom/cscs

---

easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1.eb
easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08-cuda-9.1.psmp
easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08.eb
easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.08.psmp
easybuild/easyconfigs/e/ELPA/ELPA-2016.11.001.pre-CrayGNU-18.08.eb
easybuild/easyconfigs/e/ELPA/ELPA-2017.11.001-CrayGNU-18.08.eb
easybuild/easyconfigs/e/ELPA/ELPA-2018.11.001-CrayGNU-18.08.eb

This pull request is addressing CSCS RT #35182. `CP2K` currently supports only `ELPA 2016.11`: I include anyway recipes of two more recent versions of `ELPA` that might be useful for other software packages.

[daint] CP2K with ELPA library

---

jenkins/Machines.groovy

Correct copy-paste error. Unuse path now points to currently installed modules.

[DOM_cle7] Correct unuse patch in machine file

---

easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayCCE-19.03.eb
easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayGNU-19.03.eb
easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayIntel-19.03.eb

```
papi-wrap-1.0-CrayGNU-19.03.eb                     --set-default-module --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
papi-wrap-1.0-CrayCCE-19.03.eb                                          --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
papi-wrap-1.0-CrayIntel-19.03.eb                                        --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
```
```
papi-wrap-1.0-CrayGNU-19.03.eb                     --set-default-module --installpath=$APPS/UES/jenkins/7.0.UP00/mc/easybuild/tools
papi-wrap-1.0-CrayCCE-19.03.eb                                          --installpath=$APPS/UES/jenkins/7.0.UP00/mc/easybuild/tools
papi-wrap-1.0-CrayIntel-19.03.eb …
```

[dom] papiwrap for 19.03

---

easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.15.1-CrayGNU-18.08.eb
easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.5.1-CrayGNU-18.08.eb

build was tested and log file is here:
/scratch/snx3000/jfavre/daint/software/PyExtensions/3.6.5.1-CrayGNU-18.08/easybuild/easybuild-PyExtensions-3.6.5.1-20190408.151848.log
I then successfully built Mesa and then ParaView with it.

[daint] added the Mako package, necessary to configure the new Mesa 18

---

easybuild/easyconfigs/l/Lua/Lua-5.1.4.9-xalt.eb
easybuild/easyconfigs/l/libreadline/libreadline-8.0-xalt.eb

There was an issue with libreadline 7.0 on the system. Version 8.0 removes the issue. Locally, the `Lmod` build now passes.

[dom] update of dependencies for Lmod

---

easybuild/easyconfigs/o/ospray/ospray-1.8.4-CrayGNU-19.03.eb

COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /scratch/snx1600tds/jfavre/daint/software/ospray/1.8.4-CrayGNU-19.03/easybuild/easybuild-ospray-1.8.4-20190410.142820.log
this is used by both ParaView versions

[dom] update ospray to 1.8.4  for TC 19.03

---

easybuild/easyconfigs/p/ParaView/ParaView-5.6.0-EGL-CrayGNU-19.03.eb

standard version (pvserver, pvbatch and pvpython with EGL support)
Reminder: There is no paraview client.
it uses the new ospray v1.8.4 updated earlier
== Results of the build can be found in the log file(s) /scratch/snx1600tds/jfavre/daint/software/ParaView/5.6.0-CrayGNU-19.03-EGL/easybuild/easybuild-ParaView-5.6.0-20190410.150742.log

[dom-gpu] ParaView default version ready for TC 19.03

---

easybuild/easyconfigs/b/byacc/byacc-20170709-CrayGNU-19.03.eb
easybuild/easyconfigs/g/GMP/GMP-6.1.2-CrayGNU-19.03.eb
easybuild/easyconfigs/g/gc/gc-7.6.0-CrayGNU-19.03.eb
easybuild/easyconfigs/g/guile/guile-2.0.14-CrayGNU-19.03.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-CrayGNU-19.03.eb
easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-CrayGNU-19.03.eb
easybuild/easyconfigs/l/libreadline/libreadline-8.0-CrayGNU-19.03.eb
easybuild/easyconfigs/l/libtool/libtool-2.4.6-CrayGNU-19.03.eb
easybuild/easyconfigs/l/libunistring/libunistring-0.9.10-CrayGNU-19.03.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.1-CrayGNU-19.03.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-19.03.eb

`PLUMED 2.5` was already built on Piz Daint following a user's request. 
I have removed the following from `GMP`: `toolchainopts = {'lowopt': True}`. I recall that it was required to build successfully, but with the current toolchain it's not necessary anymore.
Please kindly correct the recipe otherwise.

[dom-gpu] Plumed 2.5.1 with CrayGNU 19.03

---

easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.03.eb

The new default version is reflected in `CrayIntel` and should fix the issues reported here: https://jira.cscs.ch/browse/MAINT-45
Please note that we need to merge this pull request and a force build should be run with Jenkins on `CrayIntel` before #1081 is merged.

[dom] Updating intel version in CrayIntel

---

easybuild/easyconfigs/b/Bison/Bison-3.3.2-CrayIntel-19.03.eb
easybuild/easyconfigs/b/binutils/binutils-2.32-CrayIntel-19.03.eb
easybuild/easyconfigs/b/byacc/byacc-20170709-CrayIntel-19.03.eb
easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.03.eb
easybuild/easyconfigs/f/flex/flex-2.6.4-CrayIntel-19.03.eb
easybuild/easyconfigs/g/GMP/GMP-6.1.2-CrayIntel-19.03.eb
easybuild/easyconfigs/g/gc/gc-7.6.0-CrayIntel-19.03.eb
easybuild/easyconfigs/g/guile/guile-2.0.14-CrayIntel-19.03.eb
easybuild/easyconfigs/l/libffi/libffi-3.2.1-CrayIntel-19.03.eb
easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-CrayIntel-19.03.eb
easybuild/easyconfigs/l/libreadline/libreadline-8.0-CrayIntel-19.03.eb
easybuild/easyconfigs/l/libtool/libtool-2.4.6-CrayIntel-19.03.eb
easybuild/easyconfigs/l/libunistring/libunistring-0.9.7-CrayIntel-19.03.eb
easybuild/easyconfigs/m/M4/M4-1.4.18-CrayIntel-19.03.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.0-CrayIntel-19.03.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-19.03.eb

`Plumed` does not use anymore `libmatheval` since release `2.5`, therefore I have removed it from the dependencies: see https://plumed.github.io/doc-v2.5/user-doc/html/_c_h_a_n_g_e_s-2-5.html
I keep anyway the recipe of `libmatheval` and its dependencies as they were already tested on `19.03`.

[dom-gpu] Plumed 2.5.1 with CrayIntel 19.03

---

easybuild/easyconfigs/n/NAMD/NAMD-2.12-CrayIntel-18.08-PLUMED-2.5.0.eb
easybuild/easyconfigs/n/NAMD/NAMD-2.12-CrayIntel-18.08-cuda-9.1-PLUMED-2.5.0.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.0-CrayIntel-18.08.eb

Removing `libmatheval` from `PLUMED` dependencies:
> ... as of `PLUMED 2.5` the `libmatheval` library is not linked anymore, and the `MATHEVAL` function is implemented using the Lepton library
https://www.plumed.org/doc-v2.5/user-doc/html/_m_a_t_h_e_v_a_l.html

[daint-gpu] NAMD 2.12 with PLUMED 2.5.0

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-CrayIntel-18.08.eb

The install script of `QuantumESPRESSO` downloads the `Wannier90` package during the build process. 
However the package type has changed from `.tar.gz` to `.tar` and therefore the command used by the script fails with the following error message:
`zip: ../archive/wannier90-2.1.0.tar.gz: not in gzip format`
See https://jenkins.cscs.ch/blue/rest/organizations/jenkins/pipelines/RegressionEB/runs/860/nodes/39/steps/86/log/?start=0
This modified recipe fixes this issue with a more recent version of the package `Wannier90` needed by `QuantumESPRESSO`.

[daint-gpu] Fixing W90 bug in QuantumESPRESSO

---

easybuild/easyconfigs/c/CMake/CMake-3.9.3.eb
easybuild/easyconfigs/v/Visit/Visit-3.0.0-CrayGNU-18.08.eb

VisIt 3.0 was tested on my local branch
eb -r -f Visit-3.0.0-CrayGNU-18.08.eb
COMPLETED: Installation ended successfully
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Visit/3.0.0-CrayGNU-18.08/easybuild/easybuild-Visit-3.0.0-20190507.163146.log

[daint] VisIt 3.0 and its cmake dependency

---

jenkins-builds/6.0.UP07-18.08-gpu
jenkins-builds/6.0.UP07-18.08-mc

The recipe `Visit-3.0.0-CrayGNU-18.08.eb` will be built by EasyBuild on Piz Daint (both `gpu` and `mc` software stacks) and set as default modulefile with `--set-default-module`.

[daint] Updating production lists with VisIt

---

easybuild/easyblocks/boostcray.py

This dramatically speeds up the compilation of Boost by making the build being done in parallel.
Example: on `daint105`, building `eb Boost-1.67.0-CrayGNU-18.08.eb --try-software-version 1.70.0` only takes 3 minutes rather than 18 minutes...

[daint dom] make boostcray easyblock aware of 'parallel' easyconfig parameter

---

jenkins-builds/MCH-RH7.5-18.12

Add the (default from EB repo) recipe to the `experimental` software stack on Kesch for MCH to test.

[keschTDS] EB GCC-7.4.0-2.31.1

---

jenkins/Machines.groovy

Removing fulen from production: the node goes always offline and blocks production builds.
```
-bash: cannot create temp file for here-document: No space left on device
```

[daint-gpu] Update Machines.groovy

---

jenkins-builds/production.sh

The command `module unuse` must run before loading the module `EasyBuild-custom/cscs`. 
The `MODULEPATH` needs to be updated with the `EASYBUILD_PREFIX` before loading `EasyBuild-custom/cscs`.

[dom-gpu] Fixing production.sh

---

easybuild/easyconfigs/v/Visit/Visit-3.0.1-CrayGNU-18.08.eb

== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Visit/3.0.1-CrayGNU-18.08/easybuild/easybuild-Visit-3.0.1-20190716.103610.log

[daint-mc] update VisIt from 3.0.0 to 3.0.1

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.0.4-CrayGNU-18.08.eb

JLab 1.x. Major upgrade of JLab easyconfig file with inclusion of JHub dependecies directly and a host of extensions including jupyter-widgets, plotlywidgets, bokeh, topbar, bqplot, dask-labextension, jupyter_server_proxy. hub-extension itself is no longer required as the hub functionality it is built directly in JLab core.

[daint] Create jupyterlab-1.0.4-CrayGNU-18.08.eb

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.0.4-CrayGNU-19.06.eb

JLab 1.x. Major upgrade of JLab easyconfig file with inclusion of JHub dependecies directly and a host of extensions including jupyter-widgets, plotlywidgets, bokeh, topbar, bqplot, dask-labextension, jupyter_server_proxy. hub-extension itself is no longer required as the hub functionality it is built directly in JLab core.

[dom] jupyterlab-1.0.4-CrayGNU-19.06.eb

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.0.4-CrayGNU-18.08.eb

Only build the web pack once by doing a --no-build for individual components followed by a jupyter lab build. Reduce the size of the JS bundle significantly by doing a production build only (jupyter lab build --dev-build=False) - speed up launching of JuptyerLab at run time (launch in ca. 10 sec vs 30 sec).

[daint] jupyterlab-1.0.4-CrayGNU-18.08.eb

---

jenkins/JenkinsfileRegressionEB

I have defined the variable `EASYBUILD_SOURCEPATH` to download the packages to be installed by RegressionEB. I have also corrected the variable `EASYBUILD_TMPDIR` to write logs in the subfolder `tmp` of the `EASYBUILD_PREFIX` folder.

[daint-gpu] Change EasyBuild sourcepath in JenkinsfileRegressionEB

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.0.4-CrayGNU-19.06.eb

Added JUPYTER_PATH to make centrally-installed kernels available in addition to the ones in the user's ~/.local/share/jupyter directory.

[dom] Update jupyterlab-1.0.4-CrayGNU-19.06.eb

---

jenkins-builds/6.0.UP07-18.08-mc

Installed jlab 1.1.1 and set as default. 1.0.4 can no longer be built thanks to npm dependency beyond our control.

[dom-mc] Update 6.0.UP07-18.08-mc

---

jenkins-builds/6.0.UP07-18.08-gpu

Installed 1.1.1 and upgraded default module - 1.0.4 can no longer be built thanks to a npm dependency update (beyond our control).

[daint-gpu] Update 6.0.UP07-18.08-gpu

---

jenkins-builds/7.0.UP00-19.06-gpu

Added jupyterlab-1.1.1. Version 1.0.4 will be removed soon as it is no longer possible to rebuild a working version of it.

[dom-gpu] Update 7.0.UP00-19.06-gpu

---

jenkins-builds/7.0.UP00-19.06-mc

Added jupyterlab-1.1.1. Version 1.0.4 will be removed soon as it is no longer possible to rebuild a working version of it.

[dom-mc] Update 7.0.UP00-19.06-mc

---

jenkins-builds/6.0.UP07-18.08-mc

JHub 1.0.0 is still needed to support the legacy 0.35.2 since the upgrade to JHub 1.0 on server side.

[daint-mc] Update 6.0.UP07-18.08-mc

---

easybuild/easyconfigs/r/reframe/reframe-2.17.1.eb

The 2.17.1 release of ReFrame is back porting from master some essential fixes to 2.17, the release we currently run on Daint. It back ports the following patches:
- Slurm backend fixes, so that ReFrame does not hang with the later Slurm versions
- Maintenance slurm tests updated.
- Vtune Inspector test
It is essential to merge this PR by today, so that reframe can run without a problem during the weekend.

[daint] Easyconfig for the bugfix release of ReFrame 2.17.1

---

jenkins-builds/6.0.UP07-18.08-gpu
jenkins-builds/6.0.UP07-18.08-mc

Remove JLab 1.0.4 from this list as it can no longer be built. Remove dask-labextension from this list as it is now included directly in the jupyterlab easybuild recipe.

[daint] Update 6.0.UP07-18.08-gpu and 6.0.UP07-18.08-mc to remove JLab 1.0.4 and dask-labextension

---

easybuild/easyconfigs/r/reframe/reframe-2.17.2.eb
jenkins-builds/6.0.UP07-18.08-gpu

This time I am updating also the `gpu` production list so as to remove ReFrame from `/apps/common` and I am using a separate install path. I am planning to put a symlink to the actual modules inside the `login/` folder as we do for `xalt`, but I am not sure how to make it point it  differently for Daint and Dom now.

[daint] Add easyconfigs for ReFrame 2.17.2, 2.18 and 2.19 for Daint

---

easybuild/easyconfigs/p/ParaView/ParaView-5.6.0-EGL-CrayGNU-19.09.eb

We removed Boost 1.67.0 in PE 19.09

[dom-gpu] Changing Paraview dependency to Boost 1.70.0

---

easybuild/easyblocks/pycuda.py

This is to ensure that the pycuda easyblock is compatible with EB4 as well with older EB versions.
However we could potentially delete this custom easyblock (it seems that pycuda now builds with stock version, but I didn't test it).
Thanks @boegel !

PyCUDA: Fix for eb 4 compatibility

---

easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.09-classic.eb
easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.09.eb
easybuild/easyconfigs/c/CrayGNU/CrayGNU-19.09.eb
easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.09.eb
easybuild/easyconfigs/c/CrayPGI/CrayPGI-19.09.eb

Change deprecated 'dummy' toolchain to 'SYSTEM', since we are using EasyBuild 4.0.0

[dom] Change deprecated 'dummy' toolchain to 'SYSTEM'

---

easybuild/easyconfigs/n/NCO/NCO-4.8.1-CrayGNU-19.09.eb
jenkins-builds/7.0.UP01-19.09-gpu
jenkins-builds/7.0.UP01-19.09-mc

The build of NCO `4.7.5` fails with the latest configuration on Dom. 
However, the latest release NCO `4.8.1` builds successfully.

[dom-gpu] Latest release of NCO

---

easybuild/easyconfigs/b/Bison/Bison-3.3.2-CrayGNU-18.08.eb
easybuild/easyconfigs/g/GROMACS/GROMACS-2016.6-CrayGNU-18.08-cuda-9.1.eb
jenkins-builds/production.sh
jenkins/JenkinsfileTestingEB

Add option 
* `--hide-deps`, which adds `--hidden` to command line for easybuild in case of a hidden dependency recipe.
* `--exit-on-error` which exists the `production.sh` script on the first `eb` failure
Both options should be used in the TestingEB project. 
In this case, the CI will 
* build hidden dependencies only once
* exit the build procedure in case one of the recipes do not succeed.
Added GROMACS and Bison to the PR just to test the effects.

[daint-gpu] Add support to hide hidden dependencies and exit on first error

---

easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.4-CrayGNU-19.10-python3.eb

ipyparallel 6.2.4 for JupyterLab 1.1.1 (remove dependency on jupyter/1.0.0, which is not used for more recent version of JuptyerLab). This now has no dependencies other than JupyterLab. Fixes issues we had with compatibility between different versions of tornado, zeromqm etc.

[dom] ipyparallel-6.2.4-CrayGNU-19.10-python3.eb

---

jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-mc

ipyparallel 6.2.3 had a dependency on jupyter 1.0.0 which has been retired (replaced by jupyterlab 1.1.1 and deps).

[dom] 7.0.UP01-19.10-gpu

---

jenkins-builds/6.0.UP07-18.08-gpu
jenkins-builds/6.0.UP07-18.08-mc

Add ipyparallel-6.2.4-CrayGNU-18.08-python3.eb for testing with jupyterlab 1.1.1 in advance of the piz daint upgrade

[daint] Update 6.0.UP07-18.08-gpu

---

easybuild/easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayGNU-19.10.eb
easybuild/easyconfigs/p/PROJ/PROJ-4.9.3-CrayGNU-19.10.eb

Adds two easybuild recipes for the CrayGNU-19.10 system:
* PROJ-4.9.3-CrayGNU-19.10.eb
* ecCodes-2.12.2-CrayGNU-19.10.eb
(PS: It's the first time a make a pull request here, so let me know if this is the wrong procedure.)

[daint] Add easybuild recipes for PROJ and ecCodes for CrayGNU-19.10

---

easybuild/easyconfigs/b/Boost/Boost-1.67.0-CrayGNU-19.08.eb
easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.08-cuda-10.0-cordex-double.eb
easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.08-cuda-10.0-crclim-double.eb
easybuild/easyconfigs/c/COSMO_pompa/patch_COSMO_dom_cray_gpu_CrayCCE-19.08.patch
easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-19.08-cuda-10.1-cordex-double.eb
easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-19.08-cuda-10.1-crclim-double.eb
easybuild/easyconfigs/s/STELLA/STELLA-4a5f9c5-CrayGNU-19.08-cordex-double.eb
easybuild/easyconfigs/s/STELLA/STELLA-4a5f9c5-CrayGNU-19.08-crclim-double.eb

Taking into account the latest cudatoolkit version (that was available on DOM)
**Please note**: The change to the `Boost` recipe was necessary for building in my sandbox. If the original `Boost-1.67.0-CrayGNU-19.08` passes on Daint for other applications, the change of the `zlib` dependency from TC CrayGNU -> dummy might not be necessary.

[daint] working COSMO_pompa 19.08 + deps

---

easybuild/easyconfigs/v/Visit/Visit-3.1.0-CrayGNU-19.10.eb
jenkins-builds/7.0.UP01-19.10-mc

I will also cancel my VisIt3.0.2 PR which was blocked by failure to compile.
VisIt3.1.0 is the new version working also on my desktop, so much better overall to work with in conjonction with daint server-side.

[WIP] for daint-mc. To bypass the CI and build only on login nodes

---

easybuild/cray_external_modules_metadata-19.10.cfg

From what I can tell this module is not used in any production recipe, but fftw/2.1.5.9 is available on daint. If the entry is not useful I can remove it completely from the metadata file.

[daint dom] Remove fftw from metadata (unused)

---

login/cdt

The output of `diff` with respect to the original Cray `CDT/19.10` modulefile follows below:
```
}							      /	}
```
The line with the `puts` command is commented in the custom module on the left (no verbosity) with respect to the original Cray modulefile on the right: the symbolic link points to `/apps/daint/UES/7.0.UP01/cdt`

[dom-gpu] Custom cdt modulefile with no verbosity

---

jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-mc

The recipe is still the one available before the CLE upgrade, which used to fail in `TestingEB` due to the different build filesystem with respect to `ProductionEB` (compute vs. login node).

[daint-gpu] Adding MATLAB in production

---

spack/daint/packages.yaml

The key point here is to say that the variant is `+libiberty`.

Add support for binutils from system

---

easybuild/easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-19.10.eb

Fix download link of previous versions of `libxc`

[dom-gpu] Update libxc-4.2.3-CrayGNU-19.10.eb

---

jenkins-builds/production.sh

The current command to install XALT adds:
```
eb xalt-2.7.24.eb --set-default-module --installpath=.../xalt2 -r  --modules-header=.../daint-gpu.h --modules-footer=.../daint.footer
```
This PR removes the `--modules-header=.../daint-gpu.h --modules-footer=.../daint.footer` which makes the command become
```
eb xalt-2.7.24.eb --set-default-module --installpath=.../xalt2 -r  
```
And by consequence removes the depency on `daint-gpu`.

Remove XALT dependency on daint-mc and daint-gpu

---

easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.10-APEX.eb
easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.10-nonetworking.eb

While having the APEX build in the same recipe as the main build reduced duplication, actually using the APEX build still required manual intervention (because of the APEX build path not being present in `LD_LIBRARY_PATH`). This splits the two builds up again.
I've also added a variant with networking disabled, which is a common use-case for a few users at CSCS.

[daint-gpu] Split HPX APEX recipe into separate file

---

easybuild/easyconfigs/m/magma/magma-2.5.2-CrayIntel-19.10-cuda-10.1.eb

Hi guys!
Can somebody help me with this script? The story is the same: I can build Magma with Intel/MKL in my environment, but the same set of command from EB fails. The error message is of no use to me:
```
/opt/nvidia/cudatoolkit10/10.1.105_3.27-7.0.1.1_4.1__ga311ce7/bin/nvcc /run/user/22449/easybuild/build/magma/2.5.2/CrayIntel-19.10-cuda-10.1/magma-2.5.2/magmablas/cpotf2_kernels_var.cu -dc -o /run/user/22449/easybuild/build/magma/2.5.2/CrayIntel-19.10-cuda-10.1/easybuild_obj/CMakeFiles/magma.dir/magmablas/./magma_generated_cpotf2_kernels_var.cu.o -ccbin /opt/cray/pe/craype/2.6.1/bin/cc -m64 --std c++11 -Dmagma_EXPORTS -DMAGMA_WITH_MKL -Xcompiler ,\"-O2\",\"-ftz\",\"-fp-speculation=safe\",\"-fp-model\",\"source\",\"-fopenmp\",\"-fPIC\",\"-craype-verbose\",\"-qopenmp\",\"-Wall\",\"-Wno-u …
```

[daint-gpu dom-gpu] magma-2.5.2 with CMake for CrayIntel

---

jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-mc

Adding jupyterlab-1.1.1-CrayGNU-19.10-batchspawner.eb to production list but keeping the current default. Batchspawner version is required for updated batchspawner.

[daint,dom] Update 7.0.UP01-19.10-gpu

---

easybuild/easyconfigs/l/LAMMPS/LAMMPS-7Aug2019-CrayGNU-19.10-PLUMED-2.5.1-cuda-10.1.eb

With PLUMED 2.5 the lammps patch has been removed, see https://www.plumed.org/doc-v2.5/user-doc/html/_c_h_a_n_g_e_s-2-5.html ("LAMMPS patch has been finally removed. Notice that LAMMPS has native support for PLUMED now".). Native support from LAMMPS 2019 onwards, hence the upgrade to 2019 version. Build instructions here: https://lammps.sandia.gov/doc/Build_extras.html#user-plumed

[dom,daint] Create LAMMPS-7Aug2019-CrayGNU-19.10-PLUMED-2.5.1-cuda-10.1.eb

---

jenkins-builds/7.0.UP01-19.10-gpu-dom

Adds IPython to make it available as a module. Adds jupyterlab-1.2.4 with support for IJulia kernel. Change default version of JupyterLab to one that is supported by new batchspawner.

[dom-gpu] Adding jupyterlab-1.2.4 to jenkins list

---

easybuild/easyconfigs/c/CUDA/CUDA-10.1.168.eb

This fixes the error
```
cmd "rm /tmp/cuda-installer.log" exited with exit code 1 and output: 
rm: cannot remove /tmp/cuda-installer.log: No such file or directory
```

[daint-gpu, dom-gpu] Fix CUDA installation issue

---

easybuild/easyconfigs/o/oidn/oidn-1.1.0-CrayGNU-19.10.eb

ParaView 5.8 new release benefits from the update of the Image Denoising library.
COMPLETED: Installation ended successfully (took 4 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/oidn/1.1.0-CrayGNU-19.10/easybuild/easybuild-oidn-1.1.0-20200218.082136.log

[daint, dom] Intel Open Image Denoise Update

---

easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-EGL-CrayGNU-19.10.eb

N.B. This can only be build on Daint, not Dom, because the OpenGL libs have changed
The following 3 lines comment it out for Dom and will have to be unchecked when Daint gets re-aligned with Dom.
#configopts += '-DOPENGL_opengl_LIBRARY=/usr/lib64/libOpenGL.so '
#configopts += '-DOPENGL_egl_LIBRARY=/usr/lib64/libEGL.so '
== COMPLETED: Installation ended successfully (took 21 min 47 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.8.0-CrayGNU-19.10-EGL/easybuild/easybuild-ParaView-5.8.0-20200218.090850.log

[daint-gpu] New official release of ParaView v5.8 for the gpu partition

---

jenkins-builds/7.0.UP01-19.10-gpu-dom

Remove `IPython` from `dom-gpu`: we need to find a long-term solution for Dom and Piz Daint

[dom-gpu] Update 7.0.UP01-19.10-gpu-dom

---

easybuild/easyconfigs/e/expat/expat-2.2.4-CrayGNU-19.10.eb
easybuild/easyconfigs/g/GDAL/GDAL-2.2.2-CrayGNU-19.10.eb

Add GDAL 2.2.2 with cray-netcdf and cray-hdf5 corresponding to default versions on Daint as at 26 Feb 2020 (PE 19.10).

[daint,dom] Create GDAL-2.2.2-CrayGNU-19.10.eb

---

jenkins/util.groovy

* This makes matching the exact name of machines not only prefix/postfix.

[daint dom-gpu] Improve machine name matching test for CI

---

easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-19.10.eb

I had to revert to the easyblock `ConfigureMake` since some library files requested by `CP2K 7.1` were missing in the CMake build performed with the easyblock `CMakeMake`. 
I have also fixed the download link which was not working any more to download the package (see #1525).

[daint-gpu] Update libxc-4.3.4-CrayIntel-19.10.eb

---

easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.10.eb

I am submitting a new recipe for `libxc-4.3.4` with `CrayGNU`, since CP2K requires also the Fortran library files `libxcf03` and `libxcf90` in addition to the `libxc` file and the former ones were missing in the build with the easyblock `CMakeMake`. This recipe builds both the static and shared library files, that I have added to the sanity check list: the build will take a bit more time to complete, however I have removed the constraint `parallel = 1` to allow multiple threads with `make`.
The download from GitLab works correctly for manual builds, but recently fails with the Jenkins CI (see #1525): therefore I am reverting to the download from www.tddft.org, although in the past it was occasionally unreliable.

[daint-gpu] libxc 4.3.4 with CrayGNU

---

easybuild/module/EasyBuild-custom/cscs

On `tsa-ln003`, the compatibility mode of the modules environment was activated to mitigate an issue when unloading already unloaded modules. This requires a change of the EASYBUILD_MODULES_TOOL variable.
This modification is intended to be temporary, to account for the different settings on Tsa (RH7.6 & RH7.7).

[tsa] Account for compatibility mode of modules on RH7.7

---

jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-mc

Adds LAMMPS 3 March 2020  to the production lists.

[daint-gpu] Update 7.0.UP01-19.10-gpu

---

easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.10.eb

Reverts eth-cscs/production#1528
@lucamar The options `-DENABLE_FORTRAN=1 -DENABLE_FORTRAN03=1` to cmake produce the correct libraries. I  propose to revert this pull request and use cmake

[daint-gpu] libxc 4.3.4 with CrayGNU and CMake

---

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.10-w90-3.1.0.makefile.include

Fixing a missing Wannier90 precompiler and linker flag in VASP `makefile.include` for the multicore build.

[daint-mc] Fix VASP W90 makefile.include

---

jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-gpu-dom
jenkins-builds/7.0.UP01-19.10-mc
jenkins-builds/7.0.UP01-19.10-mc-dom

I am not sure why this recipe was introduced in the production list but, as far as I can tell, it is not used in any recipe of a supported application.

[dom daint] Remove ipykernel from production list

---

easybuild/easyconfigs/a/Amber/Amber-18-14-14-CrayGNU-19.10-cuda-10.1-pat7.1.1.eb

Amber was provided as a module on daint
```
------------------------------------------------ /apps/daint/UES/6.0.UP07/craypat/easybuild/modules/all/ -------------------------------------------------
CP2K/6.1-CrayGNU-18.08-cuda-9.1-pat-7.0.2       LAMMPS/22Aug18-CrayGNU-18.08-cuda-9.1-pat-7.0.2 VASP/5.4.4-CrayIntel-18.08-cuda-9.1-pat-7.0.2
CPMD/4.1-CrayIntel-18.08-pat-7.0.2              NAMD/2.12-CrayIntel-18.08-cuda-9.1-pat-7.0.2
```

[daint] Provide Instrumented version of Amber18

---

easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-19.10.eb

I provide the recipe `ELPA 2019.11.001` with CrayGNU and `cray-libsci` for linear algebra routines. 
The script might be useful for #1551: as a matter of fact, the previous recipe `ELPA-2019.05.001-CrayGNU-19.10.eb` that is used as a dependency in that pull request makes use of MKL libraries instead of `cray-libsci`, however the CrayIntel recipe `ELPA-2019.11.001-CrayIntel-19.10.eb` already exists.

[daint-gpu] Latest ELPA release with CrayGNU

---

easybuild/easyconfigs/p/PyFR/PyFR-1.9.0-CrayGNU-19.10-python3.eb
easybuild/easyconfigs/p/pycuda/pycuda-2019.1.2-CrayGNU-19.10-python3-cuda-10.1.eb

The pycuda version for PyFR has been updated.
The openmp backend is not working for some reason, but the cuda backend is.

[daint] new pycuda for PyFR

---

easybuild/easyblocks/boost.py
easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-19.10-python3.eb
easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10-python3.eb
easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10.eb
easybuild/easyconfigs/b/Boost/Boost-1.72.0-CrayIntel-19.10-python3.eb
easybuild/easyconfigs/b/Boost/Boost-1.72.0-CrayIntel-19.10.eb
easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayIntel-19.10.eb

I have updated `boost.py` to build `Boost` with `CrayIntel`, required by `Libint`, a dependency of `CP2K` (see #1561) : I have checked that the change is not affecting the `CrayGNU` build for version `1.70.0` (the Python build is included in this pull request, since I have updated the patch version).
I have also included a fix to `boost.py` for versions `> 1.70.0`, together with the recipes of version `1.72.0` with CrayIntel.

[daint-gpu] Boost with CrayIntel

---

easybuild/module/EasyBuild-custom/cscs

Fixes `module use` statement in the EasyBuild module wrapper when using non-default PEs.
Case #251844  
Tested on daint (`eb bzip2-1.0.6-CrayGNU-19.08.eb -r`)

[daint] Fix proposed by Cray for using non default modules

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-19.10.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-19.10-cuda-10.1.eb
jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-gpu-dom
jenkins-builds/7.0.UP01-19.10-mc
jenkins-builds/7.0.UP01-19.10-mc-dom

Changes:
- info in `module help` on IEEE warning for QuantumESPRESSO GPU (see https://www.pgroup.com/userforum/viewtopic.php?t=4585)
- change to MKL FFT for QuantumESPRESSO multicore (slightly better performance with respect to FFTW in the Deisa benchmark AuSurf used by ReFrame)
I am also adding the new modules to the production lists of Piz Daint and Dom.

[daint-gpu] Updated QuantumESPRESSO 6.5 in production

---

jenkins/Machines.groovy

The variable `XDG_RUNTIME_DIR` on Tsa RH7.7 is not set anymore by default. (this seems due to an issue in the updated setup of SLURM (https://bugs.schedmd.com/show_bug.cgi?id=5920)
It is suggested to use `/tmp/$USER` as buildpath.

[TSAtds] Change buildpath for Tsa

---

easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.2-CrayGNU-19.10.eb

https://jira.cscs.ch/browse/UES-818
is of great use to limit copying images from daint to remote teleworking locations.
== COMPLETED: Installation ended successfully (took 1 min 39 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/FFmpeg/4.2.2-CrayGNU-19.10/easybuild/easybuild-FFmpeg-4.2.2-20200427.093351.log

[dom-gpu] ffmpeg for remote video encoding

---

jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-gpu-dom
jenkins-builds/7.0.UP01-19.10-mc
jenkins-builds/7.0.UP01-19.10-mc-dom

I am adding `CP2K` 7.1 `CrayGNU` easyconfig files in the production lists of Dom and Piz Daint, as non default for the time being.

[dom-gpu] CP2K 7.1 in production

---

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10-cuda-10.1.psmp

I have added `-fopenmp` to `CFLAGS` to match `FCFLAGS`: without the additional flag, `libcusmm` is built without `OpenMP` support and the consistency check introduced by the pull request https://github.com/cp2k/dbcsr/pull/183 stops the execution of `CP2K` when `dbcsr` is initialized.

[dom-gpu] Fix libcusmm build with CP2K

---

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.psmp
easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.psmp

The new architecture files link the Intel MKL version of the `libsmm` library, which improves the performance of the executable `cp2k.psmp` and makes it always slightly faster than the GNU build. 
However, the size of the Intel executable is almost three times larger with respect to the GNU one:
- Intel MKL: 444M (`gpu`) and 437M (`mc`)
- GNU (`cray-libsci`, `fftw`): 162M (`gpu`) and 145M (`mc`)
The performance measured with the CP2K ReFrame checks in production (256 water molecules) improves by ~ 2% with the Intel multicore build and only by ~ 0.5% with the Intel GPU build.

[daint-gpu] CP2K dependency libsmm with Intel MKL

---

tools/ebdiff.py

This is a small tool I've written that generates diffs between two easyconfig specs. The problem I usually face is that since EasyBuild's mentality is to have an easyconfig for each spec (version, variant etc.) for a package, it is difficult to see what actually changes from, for example, reframe 2.3 to 2.4 or from CrayGNU 19.06 to CrayGNU 19.10. That was the motivation for this tool. It is essentially a wrapper to the system's diff command but with some EasyBuild bindings:
```
usage: ebdiff.py [-h] [-r PATH] [--num-matches NUM_MATCHES]
[DIFF_OPTS] PACKAGE SPEC1 SPEC2
positional arguments:
DIFF_OPTS
PACKAGE
SPEC1
SPEC2
optional arguments:
-h, --help            show this help message and exit
-r PATH, --robot-path PATH
Override EasyBuild's robot path
--num-matches NUM_MATCHES
Number of …
```

[dom-gpu] Tool for generating Easyconfig diffs

---

easybuild/easyconfigs/m/magma/magma-2.5.3-CrayPGI-19.10-cuda-10.1.eb
easybuild/easyconfigs/q/QD/QD-2.3.22-CrayPgi-19.10.eb
easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayPGI-19.10-cuda-10.1.eb
easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayPGI-19.10-cuda-10.1.makefile.include
easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-CrayPGI-19.10.eb

The pull request addresses the new build of `VASP 6.1.0` using `CrayPGI`: few more libraries are now needed as dependency, see https://www.vasp.at/wiki/index.php/Installing_VASP.6.X.X

[daint-gpu] VASP 6.1.0 gpu

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-19.10-cuda-10.1.eb

The pull request adds make targets to the build of `QuantumESPRESSO 6.5a1` (GPU version): it should partially address the request CSCS RT #39216, but only `cp.x` and `pw.x` are GPU enabled.
As pointed out in a comment, targets 'hp' and 'gwl' are currently failing with release `6.5a1`: I'm now trying to build the latest QE GPU release `6.5.a2` with `CrayPGI` and I will open a new pull request.

[daint-gpu] Adding make targets for QE6.5a1

---

easybuild/easyconfigs/l/line_profiler/line_profiler-2.1-CrayGNU-19.10-python3.eb
easybuild/easyconfigs/n/nvtop/nvtop-1.0.0-CrayGNU-19.10-cuda-10.1.eb

Since #1616 is getting too big, I am splitting the PR into smaller ones.
When `cray-python` and `cudatoolkit` are direct dependencies, we can use the easybuild template variables (pyver, pyshortver, pymajver, cudaver, cudashortver, cudamajver), in order to update the recipes more easily in the future.

[dom-gpu, daint-gpu] Eb template values in nvtop and line_profiler

---

easybuild/easyconfigs/c/CrayGNU/CrayGNU-19.10.eb
easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.10.eb
easybuild/easyconfigs/c/CrayPGI/CrayPGI-19.10.eb

I have added the `version` variable to the description and to the `cdt` dependency (`EXTERNAL_MODULE`) to make it easy to automate future deployments. 
If we adopt the new easyconfig files, deploying a new Cray toolchain can be simply done using the EasyBuild option `--try-software-version`, as in the example below for `20.05` based on `19.10`:
```
eb CrayPGI-19.10.eb --hidden --try-software-version=20.05
```

[dom-gpu] Version in Cray toolchain easyconfigs

---

easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-19.10-python3.eb
easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10-python3.eb
easybuild/easyconfigs/b/Boost/Boost-1.70.0-python3.patch
easybuild/easyconfigs/b/Boost/Boost-1.72.0-CrayIntel-19.10-python3.eb

The former patch had a faulty condition, which always led to using `include/python{pyshortver}m` as the py include path, however, py2.7 and py3.8 should use `include/python{pyshortver}` (without the 'm')
also update eb templates for Boost-CrayIntel

[dom, daint] Fix boost patch for python[m] includes

---

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-SIRIUS-6.5.3-cuda-10.1.eb
easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-SIRIUS-6.5.3-cuda-10.1.psmp

I provide the EasyBuild scripts to link CP2K with SIRIUS, using Intel MKL on the Cray XC50.

[daint-gpu] CP2K 7.1 with SIRIUS 6.5.3 and CrayIntel

---

easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.10-classic.eb

I have updated `CrayCCE-19.10-classic.eb` using the strings `version` and `versionsuffix` and I have checked that existing recipes are still built correctly by EasyBuild, e.g.:
```
$ eb ./c/CubeLib/CubeLib-4.4.4-CrayCCE-19.10-classic.eb --try-toolchain-version=20.05-classic -r
== temporary log file in case of crash /run/user/21827/easybuild/tmp/eb-89tOfN/easybuild-OzzJBu.log
== resolving dependencies ...
== processing EasyBuild easyconfig /users/lucamar/GitHub/lucamar/production/easybuild/easyconfigs/c/CrayCCE/CrayCCE-20.05-classic.eb
== building and installing CrayCCE/.20.05-classic...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of …
```

[dom-gpu] Update version and versionsuffix in CrayCCE-classic

---

easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-foss-2019b.eb
easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-fosscuda-2019b.eb

PyExtension build failed due to new version of matplotlib dependencies available were not compatible with Python 2 anymore.

[tsa] Fix Python module versions in PyExtension-2.7.16

---

easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2-nocuda.eb
easybuild/easyconfigs/p/PrgEnv-gnu/PrgEnv-gnu-tsa-19.2.eb

The path for the PE is hard coded in the module and was missing the subfolder corresponding to the release tag.

[tsa] Add release tag to path variable

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-19.10-batchspawner.eb

This PR adds the JupyterLab Code Formatter to JupyterLab (https://jupyterlab-code-formatter.readthedocs.io/en/latest/index.html).
It also adds one default formatter, Black, which is an industry standard for code formatting.
Dependencies of black, namely, pathspec, types_ast, appdirs, regex, toml are also included as pinned versions.
The extension also requires a serverextension to be enabled, either by the user or through the JupyterHub scripts.

[dom,daint] Update jupyterlab-1.1.1-CrayGNU-19.10-batchspawner.eb

---

jenkins-builds/production.sh

After June 30th 2020, VASP.6 modules will be accessible only to users belonging to the unix group `vasp6`.

[daint-gpu] Enforce group vasp6

---

jenkins-builds/MCH-PE20.08-dev0

Recipes for PGI 20.4 meta modules will be added later and, therefore, they are removed from the production list.

[tsa] Remove PrgEnv-pgi-20.4 from production list

---

easybuild/easyblocks/juliapackage.py
easybuild/easyconfigs/j/Julia/Julia-1.4.2-CrayGNU-19.10-cuda-10.1.eb
easybuild/easyconfigs/j/Julia/Julia-1.4.2-CrayGNU-19.10.eb
easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.4.2-CrayGNU-19.10-cuda-10.1.eb
easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.4.2-CrayGNU-19.10.eb

The Julia CUDA packages CUDAdrv, CUDAnative and CuArrays were merged into one single package CUDA.jl. This PR includes the latest CUDA.jl package as well as the latest versions of all other included packages.

[daint] Julia 1.4.2 with CUDA 1.2.0

---

jenkins-builds/7.0.UP01-19.10-gpu
jenkins-builds/7.0.UP01-19.10-mc

This is the version required by the jupyterlab that is going in production.

Add Julia 1.4.2 to production

---

easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-CrayGNU-20.06-OSMesa.eb

The error can be reproduced by (on dom) running
```
module load daint-mc
module show ParaView/5.8.0-CrayGNU-20.06-OSMesa
ParaView/5.8.0-CrayGNU-20.06-OSMesa(64):ERROR:102: Tcl command execution failed: setenv	PYTHONPATH		"/apps/dom/UES/jenkins/7.0.UP02/mc/easybuild/software/ParaView/5.8.0-CrayGNU-20.06-OSMesa/lib64/python3.8/site-packages/:$::env(PYTHONPATH)"
```

[dom-mc] Fix module show for ParaView/5.8.0 OSMesa

---

tools/upgrade-tc.py

This script seems to work fine, in case someone still needs to upgrade some 19.10 recipes.
It's based on the former new-tc.py but it also updates the external module versions according to the given metadata file (which basically means that it just removes the old hardcoded versions).
```
eb easybuild/easyconfigs/h/Horovod/Horovod-0.19.1-CrayGNU-19.10-tf-2.2.0.eb -Dr | \
grep ' \* \[.\] ' | sed 's@^[^/]*/@@g' | awk '{print $1}' | xargs basename -a | \
grep '\-Cray.*-19.10' | sort | uniq | xargs -IF find . -name F | \
xargs tools/upgrade-tc.py --metadata easybuild/cray_external_modules_metadata-20.06.cfg --toolchain-prefix Cray --version 20.06 --filenames
```
```
Finished writing new config: ./easybuild/easyconfigs/b/Bazel/Bazel-2.0.0-CrayGNU-20.06.eb
Finished writing new config: …
```

[dom-gpu] toolchain upgrade script

---

jenkins-builds/7.0.UP02-20.06-gpu-dom
jenkins-builds/7.0.UP02-20.06-mc-dom

I have updated the production lists of Dom: I have noticed that on Piz Daint we have defined both `PLUMED` modules as default, but I think that we should have only one default, even if they belong to a different toolchain.
Therefore I propose to have `PLUMED` with `CrayGNU` as default.

[dom-gpu] Update production lists on Dom

---

easybuild/easyconfigs/i/ipcmagic/ipcmagic-0.1-CrayGNU-20.06.eb
jenkins-builds/7.0.UP02-20.06-gpu-dom
jenkins-builds/7.0.UP02-20.06-mc-dom

The new recipe uses the current metadata file and loads external dependencies without versions. 
I don't understand why `ipcmagic` builds the extension `ipyparallel 6.3.0`, while we have a stand-alone modulefile ` ipyparallel/6.2.4-CrayGNU-20.06-python3` in the production list. Any idea?

[dom] Updated ipcmagic recipe and production lists

---

easybuild/easyconfigs/v/VTK/VTK-9.0.0-CrayGNU-20.06-EGL-python3.eb
jenkins-builds/7.0.UP02-20.06-gpu-dom

The pull request provides a draft recipe for VTK with `CrayGNU 20.06` and the `EGL` library.
Unfortunately, the library is available under the name `libEGL_nvidia.so.0` and not as `libEGL.so` as requested by the build process and the build fails with the following error:
```
make[2]: *** No rule to make target '/opt/cray/nvidia/default/lib64/libEGL.so', needed by 'lib64/libvtkglew-9.0.so.9.0.0'.  Stop.
```

[dom-gpu] VTK with CrayGNU 20.06 EGL

---

jenkins-builds/7.0.UP02-20.06-gpu-dom

There is no default module for Horovod.
This is in principle ok, but it is not symmetrical to the other applications that always have a default.
On daint, for instance, it shows...
```
module av Horovod
...
Horovod/0.16.4-CrayGNU-19.10-tf-1.14.0 Horovod/0.18.1-CrayGNU-19.10-tf-2.0.0  Horovod/0.19.1-CrayGNU-19.10-tf-2.2.0
```

[dom-gpu] Default module for Horovod

---

easybuild/easyconfigs/a/Amber/Amber-20-3-0-CrayIntel-20.06.eb

The generated module for Amber MC is wrongly named.
```
$ module load daint-mc 
[hvictor@dom101:~/github/production/easybuild/easyconfigs/a/Amber]$ module av Amber 
-------------------------------------------------------------------------------------------------------------- /apps/dom/UES/jenkins/7.0.UP02/mc/easybuild/modules/all/ --------------------------------------------------------------------------------------------------------------
Amber/20-3-0-CrayIntel-20.06-cuda(default)
```

[dom-mc] Fix the Amber 20.06 MC recipe

---

jenkins-builds/7.0.UP02-20.06-gpu-dom
jenkins-builds/7.0.UP02-20.06-mc-dom

I'm removing the old releases of Julia and Jupyterlab from the production list of Dom. 
I have also removed `ipyparallel`, since this Python package is installed as an extension of `ipcmagic`.
Are there other items related to Jupyter in the production lists to remove or update on Dom with the PE 20.06?

[dom] New versions of Julia and Jupyterlab in production on Dom

---

easybuild/cray_external_modules_metadata-20.08.cfg

The metadata file is needed by the Jenkins project `UpdateEB` to update the software stack.

[dom-gpu] Cray PE 20.08 metadata file

---

easybuild/module/EasyBuild-custom/cscs

The reference to the Cray metadata file needs to be updated in production:
```
setenv EASYBUILD_EXTERNAL_MODULES_METADATA $::env(EB_CUSTOM_REPOSITORY)/cray_external_modules_metadata-20.08.cfg
```

[dom] Update Cray metadata in the EasyBuild custom modulefile

---

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08-cuda.eb
easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.08-cuda.eb

I'm adding the recipe for the `ELPA` library with GPU support and updating the recipe of `CP2K` where it is currently used as a dependency.
Extending the new `ELPA` recipe to build it on the current Cray PE 19.10 of Piz Daint is straightforward: the library can be compiled using the EasyBuild flag `--try-toolchain-version=19.10`.

[dom-gpu] Adding ELPA with GPU support

---

easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-19.10-cuda-10.1.eb

Force remove the `cray-libsci_acc` module as it is not needed by `CUDA.jl` or Julia in general, but it breaks the jupyterlab module (see #1862).

[daint-gpu] Force remove cray-libsci_acc

---

easybuild/easyconfigs/h/hwloc/hwloc-1.11.7.eb
easybuild/easyconfigs/h/hwloc/hwloc-2.0.4.eb

The export of the `HWLOC_ROOT` environment allows CMake 3.17.3 cannot find hwloc, while CMake 3.17.1 can find it without this environment variable.
This issue was observed in the past with Boost, so we have added this environment variable (https://github.com/eth-cscs/production/blob/1c9786abae372c86efdcb68a5ac10a4a8a22fb58/easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-20.08.eb#L25).

[daint-gpu] Add HWLOC_ROOT to hwloc modules

---

easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-20.08-cuda.eb

This PR removes the cray-libsci_acc module from the Julia 1.5.0 module as it causes issues with numpy and Dask at runtime in JupyterLab.

[dom-gpu] Julia 1.5.0 without cray-libsci_acc module

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner-cuda.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner.eb

This is JupyterLab 2.0.2. 
JupyterLab 2.x is required for a fix for ipyparaview zooming (not backported to jupyterlab 1.x). It requires the update of some python modules and widgets, as jupyterlab extensions are incompatible between jupyterlab 1.x and 2.x. I have tried to keep as many python modules the same as for previous versions, but because of some forced changes and bug fixes there are a few updates, which are commented in the recipe.

[dom]  jupyterlab-2.0.2-CrayGNU-20.08-batchspawner-cuda.eb

---

easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-20.08-cuda.eb
easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.3-CrayIntel-20.08-cuda.eb

Linking `ELPA` with GPU support as already done for `CP2K`: linking the new library will not change the behaviour of the code, as described in the `ELPA` Wiki:
> If ELPA is build with GPU support, users can choose at RUNTIME, whether to use the GPU version or not.
Only if the configure option `--with-gpu-support-only` is used when building `ELPA`, then the use of the GPU version of the library will be enforced at runtime:
```
--with-gpu-support-only | Compile and always use the GPU version
```
See https://gitlab.mpcdf.mpg.de/elpa/elpa/-/wikis/INSTALL for more information.

[dom-gpu] Update ELPA dependency of SIRIUS

---

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7.0-CrayGNU-19.10.eb
easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-7.0-20200508

Changing the dependencies to use the SCOTCH library from the `cray-tpsl` module, instead of building SCOTCH apart.

[daint-mc] Changing SCOTCH dependency of OF7

---

easybuild/easyconfigs/x/xalt/xalt-xalt-2.8.10.bindata.patch

This fixes an integer overflow on XALT
Introduces the '?###?' separator for the symboles
Removes symbols that start with '.' or '__'
Strips the ' [code .*]' entries at the end of the function names

[dom-gpu] Fix integer overflow on xalt data

---

easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-20.08.eb
jenkins-builds/7.0.UP02-20.08-dom-gpu
jenkins-builds/7.0.UP02-20.08-dom-mc

we set CPMD 4.1 as default since our test case is executed faster with the old version
UES-1052

[dom] CPMD 4.1

---

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-20.08-cuda.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-20.08.eb
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-cuda.makefile.include
easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel.makefile.include

I provide the EasyBuild recipes of the older `VASP 5.4.4` release for users that have not yet purchased a license for the latest release `VASP 6`, as explained on the User Portal at https://user.cscs.ch/computing/applications/vasp.

[daint-gpu] Recipes of older VASP 5.4.4 on cdt 20.08

---

easybuild/cray_external_modules_metadata-20.08.cfg
easybuild/easyconfigs/s/SLEPc/SLEPc-3.13.4-CrayIntel-20.08-complex.eb

EB doesn't find software root with current metadata file. For the discussion I'm proposing here to explicitly use CRAY_PETSC_COMPLEX_PREFIX_DIR as workaround, but @ekouts or @victorusu might have a better solution? Shouldn't this be detected automatically?

[daint-gpu] slepc 3.13.4 with 20.08 + fix for PETSc metadata 

---

easybuild/cray_external_modules_metadata-20.08.cfg
easybuild/easyconfigs/s/SLEPc/SLEPc-3.13.4-CrayIntel-20.08-complex-mc.eb

Slepc with workaround due to broken `PETSC_DIR` with `craype-broadwell` + fix for `cray-petsc` metadata

[daint-mc] slepc 3.13.4 with 20.08 + fix for PETSc metadata 

---

easybuild/easyconfigs/a/adios/adios-2.6.0-CrayGnu-20.08.eb
easybuild/easyconfigs/b/blosc/blosc-1.20.1-CrayGNU-20.08.eb

ADIOS2 with MPI, hdf5, Python, Fortran, Bzip2 and Blosc support
== COMPLETED: Installation ended successfully (took 17 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/blosc/1.20.1-CrayGNU-20.08/easybuild/easybuild-blosc-1.20.1-20200914.192603.log
== COMPLETED: Installation ended successfully (took 2 min 37 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/adios/2.6.0-CrayGNU-20.08/easybuild/easybuild-adios-2.6.0-20200914.193208.log

[daint, dom] ADIOS2 for Parallel IO tutorial

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner.eb

This PR adds the plotly labextension, which was missing from this build. The production builds are already fixed by hand, so this PR should be merged, but should not be force installed.

[daint,dom] jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb

---

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.08-pat.eb

I provide also the instrumented CPU version of CP2K, since some users need it even on the hybrid nodes.

[daint-mc] CP2K (cpu only) with perftools lite

---

easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-pat.eb

EasyBuild recipe of VASP with `perftools-lite` (default from `cdt/20.08`).

[daint-mc] VASP recipe with perftools-lite

---

jenkins-builds/7.0.UP02-20.08-daint-gpu
jenkins-builds/7.0.UP02-20.08-daint-mc
jenkins-builds/7.0.UP02-20.08-dom-gpu
jenkins-builds/7.0.UP02-20.08-dom-mc

MATLAB recipe on `daint-gpu`, `daint-mc`, `dom-gpu` and `dom-mc` production lists (the latter to keep the systems in sync).

[dom daint] Add MATLAB to production lists

---

easybuild/easyconfigs/m/MATLAB/MATLAB-R2019a.eb

The build works on the `apps` folder but might fail on `scratch` with the following sanity error:
```
ERROR: Sanity check failed: no file found at 'toolbox/local/classpath.txt' in easybuild/software/MATLA/R2019a")
```

[daint-gpu] Update deprecated syntax in MATLAB recipe

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-20.08-cuda-pat.eb
easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.08-cuda-pat.eb

I provide the recipe to build the instrumented executable of QE-SIRIUS with the latest SIRIUS release.
The build was successful on the login node with my username on Piz Daint:  
```
== COMPLETED: Installation ended successfully (took 1 min 41 sec)
== Results of the build can be found in the log file(s) /apps/daint/UES/7.0.UP02/craypat/easybuild/software/QuantumESPRESSO-SIRIUS/6.5-rc4-CrayGNU-20.08-cuda-pat/easybuild/easybuild-QuantumESPRESSO-SIRIUS-6.5-rc4-20200922.100748.log
```

[daint-gpu] QE-SIRIUS with perftools-lite

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-CrayIntel-20.08.eb

I provide the recipe to build the latest release of QuantumESPRESSO (multicore only): I have linked `HDF5` and `libxc`: I have tested `pw.x` with `AUSURF112` and the performance is comparable to the previous release.

[daint-mc] QuantumESPRESSO 6.6

---

jenkins-builds/7.0.UP02-20.08-daint-gpu
jenkins-builds/7.0.UP02-20.08-daint-mc
jenkins-builds/7.0.UP02-20.08-dom-gpu
jenkins-builds/7.0.UP02-20.08-dom-mc

Updating `daint-gpu`, `daint-mc` as well as `dom-gpu` and `dom-mc` to keep Dom in sync with Piz Daint.

[daint-gpu] Add latest QuantumESPRESSO release in production as non default

---

easybuild/cray_external_modules_metadata-20.09.cfg

I provide an updated version of the Cray metadata file with CUDA 11.0 and GCC 9.3.0 supported by Nvidia: please let me know if the versions of Cray modulefiles still need to be hardcoded or if we can use the defaults.

[dom] Update Cray metadata for CDT 20.09

---

jenkins-builds/7.0.UP02-20.08-daint-mc
jenkins-builds/7.0.UP02-20.08-dom-mc

Remove `oq-engine` from `daint-mc` and `dom-mc` production lists: users can build the application using the easyconfigs provided in the repository. The current installation features a bug in the extension `celery` (see CSCS RT #40274), therefore it will be manually removed from the system as soon as this request is merged.

[daint-mc dom-mc] Remove oq-engine from production lists 

---

easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-cuda.eb

I'm providing an updated recipe for LAMMPS, adding the package `user-mofff`: I have tested the build successfully with the ReFrame checks (small and large production), therefore I don't see conflicts with the current packages provided.

[daint-gpu] LAMMPS with user-mofff

---

easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08.eb

I'm providing an updated recipe for LAMMPS on the multicore nodes, adding the package `user-mofff`: I have tested the build successfully with the ReFrame checks (small and large production), therefore I don't see conflicts with the current packages provided.

[daint-mc] LAMMPS with user-mofff

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner-cuda.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner.eb

Adding ipcmagic and dependencies back into the build. It was too messy with a separate module, and it led to a bug where the use of ipython at the command line failed with: ModuleNotFoundError: No module named 'ipyparallel'. The reason for this was the startup file /apps/daint/UES/jenkins/7.0.UP02/gpu/easybuild/software/IPython/7.7.0-CrayGNU-20.08-python3/startup/01-ipcmagic-cscs.py. So, previously, for this not to fail you needed to load the ipcmagic module in your .jupyterhub.env.
This should fix a bug needed for JF's course next week.

[daint,dom] ipcmagic is back

---

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-CrayIntel-20.08-pat.eb

I provide the EasyBuild recipe to build the instrumented executable of the latest release of QuantumESPRESSO: the environment variable defined below was necessary to get the performance report.
```
modextravars = {'PAT_RT_MPI_THREAD_REQUIRED': '3'}
```

[daint-mc] QuantumESPRESSO 6.6 instrumented with CrayPAT

---

easybuild/cray_external_modules_metadata-20.10.cfg

I have created a new metadata file for the Cray PE 20.10 recently installed on Dom (the file is exactly the same at the previous one).

[dom] New metadata file for PE 20.10

---

easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-20.10.eb
jenkins-builds/1.3.1-20.10-eiger

I had to add include and library flags for `cray-python`, since the Cray wrappers do not seem to add them to the compile and link lines, when the corresponding module is loaded.
I also had to remove some packages that are no longer available: see https://lammps.sandia.gov/doc/Commands_removed.html

[eiger] Last stable release of LAMMPS

---

easybuild/cray_external_modules_metadata-20.10.cfg
easybuild/easyconfigs/c/CDO/CDO-1.9.9-cpeGNU-20.10.eb
jenkins-builds/1.3.1-20.10-eiger

I had to insert `prefix` and `version` in the metadata file for the `CDO` dependency `cray-netcdf`, otherwise I was getting an error from the EasyBuild function `get_software_root`.

[eiger] Updated CDO and metadata with production list for Eiger

---

jenkins-builds/1.3.1-20.10-eiger

Add `matplotlib` in production (replaces `PyExtensions`)

[eiger] Update production list 1.3.1-20.10-eiger

---

easybuild/cray_external_modules_metadata-20.10.cfg

The prefix `CRAY_NETCDF_PREFIX` should not be needed on Dom, but it was needed on Eiger.

[dom] Fix netCDF PREFIX

---

jenkins/JenkinsfileUpdateEB

I have changed `BUILDPATH` to the default one under `$XDG_RUNTIME_DIR` since we use the login node and `/tmp` is not reliable: see my comments in some issues of https://jira.cscs.ch/browse/UES-1240. I have also fixed `TMPDIR` general access.

[dom-gpu] Minor changes in UpdateEB

---

easybuild/easyconfigs/j/jupyterlab/ipython-7.18.1-jupyter.patch
easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-20.10.eb
jenkins-builds/1.3.2-20.10-eiger

JupyterLab 2.2.8 without Julia kernel. We will reintroduce Julia kernel when we have a working Julia and JuliaExtensions (currently suffering from ENOTSUP).
Ready for merging.

[eiger] jupyterlab-2.2.8-cpeGNU-20.10.eb

---

easybuild/easyconfigs/e/ecCodes/ecCodes-2.19.1-cpeGNU-20.10.eb
easybuild/easyconfigs/l/libaec/libaec-1.0.4-cpeGNU-20.10.eb

I provide the recipes for `ecCodes` and dependencies as required by the custom `CDI` and `CDO` release (https://jira.cscs.ch/browse/SD-51043).

[eiger] ecCodes with libaec dependency

---

jenkins-builds/7.0.UP02-20.10-dom-gpu

Amber GPU fails to build on Dom with CUDA 11 with the error:
```
Error: Unsupported CUDA version 11.0 detected
```

[dom-gpu] Remove Amber from dom-gpu

---

jenkins-builds/7.0.UP02-20.10-dom-gpu

Remove older NAMD release from the updated GPU production list on Dom.

[dom-gpu] Remove NAMD 2.13 from dom-gpu

---

spack/daint/config.yaml

This PR avoids issues about running multiple Spack instances

[daint-gpu] Add config.yaml to Spack

---

jenkins-builds/7.0.UP02-20.10-dom-gpu

For Cuda 11 support, magma has to be upgraded to version 2.5.4: see https://jira.cscs.ch/browse/UES-1318.

[dom-gpu] Remove magma-2.4.0 from dom-gpu production list

---

easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.10-cuda.eb
easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-CrayGNU-20.10.eb
jenkins-builds/7.0.UP02-20.10-dom-gpu
jenkins-builds/7.0.UP02-20.10-dom-mc

Add LAMMPS 29 October 2020 version, as the March version could not compile with OpenMP and GCC 9+. A couple of pacakges have been removed from "core" so packages options have been changed slightly (as was done for Eiger). i did not modify the Python stuff - @lucamar if this is needed for forwards compatibility please let me know. Otherwise I think this is ready to just be merged.

[dom] create LAMMPS-29Oct20-CrayGNU-20.10.eb

---

easybuild/cray_external_modules_metadata-20.11.cfg

I provide the initial metadata file for Cray PE 20.11 on Dom.

[dom] Cray external metadata file for PE 20.11 on Dom

---

jenkins/JenkinsfileUpdateEB

Replace `cdt` with `cdt-cuda` in `UpdateEB` to build the software stack on Dom.

[dom] Switch to cdt-cuda in UpdateEB

---

easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.26.eb

The tarball of version 2.2.26 is no longer available for download from the FTP server: see https://jira.cscs.ch/browse/UES-13[66-69].

[dom] Fix UDUNITS 2.2.26 download

---

easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.10.eb

Download from ELPA web server is often unreliable, use local downloaded file instead (see https://jira.cscs.ch/browse/UES-1365).

[dom-mc] Fix ELPA download (multicore)

---

easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayGNU-20.10-cuda.eb

Download from ELPA web server is often unreliable, use local downloaded file instead (see https://jira.cscs.ch/browse/UES-1364).

[dom-gpu] Fix ELPA cuda download

---

jenkins-builds/7.0.UP02-20.08-daint-gpu
jenkins-builds/7.0.UP02-20.08-daint-mc

I have added the recipes of the latest CP2K stable release 8.1 in the production lists on Piz Daint.

[daint] Add CP2K 8.1 in production

---

easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-cuda.eb
easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-cuda.psmp
easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-20.11-cuda.eb
jenkins-builds/7.0.UP02-20.11-dom-gpu

CP2K latest stable release with the corresponding architecture file and ELPA dependency updated.

[dom-gpu] CP2K 8.1 with PE 20.11

---

easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11.eb
easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU.psmp
easybuild/easyconfigs/e/ELPA/ELPA-2020.11.001-CrayGNU-20.11.eb
jenkins-builds/7.0.UP02-20.11-dom-mc

CP2K latest stable release with the corresponding architecture file and ELPA dependency updated (multicore).

[dom-mc] CP2K 8.1 with PE 20.11 (multicore)

---

easybuild/easyblocks/julia.py
easybuild/easyblocks/juliabundle.py
easybuild/easyblocks/juliapackage.py
easybuild/easyconfigs/j/Julia/Julia-1.5.3-CrayGNU-20.08-cuda.eb
easybuild/easyconfigs/j/Julia/Julia-1.5.3-CrayGNU-20.08.eb
easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.3-CrayGNU-20.08-cuda.eb
easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.3-CrayGNU-20.08.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner.eb
jenkins-builds/7.0.UP02-20.08-daint-gpu
jenkins-builds/7.0.UP02-20.08-daint-mc
jenkins-builds/7.0.UP02-20.08-dom-gpu
jenkins-builds/7.0.UP02-20.08-dom-mc

Building and testing of certain packages from within the Julia Pkg manager can fail due to the Julia startup file. Either because 1) it gives an error if the DEPOT_PATH/LOAD_PATH were modified and the length does not correspond to length(USER_DEPOT_PATH) + length(ADMIN_DEPOT_PATH) or length(USER_LOAD_PATH) + length(ADMIN_LOAD_PATH)  or 2) the startup file is deactivated (according to the documentation, building happens without startup file by default except if julia is called explicitly with --startup-file=yes).
1. The modules leave the DEPOT_PATH and LOAD_PATH essentially as defined by default by the Julia installation (introducing though mc and daint as well as using #.#.#).
2. The modules define the ADMIN_DEPOT_PATH and ADMIN_LOAD_PATH environment variables as before, with the …

[daint] Add Julia 1.5.3 and improve Julia admin path handling

---

easybuild/easyconfigs/p/pybind11/pybind11-2.6.1-CrayGNU-20.11.eb

The former EXTERNAL_MODULE seems to break ReBuildEB

[dom] fix cmake version in pybind11

---

easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-cpeCCE-20.10-OSMesa-python3.eb

This fix enables correct loading of the python library for all executables (pvbatch, pvserver, pvpython). Thanks to @teojgo who identified the bug

[eiger] on eiger, the libpython3.8.so is in a different place

---

easybuild/easyconfigs/c/cpeCray/cpeCray-21.02.eb
easybuild/easyconfigs/g/GSL/GSL-2.6-cpeCray-21.02.eb
jenkins-builds/1.3.2-21.02-pilatus

The new name will be used on Eiger after the upgrade as well.

[pilatus] Rename toolchain cpeCCE as cpeCray

---

jenkins-builds/1.3.2-21.02-pilatus
jenkins/README.md

I have added the recipe of the latest ReFrame release in the production list of Pilatus.

[pilatus] Reframe 3.4.2 as default on Pilatus

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-21.02.eb

This PR removes the NVIDIA dashboard python modules. This was causing warnings in the jupyter logfile related to missing pynvml.

[pilatus] Update jupyterlab-2.2.8-cpeGNU-21.02.eb

---

jenkins-builds/1.3.2-21.02-pilatus

I have added `jupyter-utils` and `juypterlab` on Pilatus: the first one is built with the system toolchain, therefore the corresponding modulefile will be installed under the `Core` folder. 
The `jupyterlab` modulefile will be installed under to corresponding toolchain folder instead and it will be available for loading only after the toolchain modulefile `cpeGNU/21.02` is loaded (Lmod hierarchy).

[pilatus] Update production list 1.3.2-21.02-pilatus

---

easybuild/easyconfigs/v/VASP/VASP-6.2.0-cpeIntel-21.02.eb
easybuild/easyconfigs/v/VASP/VASP-6.2.0-cpeIntel.makefile.include
jenkins-builds/1.3.2-21.02-pilatus

I provide the recipe of the latest stable release of VASP with the toolchain `cpeIntel` and PE 21.02 on Pilatus.

[pilatus] VASP 6.2.0 on Pilatus

---

easybuild/cray_external_modules_metadata-21.02.cfg
easybuild/easyconfigs/l/libxc/libxc-5.1.2-cpeGNU-21.02.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7-cpeGNU-21.02.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeGNU-21.02.eb
jenkins-builds/1.3.2-21.02-pilatus

I provide the recipe of QuantumESPRESSO 6.7.0 with the toolchain `cpeGNU/21.02`: the more recent version of the `libxc` library is added for future use, since it could not be used immediately as a dependency.
The `prefix` and `version` of some key modules provided by the Cray Programming Environment have been added to the metadata file, in order to get the correct library path of the corresponding library with the `EBROOT` variables.

[pilatus] QuantumESPRESSO 6.7.0

---

easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-20.08.eb
easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayIntel-20.08.eb
jenkins-builds/7.0.UP02-20.08-daint-gpu
jenkins-builds/7.0.UP02-20.08-daint-mc

Recipe for Boost 1.75.0 on Daint with Cray Programming Environment 20.08 both GNU and Intel (required for HPX CI). Built and tested locally.

[daint] Add Boost 1.75.0 with CrayGNU 20.08

---

jenkins-builds/7.0.UP02-20.08-daint-gpu
jenkins-builds/7.0.UP02-20.08-daint-mc
jenkins-builds/7.0.UP02-20.11-dom-gpu
jenkins-builds/7.0.UP02-20.11-dom-mc

Remove the flag `--set-default` from the `-serial` build of `h5py` in the production lists of Dom and Piz Daint.

[daint dom] Set h5py parallel default

---

easybuild/easyconfigs/l/libreadline/libreadline-8.1-cpeGNU-21.02.eb
easybuild/easyconfigs/n/ncurses/ncurses-6.2-cpeGNU-21.02.eb
easybuild/easyconfigs/p/PROJ/PROJ-8.0.0-cpeGNU-21.02.eb
easybuild/easyconfigs/s/SQLite/SQLite-3.34.1-cpeGNU-21.02.eb

I provide the recipe and dependencies of `PROJ` (latest stable release 8.0.0) with Cray PE 21.02 on Pilatus: I'm not adding the module directly in the production list, since it will be a dependency of the new module `CDO` (to be submitted soon).

[pilatus] PROJ 8 and dependencies

---

easybuild/easyconfigs/c/CDO/CDO-1.9.9-cpeGNU-20.10.eb

The CDO module is installed on the system, but the recipe is not working due to the open issue of libtool unhandled argument with `cray-dsmml/0.1.3` (https://jira.cscs.ch/browse/SD-51192): I'm restoring the recipe in production to avoid failures in `ProductionEB`.

[eiger] Restore recipe of CDO 1.9.9 in production

---

easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-cpeGNU-21.02-python3.eb
easybuild/easyconfigs/n/NCO/NCO-4.9.7-cpeGNU-21.01.eb
easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28-cpeGNU-21.02.eb
jenkins-builds/1.3.2-21.02-pilatus

I provide the recipe of the latest stable release of NCO and its dependencies with Cray PE 21.02 on Pilatus.

[pilatus] NCO with PE 21.02

---

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11-pat.eb
easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-pat.eb

The default module in production will still be CP2K 7.1 due to a performance issue with the gpu release of CP2K 8.1: for the sake consistency, I keep the same default also with the mc release. I provide a minor fix for production recipe of CP2K 7.1 as well.

[dom-mc] CP2K 7.1 and 8.1 with CrayPAT 20.11

---

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-20.11-cuda-pat.eb
easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.11-cuda-pat.eb

The default module in production will still be CP2K 7.1 due to a performance issue with CP2K 8.1.

[dom-gpu] CP2K 7.1 and 8.1 with CrayPAT 20.11

---

jenkins-builds/1.3.2-21.02-pilatus

This module is required for the JenkinsfileUpdateEB project for the automation of the Github PRs.

[pilatus] Add hub to production list

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.11-batchspawner-cuda.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.11-batchspawner.eb

Adds a single requirement for EMPA course. This was added to 20.08 after the freeze so was not caught by the auto-update to 20.11. Thus needs to be deployed by hand.

[dom] Update jupyterlab-2.0.2-CrayGNU-20.11-batchspawner-cuda.eb

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-20.10.eb

Bump jupyterhub version to 1.3.0 to match upgrade on the VM. No updates required for jupyterhub dependencies.

[eiger] Update jupyterlab-2.2.8-cpeGNU-20.10.eb

---

easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.11-EGL-python3.eb

fixes https://jira.cscs.ch/browse/SD-51595
Not having the possibility and time to test all client OSs to test ParaView in client-server mode (I don't have a Mac), we missed the case where desktop client do not have an NVIDIA card and the plugin (even though it is loaded on the Daint server-side) causes failure on the client side. We turn it off with this patch.

[daint-gpu] Do not auto-load the NVIDIA IndeX plugin

---

easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.7-CrayGNU-20.11-cuda.eb
easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.1-CrayGNU-20.11-cuda-mkl.eb

SpFFT 0.9.10 doesn't work with Cuda 11. 
The official QE-SIRIUS installation, `QuantumESPRESSO-SIRIUS/6.5-rc4-CrayGNU-20.11-cuda`, on daint is broken at the moment and should be reinstalled after merging this PR.

[daint-gpu] SpFFT 0.9.10 isn't compatible with cuda 11, upgrade it

---

easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.11-OSMesa-python3.eb

== COMPLETED: Installation ended successfully (took 25 min 35 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.9.0-CrayGNU-20.11-OSMesa-python3/easybuild/easybuild-ParaView-5.9.0-20210323.203118.log

[daint-mc] Materials were missing from install dir

---

easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayCCE-20.11.eb
easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayIntel-20.11.eb
easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-CrayCCE-20.11.eb
easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-CrayIntel-20.11.eb
easybuild/easyconfigs/z/zlib/zlib-1.2.11-CrayCCE-20.11.eb
jenkins-builds/7.0.UP02-20.11-daint-gpu
jenkins-builds/7.0.UP02-20.11-daint-mc

Also add them to production lists.
I haven't tested the CrayCCE recipe (I'm assuming the two others will work just fine). Hoping to have CI tell me if I've done something wrong.

[daint] Update Boost recipes to 20.11 toolchains

---

jenkins-builds/7.0.UP02-20.11-daint-gpu
jenkins-builds/7.0.UP02-20.11-daint-mc
jenkins-builds/7.0.UP02-20.11-dom-gpu
jenkins-builds/7.0.UP02-20.11-dom-mc

I am not deploynd as default yet since this is also introduces a major release difference.

[dom daint] Deploy h5py 3.2.1 on dom/daint

---

easybuild/easyconfigs/a/Amber/Amber-20-15-9-cpeIntel-21.03.eb
easybuild/easyconfigs/j/JasPer/JasPer-2.0.32-cpeGNU-21.03.eb
easybuild/easyconfigs/n/NCO/NCO-4.9.8-cpeGNU-21.03.eb

Remove `cray-hdf5` from Amber since it's not provided by `cpeIntel 21.04` and fix NCO filename (tested in https://jenkins.cscs.ch/blue/organizations/jenkins/UpdateEB/detail/UpdateEB/2/pipeline/, therefore it will be merged immediately).

[eiger] Fix Amber and NCO with PE 21.03

---

easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11-cuda.eb
easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11.eb

xalt hijacks libcurl.so through LD_LIBRARY_PATH as julia tries to open a vendored version of the library.
This results in warning messages when using Downloads.jl (which is used by the package manager).
Julia has good reasons to vendor libcurl: https://julialang.org/blog/2021/03/julia-1.6-highlights/#downloads_networkingoptions
So we should drop xalt here.
Pinging @lucamar, @omlins, @gppezzi

[dom] Drop xalt when loading julia, since it hijacks libcurl.so and is incompatible

---

jenkins-builds/7.0.UP02-20.11-daint-gpu
jenkins-builds/7.0.UP02-20.11-daint-mc
jenkins-builds/7.0.UP02-20.11-dom-gpu
jenkins-builds/7.0.UP02-20.11-dom-mc

This changes the default Julia to 1.6 which offers a bunch of enhancements, and very little regression.. if any! JupyterLab kernel is already at 1.6, so this will align termianl and jupyter behaviour nicely.

[daint] Update 7.0.UP02-20.11-daint-gpu

---

easybuild/easyconfigs/g/GSL/GSL-2.6-CrayGNU-20.11.eb
easybuild/easyconfigs/l/libxc/libxc-5.1.2-CrayGNU-20.11.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.7-rc1-CrayGNU-20.11-cuda.eb
easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.0-CrayGNU-20.11-cuda.eb
easybuild/easyconfigs/s/SPLA/SPLA-1.3.0-CrayGNU-20.11-cuda-mkl.eb
easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.1-CrayGNU-20.11-cuda-mkl.eb

This should be a solution to fix 
https://github.com/eth-cscs/production/pull/2228 
and 
https://github.com/eth-cscs/production/pull/2199
We just update to the latest version of the code. However, there is a problem. QE now uses CMake in combination with git submodules (for example, `qe_git_submodule_update(external/fox)`). This means that it can be easily installed from the git repository and not so easily from the tar.gz release if the submodules are available as external packages (I'm not sure it will even work). So the QE EB recipe must be changed to fetch the source from our git development branch. I know it's a path towards a rolling release model, but that should also be supported in our way of deploying software.

[daint-gpu] Add latest QE/SIRIUS

---

spack/daint/config.yaml
spack/daint/packages.yaml

This fixes two issues:
1.  `intel-mkl` package not being able to be installed with the `${RANDOM}` in the build path
2. For some strange reason, the `netcdf` modules have the wrong versions

[daint] Update Spack config for version develop on daint

---

spack/0.15.4/daint/packages.yaml

This fixes one issue:
1. For some strange reason, the `netcdf` modules have the wrong versions

[daint] Update Spack config for version 0.15.4 on daint

---

spack/0.16.1/daint/config.yaml
spack/0.16.1/daint/packages.yaml

This fixes two issues:
1.  `intel-mkl` package not being able to be installed with the `${RANDOM}` in the build path
2. For some strange reason, the `netcdf` modules have the wrong versions

[daint] Update Spack config for version 0.16.1 on daint

---

easybuild/easyconfigs/l/libxc/libxc-4.3.4-cpeIntel-21.04.eb
easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-cpeIntel-21.04.eb
jenkins-builds/1.4.0-21.04-eiger

QuantumESPRESSO and dependencies with the Intel compiler to address the issue with `cray-libsci` reported in [SD-52008](https://jira.cscs.ch/browse/SD-52008): `cray-hdf5` is not available with `PrgEnv-intel`, therefore it has been removed with respect to the build with `cpeGNU`.

[eiger] QuantumESPRESSO with cpeIntel

---

easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11-cuda.eb
easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11.eb

It was added to work around some weird issue where curl would complain about incomplete downloads, but in the end it happened with & without this variable.
Turns out it is useful to unset it, because then the julia package registry gets updated by just a download into ~/.julia/... when you run Pkg.update(), whereas when this variable is set to empty git clone the registry into ~/.julia/..., which curently fails because git tries to mmap something and that fails on the $HOME filesystem.

[dom daint] Remove JULIA_PKG_SERVER

---

easybuild/easyconfigs/c/CMake/CMake-3.14.5.eb

Use the configure option `--system-curl` to use system cURL to avoid the undefined reference to 'DH_get_nid@OPENSSL_1_1_0i' when building cURL on dom101, as explained in [SD-52103](https://jira.cscs.ch/browse/SD-52103).

[dom] Fix CMake on Dom

---

easybuild/module/EasyBuild-custom/cscs

If `XDG_RUNTIME_DIR` is not set, then `TMPDIR` should point to `tmp` as `BUILDPATH`.

[daint dom eiger tsa] Fix TMPDIR 

---

jenkins-builds/1.4.0-21.04-eiger
jenkins-builds/1.4.0-21.04-pilatus

I add the latest release of NCL on Eiger and Pilatus production lists to address [SD-51081](https://jira.cscs.ch/browse/SD-51081).

[eiger pilatus] Add NCL 6.6.2 in production

---

easybuild/module/EasyBuild-custom/cscs
easybuild/module/EasyBuild-custom/cscs.lua

I have realized that the EasyBuild-custom modulefile does not export correctly `EASYBUILD_PREFIX` for user `jenscscs` on Eiger and Pilatus (Cray with Lmod): the reason could be an issue with the script `tcl2lua.tcl` invoked by Lmod to convert Tcl to Lua syntax.
I have tried to fix the Tcl modulefile enclosed to this pull request removing the following line, which should not be necessary:
```
setenv EASYBUILD_PREFIX                     $::env(EASYBUILD_PREFIX)
```
However, the modified Tcl modulefile does not still work for user `jenscscs` on the systems with Lmod, therefore I provide the corresponding Lua modulefile which will only be loaded on systems with Lmod: the other systems will still load the Tcl modulefile.

[eiger pilatus] Fix EB custom modulefile for Lmod

---

easybuild/module/EasyBuild-custom/cscs.lua

Read the environment variable `CLUSTER_NAME` if `LMOD_SYSTEM_NAME` is not defined.

[eiger] Fix EasyBuild custom modulefile on Eiger

---

easybuild/module/EasyBuild-custom/cscs
easybuild/module/EasyBuild-custom/cscs.lua

I have implemented the change following the instructions on the [EasyBuild documentation](https://docs.easybuild.io/en/latest/Including_additional_Python_modules.html), since we have a custom module naming scheme and custom toolchains: using the include variables, we can avoid to copy manually the python scripts, therefore I have adapted [our Confluence page](https://confluence.cscs.ch/display/GENERAL/EasyBuild+at+CSCS) accordingly. 
You can check that the new custom modulefiles add the correct python scripts switching to the latest non-default `EasyBuild/4.4.0` (I have removed the custom python scripts from the standard installation folder) with the commands:
```
git clone git@github.com:lucamar/production.git
cd production
git checkout eb-custom
module use $PWD/easybuild/module
module …
```

[daint dom eiger pilatus tsa] Include custom MNS and toolchains

---

easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-CrayGNU-20.11.eb
easybuild/easyconfigs/x/x264/x264-20191217-CrayGNU-20.11.eb

== COMPLETED: Installation ended successfully (took 20 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/x264/20191217-CrayGNU-20.11/easybuild/easybuild-x264-20191217-20210616.161055.log
== COMPLETED: Installation ended successfully (took 1 min 52 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/FFmpeg/4.4-CrayGNU-20.11/easybuild/easybuild-FFmpeg-4.4-20210616.161717.log

[daint] adding libx264 encoding options

---

easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-CrayGNU-20.11.eb
easybuild/easyconfigs/x/x265/x265-3.2.1-CrayGNU-20.11.eb

== COMPLETED: Installation ended successfully (took 1 min 23 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/x265/3.2.1-CrayGNU-20.11/easybuild/easybuild-x265-3.2.1-20210618.170117.log
== COMPLETED: Installation ended successfully (took 2 min 1 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/FFmpeg/4.4-CrayGNU-20.11/easybuild/easybuild-FFmpeg-4.4-20210618.170431.log
a video can be encoded in this manner:
ffmpeg -i animation_%06d.jpg  -c:v libx265  -vf format=yuv420p  -tag:v hvc1 test_265.mp4

[daint] provide X265 encoding

---

easybuild/module/EasyBuild-custom/cscs.lua

The change to `cscs.lua` will fix the Lmod warning shown on Eiger and Pilatus for `EASYBUILD_INSTALLPATH` when `EASYBUILD_PREFIX` is not defined before loading the custom module:
```
Lmod Warning:  Syntax error in file:
/apps/pilatus/UES/modulefiles/EasyBuild-custom/cscs.lua
with command: setenv, one or more arguments are not strings.
```
The new modulefile will also keep different prefix and installpath values if they are exported before loading `EasyBuild-custom/cscs`, without overwriting the installpath with the chosen prefix: this is relevant on Eiger and Pilatus with the hierarchical module naming scheme, if a user wants to build new local modules on top of the ones provided by CSCS staff.

[eiger pilatus] Fix cscs Lua modulefile to avoid Lmod warning

---

easybuild/easyblocks/matlab.py
easybuild/easyconfigs/m/MATLAB/MATLAB-R2021a.eb
jenkins-builds/7.0.UP02-20.11-daint-gpu
jenkins-builds/7.0.UP02-20.11-daint-mc
jenkins-builds/7.0.UP02-20.11-dom-gpu
jenkins-builds/7.0.UP02-20.11-dom-mc
jenkins-builds/7.0.UP02-21.02-dom-gpu
jenkins-builds/7.0.UP02-21.02-dom-mc

I provide a fix for [UES-1617](https://jira.cscs.ch/browse/UES-1617) and [UES-1619](https://jira.cscs.ch/browse/UES-1619), replacing MATLAB `R2019a` with the latest `R2021a` in the production lists of Dom and Piz Daint:
- LooseVersion in the easyblock `matlab.py` is fixed with Python3 following [a similar issue](https://github.com/easybuilders/easybuild-easyblocks/issues/1792)
- I added a `FIXME` in the easyconfig file `MATLAB-R2021a.eb` since the `open()` function raises an error only with EasyBuild 4.4.0 and newer, not with 4.3.4 (`Failed to copy 'local_filehandle' easyconfig parameter: cannot serialize '_io.TextIOWrapper' object`)

[daint dom] Fix MATLAB

---

jenkins-builds/1.4.0-21.07-eiger

Add `FFmpeg` 21.07 in production with PE 21.07 (currently on Pilatus only): this pull request depends on #2410.

[pilatus] Add FFmpeg to 21.07 software stack

---

easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.06.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.05.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.06.eb

I provide a fixed recipe for PLUMED with PE 21.05 and 21.06 that avoids linking the non-threaded release of `cray-libsci` (see [SD-52306](https://jira.cscs.ch/browse/SD-52306)).

[eiger] Fix PLUMED 2.7.1

---

easybuild/easyconfigs/c/CGAL/CGAL-4.14.3-CrayGNU-20.11.eb
easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2106-CrayGNU-20.11.eb
easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-v2106

Updated source URL as well as dependencies using cray-tpsl instead of Scotch built using EB.

[daint-mc] Add OpenFOAM v2106 for CrayGNU 20.11

---

easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-CrayGNU-20.11.eb
easybuild/easyconfigs/m/Mesa/Mesa-21.2.1-CrayGNU-20.11.eb
easybuild/easyconfigs/m/Meson/Meson-0.59.1-CrayGNU-20.11-python3.eb
easybuild/easyconfigs/n/Ninja/Ninja-1.10.2-CrayGNU-20.11-python3.eb

the old driver had:
################ Remote Render Server ############
Vendor:   VMware, Inc.
Version:  3.3 (Core Profile) Mesa 18.3.3
Renderer: llvmpipe (LLVM 8.0, 256 bits)
##################################################
the new driver has:
################ Remote Render Server ############
Vendor:   Mesa/X.org
Version:  4.5 (Core Profile) Mesa 21.2.1
Renderer: llvmpipe (LLVM 9.0.1, 256 bits)
##################################################
== COMPLETED: Installation ended successfully (took 2 mins 59 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Mesa/21.2.1-CrayGNU-20.11/easybuild/easybuild-Mesa-21.2.1-20210910.091009.log

[daint-mc] major Mesa upgrade for cpu-based rendering for ParaView

---

spack/reframe/spack.py
spack/reframe/src/spack_util/spacklib.py

The cdt is not part of the package version, so instead use [package version]-[cdt version] as a way to make compilers & externals use the cdt

Use '-[cdt version]' as a suffix

---

spack/reframe/spack.py
spack/reframe/src/config/0.15.4/config.yaml
spack/reframe/src/config/0.16.2/config.yaml
spack/reframe/src/config/develop/config.yaml

To avoid build errors with spack 0.15.x we are better off making spack use the reframe stage dir throughout

Use the reframe stage dir for spack stage & install

---

spack/reframe/spack.py

Thanks @haampie and @ekouts for the support!
It's a bit hacky, let me know how can we improve it.
EDIT:
Main points:
1. home folder: set the home folder to the stage dir, so that user configurations stored in `$HOME/.spack` do not kick in
2. bootstrap store: it is stored in home folder, that would be otherwise shared by all tests running in parallel, that seems problematic. if we don't want to re-bootstrap, we can opt for running pkg tests sequentially.
3. fix problem with stage dir #2474: the config_check test was shared by all the tests in parallel that were competing for setting the same variable in the shared environment.

[daint dom eiger pilatus tsa] Workarounds for spack config generator

---

spack/readme.md

The store/database of spack moved inside the reframe stage dir for each
test, but that can cause errors about long path names. Simple solution
is to make reframe create a stage dir in /tmp

Use short dir for reframe stage in spack test

---

easybuild/easyconfigs/e/expat/expat-2.2.10-CrayGNU-20.11.eb

Source is no longer hosted on sourceforge. Fixes SD-53430.
This builds, but please feel free to modify the variable usage convention according to current preferences (e.g. SOURCELOWER_TAR_XZ...)

[daint,dom] Update expat-2.2.10-CrayGNU-20.11.eb

---

easybuild/easyconfigs/v/VTK/VTK-9.1.0-CrayGNU-20.11-EGL-python3.eb

== COMPLETED: Installation ended successfully (took 16 mins 42 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VTK/9.1.0-CrayGNU-20.11-EGL-python3/easybuild/easybuild-VTK-9.1.0-20211107.104509.log
Release notes: https://gitlab.kitware.com/vtk/vtk/-/blob/master/Documentation/release/9.1.md

[daint-gpu] Major VTK upgrade

---

easybuild/easyconfigs/v/VTK/VTK-9.1.0-CrayGNU-20.11-EGL-python3.eb

a fix for https://jira.cscs.ch/projects/SD/queues/custom/48/SD-53788
I also change cray-python from 3.8.5.0 to 3.8.5.1 because the newer module adds /opt/python/3.8.5.1/lib to LD_LIBRARY_PATH. That's one less problem to handle. I can now re-introduce the sanity check.
== COMPLETED: Installation ended successfully (took 24 mins 58 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VTK/9.1.0-CrayGNU-20.11-EGL-python3/easybuild/easybuild-VTK-9.1.0-20211111.145209.log

[daint-gpu] fix for compilation and runtime issue for 3rd party apps

---

easybuild/easyconfigs/j/Julia/Julia-1.6.3-cpeGNU-21.09.eb
easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.3-cpeGNU-21.09.eb
easybuild/easyconfigs/o/oidn/oidn-1.4.1-cpeCray-21.09.eb
easybuild/easyconfigs/o/ospray/ospray-2.7.0-cpeCray-21.09.eb
easybuild/easyconfigs/v/VTK/VTK-9.1.0-cpeCray-21.09-OSMesa-python3.eb
easybuild/module/EasyBuild-custom/cscs.lua
jenkins-builds/1.4.0-21.09-eiger

Pilatus toolchains default version is now 21.09, while Eiger will still keep 21.08: I have fixed the EasyBuild metadata accordingly. 
I am also updating the production list of 21.09 with the latest version of ReFrame, Julia, JuliaExtensions and VTK.

[pilatus] Update Pilatus builds

---

easybuild/easyconfigs/c/CDO/CDO-1.9.10-foss-2019b.eb
easybuild/easyconfigs/c/CDO/CDO-1.9.10-fosscuda-2019b.eb
easybuild/easyconfigs/e/ecCodes/ecCodes-2.23.0-foss-2019b-python3.eb
easybuild/easyconfigs/e/ecCodes/ecCodes-2.23.0-fosscuda-2019b-python3.eb
easybuild/easyconfigs/l/libaec/libaec-1.0.6-foss-2019b.eb
easybuild/easyconfigs/l/libaec/libaec-1.0.6-fosscuda-2019b.eb

I provide the recipes of CDO, ecCodes and libaec with the toolchains `foss` and `fosscuda`, version `2019b` (see [SD-53816](https://jira.cscs.ch/browse/SD-53816)).

[tsa] Updated CDO with ecCodes and libaec

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.09.eb

This upgrades the JupyterLab Julia kernel to julia 1.6.3, to match the new version on Pilatus.

[pilatus] jupyterlab-2.2.10-cpeGNU-21.09.eb

---

easybuild/easyconfigs/v/VTK/VTK-9.1.0-cpeCray-21.08-OSMesa-python3.eb

== COMPLETED: Installation ended successfully (took 16 mins 6 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/VTK/9.1.0-cpeCray-21.08-OSMesa-python3/easybuild/easybuild-VTK-9.1.0-20211209.110912.log

[eiger] fix LD_LIBRARY_PATH and restored sanity check

---

easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-CrayGNU-21.09-EGL.eb
jenkins-builds/7.0.UP03-21.09-dom-gpu

I provide the recipe of ParaView with EGL and dependencies with CDT 21.09 on Dom: I have removed the suffix `-python3`, since only Python3 is supported.
Please note that the build of ParaView would fail on GPFS due to the issue reported in [SD-53990](https://jira.cscs.ch/browse/SD-53990), since the `postinstallcmds` use `git clone`.

[dom-gpu] ParaView with EGL

---

easybuild/easyconfigs/c/Cython/Cython-0.29.25-CrayGNU-21.09.eb
easybuild/easyconfigs/c/cftime/site.py
easybuild/easyconfigs/n/NCO/NCO-5.0.4-CrayGNU-21.09.eb
easybuild/easyconfigs/n/numpy/mkl-2021-sitecfg.patch
easybuild/easyconfigs/n/numpy/numpy-1.21.4-CrayGNU-21.09.eb
easybuild/easyconfigs/p/pycuda/site.py
jenkins-builds/7.0.UP03-21.09-dom-gpu
jenkins-builds/7.0.UP03-21.09-dom-mc
jenkins/JenkinsfileUpdateEB

I provide some minor updates for the new production lists and recipes with Cray PE 21.09 on Dom, including `NCO` @omlins and `numpy` @henrique (is it still needed? The recent `cray-python/3.9.4.1` features `numpy` release `1.20.1`).

[dom] Update lists and recipes for Dom

---

easybuild/easyconfigs/m/Mako/Mako-1.1.5-cpeCray-21.09-python3.eb
easybuild/easyconfigs/m/Meson/Meson-0.59.2-cpeCray-21.09-python3.eb
easybuild/easyconfigs/w/wheel/wheel-0.37.0-cpeCray-21.09.eb

I provide updated recipes for Python packages on Pilatus with Cray PE 21.09 as in  #2566.

[pilatus] Update Python packages

---

easybuild/cpe_external_modules_metadata-21.10.cfg
easybuild/cpe_external_modules_metadata-21.11.cfg
easybuild/easyconfigs/v/VASP/VASP-6.2.1-cpeIntel.makefile.include
easybuild/toolchains/compiler/cpe.py
easybuild/toolchains/compiler/craype.py

Update Intel compiler options for oneAPI and add external metadata for CPE 21.10 and 21.11.

[daint dom eiger pilatus tsa] Update compiler definitions and external metadata

---

easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.5.0-CrayGNU-21.09.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.09-batchspawner-cuda.eb
easybuild/easyconfigs/n/nodejs/nodejs-16.13.2-CrayGNU-21.09.eb
easybuild/easyconfigs/n/nodejs/nodejs-16.13.2.eb

The new `nodejs` recipe used by `configurable-http-proxy` will build with the compiler provided by the operating system (the CrayGNU `nodejs` recipe is enclosed to the pull request but not used as dependency in any recipe at present).

[dom-gpu] Update JupyterLab dependencies

---

easybuild/easyconfigs/b/BAGEL/BAGEL-1.2.2-CrayGNU-20.11.eb
easybuild/easyconfigs/b/BAGEL/BAGEL-1.2.2-CrayIntel-20.11.eb
easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-20.11.eb
easybuild/easyconfigs/l/libxc/libxc-5.1.6-CrayGNU-20.11.eb

Tentative recipe of BAGEL with CrayIntel 20.11 for [SD-54169](https://jira.cscs.ch/browse/SD-54169): I had to use Boost 1.70.0 as a dependency since 1.75.0 was making the build fail. 
The configure option `--with-mpi=intel` is due to the limited choices available (`intel`, `mvapich` or `openmpi` only): the executable [needs to be tested beforehand](https://nubakery.org/quickstart/how_to_run_bagel.html).

[daint-mc] BAGEL with Cray

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb

Updated JupyterLab for 21.09. This is JupyterLab 3.x which is a breaking change for labextensions and other functionality.
- updated packages
- change from source install to wheels where available
- added cupy in cuda build
- ipykernel, R 4.1 kernel, Julia 1.6.3 kernel functioning
- integrate dask to ensure compatibility with labextension
- new ipyparallel labextension
- NB: nvdashboard non functioning
- NB: itkwidgets non functioning
- NB: ipyparaview non functioning
- NB: jupyter code formatter doesn't work, commented out

[dom] jupyterlab 3.2.8

---

easybuild/easyconfigs/v/VASP/VASP-6.2.1-CrayIntel-21.09-cuda.eb
easybuild/easyconfigs/v/VASP/VASP-6.2.1-CrayIntel-cuda.makefile.include
jenkins-builds/7.0.UP03-21.09-dom-gpu

Recipe for the CUDA port of VASP 6.2.1 in production (it might still outperform the OpenACC port in some cases, therefore I keep it default although deprecated).

[dom-gpu] VASP 6.2.1

---

jenkins-builds/7.0.UP03-21.09-dom-gpu
jenkins-builds/7.0.UP03-21.09-dom-mc

Adds Jupyterlab 3.2.8 and removes the temporary Jupyterlab 2, which will not be supported.

[dom] Update JupyterLab release in production

---

easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-CrayGNU-21.09-cuda.eb
jenkins-builds/7.0.UP03-21.09-dom-gpu

I provide the recipe for the latest GROMACS release 2021.5 with CDT 21.09.

[dom-gpu] Update GROMACS gpu with 21.09

---

easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09-cuda.eb
easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-cuda.psmp
easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-cuda-mkl.eb

I provide the recipe of CP2K 9.1 with the latest SIRIUS including ELPA: I kept `-DUSE_CRAY_LIBSCI=0` and `-DUSE_MKL=1` as in the current modulefile in production, although the build with `cray-libsci` seems to work well too.

[dom-gpu] CP2K 9.1 with SIRIUS (cuda-mkl)

---

easybuild/easyconfigs/c/CrayNvidia/CrayNvidia-21.05.eb
easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-21.05-acc.eb
easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-acc.makefile.include

Use QD from module `nvidia` and add QD library path to `CrayNvidia` modulefile at runtime.

[daint-gpu] VASP 6.3.0 fix with 21.05

---

easybuild/easyconfigs/v/VTK/VTK-9.1.0-CrayGNU-21.09-EGL-python3.eb

restore sanity check and add path to TBB libs
== COMPLETED: Installation ended successfully (took 16 mins 41 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/VTK/9.1.0-CrayGNU-21.09-EGL-python3/easybuild/easybuild-VTK-9.1.0-20220201.153333.log

[dom-gpu] VTK v9.1 for cdt21.09

---

easybuild/easyconfigs/m/Mesa/Mesa-21.3.2-cpeCray-21.12.eb

The build of Mesa 21.3.2 using `cpeCray` 21.12 is now fixed with `cce/13.0.1` as anticipated in the Cray case linked to [AVAILAPPS-49](https://jira.cscs.ch/browse/AVAILAPPS-49).

[pilatus] Fix Mesa build 

---

jenkins-builds/7.0.UP03-21.09-daint-gpu

VASP 6.3.0 OpenACC will be the default as the CUDA-C GPU port is deprecated.

[dom-gpu] Update VASP default

---

easybuild/easyconfigs/j/Julia/Julia-1.7.2-CrayGNU-20.11-cuda.eb
easybuild/easyconfigs/j/Julia/Julia-1.7.2-CrayGNU-20.11.eb

This Julia recipes does
- install Julia without any packages
- set environment variables for the installation of packages that rely on system libraries (MPI, CUDA)
- set JULIA_LOAD_PATH and JULIA_DEPOT_PATH to a default that will separate 'daint-gpu' packages installations from 'daint-mc' packages installations (different CPU architecture...). The package installation destination is: 
`/scratch/snx3000/julia/$USER` on Daint and `/scratch/snx3000tds/julia/$USER` on Dom.
This PR is based on earlier discussions in #2570 .

[daint] Add Julia 1.7.2 pe20.11 without site-wide package installations

---

easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-cuda.psmp
easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU.psmp

I suggest to link MPI-only ELPA with CP2K on the Cray XC systems, since `cray-mpich` does not provide a sufficient level of threading support according to ELPA requirements. See [SD-54759](https://jira.cscs.ch/browse/SD-54759) for more details.

[daint dom] Link MPI-only ELPA with CP2K

---

easybuild/easyconfigs/s/spack-config/spack-config-1.6-cdt-21.09.eb
easybuild/easyconfigs/s/spack-config/spack-config-1.6-cdt-cuda-21.09.eb

- Adds `upstreams.yaml` as part of `module load spack-config` for reuse of binaries
- Makes `pkg-config` the default `pkgconfig` provider, since that's what cray compilers rely on by default
Purposely not changing the default version (requires some real life testing on daint).

[daint,dom] spack-config 1.6

---

jenkins-builds/7.0.UP03-21.09-daint-gpu
jenkins-builds/7.0.UP03-21.09-daint-mc

Install spack-config 1.6, but for the moment keep 1.5 as default one.

[dom, daint] install spack-config 1.6 module

---

easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09.eb
easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-mkl.eb

I provide the recipes of CP2K and SIRIUS (multicore) with the latest ELPA release 2021.11.002.

[daint-mc] CP2K and SIRIUS with latest ELPA

---

easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09-cuda.eb
easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-cuda-mkl.eb

I provide the recipes of CP2K and SIRIUS with the latest ELPA release `2021.11.002`.

[daint-gpu] CP2K and SIRIUS with latest ELPA

---

easybuild/easyconfigs/a/Ascent/Ascent-0.8.0-CrayGNU-21.09.eb
easybuild/easyconfigs/c/Conduit/Conduit-0.8.2-CrayGNU-21.09-python3.eb

== COMPLETED: Installation ended successfully (took 1 min 5 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Ascent/0.8.0-CrayGNU-21.09/easybuild/easybuild-Ascent-0.8.0-20220404.112441.log
== COMPLETED: Installation ended successfully (took 1 min 52 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Conduit/0.8.2-CrayGNU-21.09-python3/easybuild/easybuild-Conduit-0.8.2-20220404.112308.log

[daint,dom] set non-standard PYTHONPATH

---

jenkins-builds/7.0.UP03-21.09-daint-gpu

update Visit to 3.2.2 to support Blueprint HDF5

[daint-gpu dom-gpu] Update 7.0.UP03-21.09-daint-gpu

---

easybuild/easyconfigs/g/GEOS/GEOS-3.9.3-CrayGNU-21.09.eb

Testing: Used it in combination with PROJ/8.1.1-CrayGNU-21.09 to install cartopy

[daint] GEOS-3.9.3-CrayGNU-21.09.eb

---

easybuild/easyconfigs/v/VTK-m/VTK-m-1.8.0-CrayGNU-21.09-cuda.eb

== COMPLETED: Installation ended successfully (took 1 hour 3 mins 49 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VTK-m/1.8.0-CrayGNU-21.09-cuda/easybuild/easybuild-VTK-m-1.8.0-20220816.124921.log

[daint-gpu, dom-gpu] upgrading VTK-m and adding CUDA support

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda.eb
easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner.eb
jenkins-builds/7.0.UP03-21.09-daint-gpu
jenkins-builds/7.0.UP03-21.09-daint-mc

This PR adds functional improvements to JupyterLab:
Adds HDF5 viewer (works on SCRATCH, doesn't work on HOME due to flocking)
Adds git support.
Upgrades JupyterLab version to 3.4.5 (minor improvements)
It will be installed as non-default for beta testing, so should not be considered risky.

[dom,daint] jupyterlab-3.4.5-CrayGNU-21.09-batchspawner.eb

---

easybuild/module/EasyBuild-custom/cscs

I update the system name match in the EasyBuild custom module addressing Eiger and Pilatus and removing outdated matches of dismissed systems: this should fix the error of [ProductionEB](https://jenkins.cscs.ch/view/Production/job/ProductionEB) on Eiger (see my comment in #2790 ).

[eiger pilatus] Fix system name

---

jenkins-builds/1.4.0-21.12-eiger

Update the default module with the new tag 22.10.1 that includes the recent changes of the `sarus` check.

[eiger pilatus] Update reframe-cscs-tests

---

jenkins-builds/1.4.0-21.12-eiger

I am removing the latest VTK with the `ospray` dependency until we fix [VCMSA-108](https://jira.cscs.ch/browse/VCMSA-108).

[eiger pilatus] VTK on hold

---

easybuild/easyconfigs/v/VMD/VMD-1.9.4a57.eb
jenkins-builds/7.0.UP03-21.09-daint-gpu

Fix `versionsuffix`, recipe name and production list removing `-`.

[daint-gpu dom-gpu] Update and rename VMD-1.9.4-a57.eb to VMD-1.9.4a57.eb

---

jenkins-builds/1.4.0-21.12-eiger

Add reframe-cscs-tests/23.01 in production on Eiger and Pilatus ad default.

[eiger pilatus] ReFrame 4.0.1 and reframe-cscs-tests/23.01

---

jenkins-builds/production.sh
jenkins/JenkinsfileUpdateEB

I remove CPMD from the list of licensed software in the production scripts to reflect the new licensing terms pointed out in [SD-57890](https://jira.cscs.ch/browse/SD-57890) and updated in the [CPMD page on the User Portal](https://user.cscs.ch/computing/applications/cpmd/).

[daint dom] Remove CPMD from licensed software

---

easybuild/easyconfigs/s/singularity/singularity-3.5.3-eiger.eb
easybuild/easyconfigs/s/singularity/singularity-3.6.4-eiger.eb

Folder /etc/libibverbs.d no longer present on the system and presence in SINGULARITY_BIND variable causes ReFrame to fail.

[eiger, pilatus] Remove /etc/libibverbs.d bind

---

easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-CrayGNU-21.09.eb
easybuild/easyconfigs/o/ospray/ospray-2.10.0-CrayGNU-21.09.eb
easybuild/easyconfigs/p/ParaView/ParaView-5.11.2-CrayGNU-21.09-OSMesa.eb
jenkins-builds/7.0.UP03-21.09-daint-mc

LLVM now uses the new default CMake
Ospray is updated to v2.10
ParaView has a minor update
== COMPLETED: Installation ended successfully (took 36 mins 36 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.11.2-CrayGNU-21.09-OSMesa/easybuild/easybuild-ParaView-5.11.2-20230928.153027.log

[daint] minor subversion update of ParaView, adding ospray 2.10

---

easybuild/easyconfigs/a/adios/adios-2.9.2-CrayGNU-21.09.eb
easybuild/easyconfigs/c/CDI/CDI-2.3.0-CrayGNU-21.09.eb
easybuild/easyconfigs/e/ecCodes/ecCodes-2.23.0-CrayGNU-21.09.eb
easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-CrayGNU-21.09-EGL.eb
jenkins-builds/7.0.UP03-21.09-daint-gpu

== COMPLETED: Installation ended successfully (took 45 mins 59 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.12.0-CrayGNU-21.09-EGL/easybuild/easybuild-ParaView-5.12.0-20231106.103251.log
== Temporary log file(s) /run/user/1100/easybuild/tmp/eb-93cjb18c/easybuild-qgakgb02.log* have been removed.
== Temporary directory /run/user/1100/easybuild/tmp/eb-93cjb18c has been removed.

[daint-gpu] changed CDI reader dependencies to be compatible with ADIOS to enable ParaView v5.12

---

easybuild/easyconfigs/c/CDI/CDI-2.3.0-CrayGNU-21.09.eb

I have removed the dependencies below as the corresponding modules are already loaded by ecCodes:
```
```

[dom] Fix recipe of CDI on Dom

---

easybuild/easyconfigs/c/CDI/CDI-2.3.0-CrayGNU-21.09.eb
easybuild/easyconfigs/e/ecCodes/ecCodes-2.23.0-CrayGNU-21.09-parallel.eb
jenkins-builds/7.0.UP03-21.09-daint-gpu

Provide the recipe `ecCodes-parallel` to build `CDI` and ParaView 5.12.0 compatible with `ADIOS` on `daint-gpu` as requiested in #2923, fixing the regression test on Piz Daint: see the [failed check](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-daint-production-daily/detail/reframe-daint-production-daily/2674/pipeline) with ParaView.

[daint-gpu dom-gpu] CDI wih ecCodes parallel

---

easybuild/easyconfigs/e/ecCodes/ecCodes-2.23.0-CrayGNU-21.09.eb

Revert to `cray-hdf5` and `cray-netcdf` to avoid the issues reported in [the regression tests](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-daint-production-daily/detail/reframe-daint-production-daily/2674/pipeline) for CDO and ParaView.

[daint dom] Revert ecCodes dependencies

---

jenkins-builds/7.0.UP03-21.09-daint-gpu

The latest recipe does not feature the `-python3` suffix.

[daint-gpu dom-gpu] Fix name of latest VTK recipe in production list

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner.eb

This is using the updated julia module where all issues have been solved according to user feedback.
The jupyterlab recipe itself has been successfully used during the "GPU programming with Julia" course end of November.

 [dom-gpu] update julia version in jupyterlab-3.4.5-CrayGNU-21.09-batchspawner

---

easybuild/easyconfigs/s/singularity/singularity-3.6.4-eiger.eb

Fix Lua footer for singularity module to avoid the following Lmod warning:
```
Lmod Warning:  Syntax error in file: /capstor/apps/cscs/eiger/UES/modulefiles/singularity/3.6.4-eiger.lua
with command: prepend_path, one or more arguments are not strings.
```
The warning is due to the missing definition of `CRAY_LD_LIBRARY_PATH`, since the user environment does not load the Cray PE any longer by default upon login, but the user needs to do that with the `module load cray`.

[eiger pilatus] Update singularity-3.6.4-eiger.eb

---

jenkins-builds/7.0.UP03-21.09-daint-mc

Remove recipe `jupyterlab-3.4.5-CrayGNU-21.09-batchspawner.eb` from the list `7.0.UP03-21.09-daint-mc`, since the build fails on `dom-mc`.

[daint-mc dom-mc] Remove non-default jupyterlab from daint-mc

---

jenkins/JenkinsfileTestingEB

Disable Lmod cache in `TestingEB` to try avoiding [issues](https://sourceforge.net/p/lmod/mailman/message/34706635/) similar to the one experienced in #2964.

[eiger pilatus] Update JenkinsfileTestingEB to disable Lmod cache

---

jenkins/JenkinsfileTestingEB

Set toolchain modules default on systems with Lmod that use the EasyBuild hierarchical module naming scheme in order to avoid the issue experienced in #2964.

[eiger] Update TestingEB

---

easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-cpeGNU-21.12-OSMesa.eb

with an Easybuild Adios module, we are finally able to build the production version of ParaView v5.12 for eiger
== COMPLETED: Installation ended successfully (took 1 hour 14 mins 58 secs)
== Results of the build can be found in the log file(s) /capstor/scratch/cscs/jfavre/eiger/software/ParaView/5.12.0-cpeGNU-21.12-OSMesa/easybuild/easybuild-ParaView-5.12.0-20240312.101717.log

[eiger] ParaView superbuild with system ADIOS

---

easybuild/cpe_external_modules_metadata-23.05.cfg
jenkins-builds/21.12-pilatus
jenkins-builds/production.sh

I provide the configuration files required for CPE 23.05 currently installed on Pilatus, in view of the software stack update. 
Therefore, I need to detach the production list of Pilatus from Eiger, removing some builds that currently are not working (e.g.: `Scalasca`, due to the `PDT` dependency of `Score-P`). 
I also provide an updated `production.sh` to use a more recent EasyBuild release on Eiger and Pilatus.

[daint dom eiger pilatus] Files for CPE 23.05

---

easybuild/easyconfigs/c/cpeGNU/cpeGNU-23.09.eb

I provide the missing recipe for the toolchain `cpeGNU`, release `23.09`.

[pilatus] Add missing cpeGNU-23.09.eb

---

jenkins/JenkinsfileUpdateEB

Add `module use` statement to fix `MODULEPATH` on Rigi.

[rigi] Fix module load hub on Rigi

---

easybuild/easyconfigs/a/adios/adios-2.9.2-CrayGNU-21.09.eb

use the production version of Catalyst, instead of "rc4" version

[daint, dom] Update adios-2.9.2-CrayGNU-21.09.eb

---

easybuild/easyconfigs/c/CP2K/CP2K-9.1-cpeGNU-23.12.eb
easybuild/easyconfigs/c/CP2K/CP2K-9.1-cpeGNU.psmp
easybuild/easyconfigs/e/ELPA/ELPA-2021.11.001-cpeGNU-23.12.eb
easybuild/easyconfigs/g/GMP/GMP-6.2.1-cpeGNU-23.12.eb
easybuild/easyconfigs/l/Libint-CP2K/Libint-CP2K-2.6.0-cpeGNU-23.12.eb
easybuild/easyconfigs/l/libvori/libvori-210412-cpeGNU-23.12.eb
easybuild/easyconfigs/l/libxc/libxc-5.1.7-cpeGNU-23.12.eb
easybuild/easyconfigs/l/libxsmm/libxsmm-1.17-cpeGNU-23.12.eb
easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.3-cpeGNU-23.12.eb
easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-cpeGNU-23.12.eb
easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-cpeGNU-23.12.eb
easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.5-cpeGNU-23.12.eb
easybuild/easyconfigs/s/spglib/spglib-1.16.3-cpeGNU-23.12.eb
jenkins-builds/23.12-pilatus

I provide an updated architecture file for CP2K 9.1 on Pilatus and the recipes of the dependencies (see [SPCI-265](https://jira.cscs.ch/browse/SPCI-265)).

[pilatus] Update CP2K architecture file on Pilatus

---

easybuild/easyconfigs/p/ParaView/ParaView-5.11.2-CrayGNU-21.09-OSMesa.eb
easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-CrayGNU-21.09-OSMesa.eb

Remove version suffix `-rc4` from `Catalyst` dependency of `ParaView` (see #2999): the [regression tests](https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-daint-production-daily/detail/reframe-daint-production-daily/2879/pipeline) are successful (after the manual change of the corresponding modules on the system).

[daint-mc] Remove versionsuffix from Catalyst dependency

---

easybuild/easyconfigs/p/ParaView/ParaView-5.12.1-CrayGNU-21.09-EGL.eb
jenkins-builds/7.0.UP03-21.09-daint-gpu

synching with the HDF5 provided by adios2 dependencies
removing NVIndeX no longer supported
making it the default

[daint-gpu] adding ParaView 5.12.1 as default for EGL-rendering

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.6.7-cpeGNU-23.12.eb

The downgrade is required for compatibility with the `jupyterhub` version installed on the virtual machine.

[pilatus] Downgrade jupyterhub==1.4.2

---

jenkins-builds/23.12-eiger

replaced non functional jupyterlab 3.x with 4.2.3

[eiger pilatus] Update 23.12-eiger

---

easybuild/easyconfigs/v/Visit/Visit-3.4.1-cpeGNU-23.12.eb

this fixes 3 things:
HDF5_HL libs are not getting installed
cray-python module is not loaded for run-time
H5part was missing

[eiger] tweaks to enable h5part, run-time python, and hdf5_HL

---

easybuild/easyconfigs/j/jupyterlab/jupyterlab-4.2.3-cpeGNU-23.12.eb

This pull request fixes Julia paths, appending IJulia paths rather than prepending:
eiger:
pilatus:

 [pilatus eiger] jupyterlab-4.2.3-cpeGNU-23.12 paths fix - lua
