eth-cscs/production

jenkins-builds/6.0.UP02-2016.11-mc
Keeping only the last version of Amber
=> Removing Amber14 from MC list

easybuild/easyconfigs/c/Cube/Cube-4.3.4.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayCCE-2016.11.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayGNU-2016.11.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayIntel-2016.11.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayPGI-2016.11.eb
* https://madra.cscs.ch/scs/doc/issues/13
Rebuilt, looks good.
=> Score-P using system Qt

easybuild/easyconfigs/d/ddt/ddt-6.1.2.eb, jenkins-builds/common-SLES12-2016.10
@jgphpc 
please test /apps/common/UES/sandbox-gpp/modules/all/ddt/6.1.2
=> adding ddt modulefile

easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb, easybuild/module/Easybuild
=> Added ela support

easybuild/easyconfigs/p/PyRegression/PyRegression-dev.eb
instead of the static tarball from master
@vkarak  @victorusu
=> Use PyRegression updated daily by jenkins

easybuild/easyconfigs/c/CDO/CDO-1.7.2-gmvolf-15.11.eb
@vkarak can you please confirm that it works on kesch?
=> version bump for CDO

jenkins-builds/common-SLES12-2016.10
@vkarak @victorusu let me know when this is ready to be deployed on daint.
=> adding PyRegression 2.0 to production

jenkins-builds/production_builds.sh
to enable concurrent builds of the gpu/mc software stacks
@lucamar @victorusu I'm merging now, PR is FYI
=> adding $ARCH to build prefix

jenkins-builds/production_builds.sh
=> remove xalt from production builds

easybuild/easyconfigs/s/Szip/Szip-2.1.eb
please merge so i can tell Doris to use EB.
=> szip for ticket 25733

easybuild/easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-PLUMED-2.2.3-cuda-8.0.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-PLUMED-2.2.3.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.2.3-CrayGNU-2016.11.eb
The branch includes new configuration files to build LAMMPS with PLUMED, multicore and cuda version. I have also updated the standard LAMMPS configuration files, multicore and cuda version, to include some more packages.
=> LAMMPS with PLUMED

easybuild/easyconfigs/s/Scalasca/Scalasca-2.3.1-CrayGNU-2016.06.eb, easybuild/easyconfigs/s/Scalasca/Scalasca-2.3.1-CrayGNU-2016.11.eb, easybuild/easyconfigs/s/Scalasca/Scalasca-2.3.1-CrayIntel-2016.11.eb, easybuild/easyconfigs/s/Scalasca/Scalasca-2.3.1-CrayPGI-2016.11.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayCCE-2016.11.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayGNU-2016.11.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayIntel-2016.11.eb, easybuild/easyconfigs/s/Score-P/Score-P-3.0-CrayPGI-2016.11.eb, easybuild/easyconfigs/v/vampir/vampir-9.2.0.eb, jenkins-builds/common-SLES12-2016.10
/apps/daint/UES/6.0.UP02/sandbox-haswell/easybuild/software/vampir/9.2.0/easybuild/*log
```
piccinal@daint101:~$ module use \
/apps/daint/UES/6.0.UP02/sandbox-haswell/easybuild/modules/all 
piccinal@daint101:~$ module load vampir/9.2.0
piccinal@daint101:~$ which vampir
/apps/common/UES/vampir/9.2.0/bin/vampir
```
=> adding vampir/9.2

easybuild/easyconfigs/g/GLib/GLib-2.49.5.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8.eb, easybuild/easyconfigs/l/libffi/libffi-3.2.1.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.4.eb, easybuild/easyconfigs/m/mc/mc-4.8.18.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.38.eb, easybuild/easyconfigs/p/pkg-config/pkg-config-0.29.1.eb, easybuild/easyconfigs/s/S-Lang/S-Lang-2.3.1a.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.2.eb, jenkins-builds/common-SLES12-2016.10
Ready to merge
* https://jenkins.cscs.ch/view/ProductionEB/job/ProductionEBtestingPR-sles12/label=daint101/6/console
=> midnight commander/sles12

easybuild/easyconfigs/p/perftools-base-cscs/perftools-base-cscs-643cuda.eb, easybuild/easyconfigs/p/perftools-base-cscs/perftools-base-cscs-643nogpu.eb, easybuild/easyconfigs/p/perftools-base-cscs/perftools-base-cscs-643openacc.eb, easybuild/easyconfigs/p/perftools-cscs/perftools-cscs-643cuda.eb, easybuild/easyconfigs/p/perftools-cscs/perftools-cscs-643nogpu.eb, easybuild/easyconfigs/p/perftools-cscs/perftools-cscs-643openacc.eb, jenkins-builds/6.0.UP02-2016.11-gpu, jenkins-builds/6.0.UP02-2016.11-mc
[For technical reviews](https://madra.cscs.ch/scs/doc/issues?scope=all&state=opened&utf8=%E2%9C%93&label_name%5B%5D=techrevs)
=> cray perftools/643 (technical reviews)

easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-2016.11-cuda-8.0.54.eb
attempting to actually pin cudatoolkit version (current cuda-enabled modules rely on system defaults)
Please review @ajocksch @jgphpc @lucamar. Do you foresee any potential side effect?
=> Magma using CRAY_LD_LIBRARY_PATH

easybuild/easyconfigs/p/PLUMED/PLUMED-2.3.0-CrayGNU-2016.11.eb
New stable release of PLUMED 2.3.0 available for patching scientific applications
=> Adding PLUMED 2.3.0

easybuild/easyconfigs/c/CP2K/CP2K-4.1-CrayGNU-2016.11-cuda-8.0.54.eb
Inserting modextravars in CP2K-4.1 cuda-8.0.54 configuration file
=> Update CP2K gpu with modextravars

easybuild/easyconfigs/g/GPAW/GPAW-1.2.0-CrayGNU-2016.11-Python-2.7.12.eb, easybuild/easyconfigs/g/GPAW/gpaw-1.2.0-cray.patch
=> Adding GPAW-1.2.0 easyconfig and patch files with updated dependency list

easybuild/easyconfigs/c/CP2K/CP2K-4.1-CrayGNU-2016.11-PLUMED-2.2.3-cuda-8.0.54.eb
I had to shorten the BUILDPATH to build successfully:
`export EASYBUILD_BUILDPATH=/dev/shm/lucamar`
=> Easyconfig file for CP2K with PLUMED plumgin

easybuild/easyconfigs/p/Python-bare/Python-bare-3.5.2.eb
Plus some cleaning...
Also see: https://github.com/hpcugent/easybuild-easyblocks/issues/1063
=> fixed problem due to renaming Python to Python-bare

easybuild/easyconfigs/g/GSL/GSL-2.3-CrayGNU-2016.11.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.3.0-CrayGNU-2016.11.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.11-CrayGNU-2016.11.eb
Plumed 2.30.0 configuration file linking libmatheval with updated dependency list.
=> Plumed matheval

data_science/README.md, data_science/SIDEBAR.md, data_science/index.html, data_science/tensorflow/README.md, data_science/tensorflow/index.html, data_science/theano/README.md, data_science/theano/index.html, html/navbar-without-presentation.html, html/navbar.html
@mschoengens @victorusu I've created the pull request, but I don't really understand what is the problem, both branches are unprotected.
=> Gh pages datascience

easybuild/cray_external_modules_metadata.cfg, easybuild/easyconfigs/m/moose/moose-b675783-CrayGNU-2016.11.eb
Build took 6h but it seems to work.
cc @vectorflux
=> first attempt of building moose and libmesh

easybuild/easyconfigs/m/moose/moose-b675783-CrayGNU-2016.11.eb
User reported that current build is looking for includes on /dev/shm...
This is a desperate attempt to fix that.
=> Compiling moose on build dir

easybuild/easyconfigs/p/ParaView/ParaView-5.3.0-EGL-CrayGNU-2016.11.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.3.0-calculator-patch
ParaView with EGL. Succesfully tested on Dom. It prevents the crashing of Render windows when closing/reopening a root 3D window.
=> Paraview with EGL

easybuild/easyconfigs/v/VMD/VMD-1.9.3-egl.eb
Actually install package with EB instead of only creating the module file.
=> unpacking VMD with EB

easybuild/easyconfigs/c/CP2K/CP2K-4.1-CrayGNU-2016.11-cuda-8.0.54-pat-645-cuda.eb
CUDA only as the performance report should be run with daint-gpu on the Cray XC50
=> Adding CP2K with perftools-cscs/645-cuda

easybuild/easyconfigs/g/gnuplot/gnuplot-5.0.6.eb
* ela> gnuplot    :new: 
`	Version 5.0 patchlevel 6    last modified 2017-03-18`
* ela> /usr/bin/gnuplot 
`	Version 5.0 patchlevel 3    last modified 2016-02-21 `
Recipe not used in any jenkins script hence it will not impact any user.
=> gnuplot new version 5.0.6

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-5.4.0-CrayIntel-2016.11-pat-645-nogpu.eb
Quantum ESPRESSO configuration file with perftools-cscs updated `builddependencies`
=> Espresso pat

jenkins-builds/6.0.UP02-2016.11-mc
Forgot to add it to the daint-mc as well
=> Adding NCL 6.4.0 to mc

easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-2016.10-intel17.eb, easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-2016.10-intel17_craypat.eb, easybuild/easyconfigs/c/CPMD/CRAY-XE6-INTEL-MKL
linked with mkl; also craypat included in the 2nd recipe
=> cpmd with mkl

easybuild/easyconfigs/s/Spark/Spark-1.6.0.eb
=> adds Maxime's spark module

easybuild/easyconfigs/m/MaTEx/MaTEx-ce0cab8-CrayGNU-2016.11.eb, easybuild/easyconfigs/p/parallel-netcdf/parallel-netcdf-1.8.1-CrayGNU-2016.11-shared.eb, easybuild/easyconfigs/p/parallel-netcdf/parallel-netcdf-1.8.1.patch
Thanks to @mmxcscs.
I'll test before merging
=> WIP: adding MaTEx (TensorFlow MPI)

easybuild/easyconfigs/c/Caffe/Caffe-1.0-CrayGNU-2016.11-cuda-8.0-Python-2.7.12.eb, easybuild/easyconfigs/g/gflags/gflags-2.1.2-CrayGNU-2016.11.eb, easybuild/easyconfigs/g/glog/glog-0.3.4-CrayGNU-2016.11.eb, easybuild/easyconfigs/l/LMDB/LMDB-0.9.18-CrayGNU-2016.11.eb, easybuild/easyconfigs/l/LevelDB/LevelDB-1.18-CrayGNU-2016.11.eb, easybuild/easyconfigs/n/networkx/networkx-1.11-CrayGNU-2016.11-Python-2.7.12.eb, easybuild/easyconfigs/o/OpenCV/OpenCV-3.2.0-CrayGNU-2016.11-Python-2.7.12.eb, easybuild/easyconfigs/p/Pillow/Pillow-3.2.0-CrayGNU-2016.11-Python-2.7.12-freetype-2.6.3.eb, easybuild/easyconfigs/p/protobuf-python/protobuf-python-3.1.0-CrayGNU-2016.11-Python-2.7.12.eb, easybuild/easyconfigs/s/scikit-image/scikit-image-0.13.0-CrayGNU-2016.11-Python-2.7.12.eb, easybuild/easyconfigs/s/snappy/snappy-1.1.3-CrayGNU-2016.11.eb
Sanity check command fails during build, but it works after installing (that's odd).
=> adding Caffe 1.0 and dependencies

easybuild/easyconfigs/c/Caffe2/Caffe2-0.7.0-CrayGNU-2016.11-cuda-8.0-Python-2.7.12.eb
=> Caffe2 8ce4e2e

easybuild/easyconfigs/p/perftools-base-cscs/perftools-base-cscs-645-loops.eb, easybuild/easyconfigs/p/perftools-cscs/perftools-cscs-645-loops.eb, jenkins-builds/6.0.UP02-2016.11-gpu, jenkins-builds/6.0.UP02-2016.11-mc
=> adding ptl645-loops

easybuild/easyconfigs/c/CMake/CMake-3.8.1.eb, jenkins-builds/common-SLES12-2016.10
... and changing list common-SLES12 accordingly
=> Adding recipe for CMake-3.8.1

easybuild/easyconfigs/l/libxc/libxc-3.0.0-CrayIntel-2016.11.eb
Exchange-correlation library required by some quantum mechanics codes
=> Adding libxc recipe with CrayIntel

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-4.1-foss-2016b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-4.1-mpfr.patch
@ajocksch can you please test this?
```
module use /apps/leone/UES/RHEL6.7EUS/sandbox/modules/all
```
=> OpenFOAM 4.1 for leone

easybuild/easyconfigs/r/reframe/reframe-2.3.eb, jenkins-builds/common-RH6.7-2016.10, jenkins-builds/common-SLES12-2016.10
This should not be made the default version, since it has broken some of our regression tests.
=> Reframe 2.3

easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb, easybuild/module/Easybuild
The variables is now defined as follows:
```
set eb_config_dir          /apps/daint/UES/jenkins/production/easybuild
```
=> Updating set eb_config_dir in recipe

easybuild/easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11-cuda-8.0.54.eb
Adding support for package `user-cgsdk` following CSCS request #27958 (Lammps )
=> [daint-gpu] Updating LAMMPS recipe

easybuild/easyconfigs/l/LAMMPS/LAMMPS-30Jul16-CrayGNU-2016.11.eb
Adding support for package user-cgsdk following CSCS request #27958 (Lammps)
=> [daint-mc] Updating LAMMPS multicore

easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb, easybuild/module/Easybuild
Using the variable `CRAYPE_NETWORK_TARGET` to define `EASYBUILD_PREFIX`
=> Updating EasyBuild-custom-cscs

easybuild/easyconfigs/h/HDF5/HDF5-1.8.18-gmvolf-17.06-serial.eb, easybuild/easyconfigs/h/HDF5/HDF5-1.8.18-gmvolf-17.06.eb, easybuild/easyconfigs/p/Python/Python-2.7.12-gmvolf-17.06.eb, easybuild/easyconfigs/p/Python/Python-3.5.3-gmvolf-17.06.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.5-gmvolf-17.06.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.5-gmvolf-17.06.eb
=> [monch] sync dep versions for zlib, ncurses, libreadline

easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb, easybuild/module/Easybuild
We now have a dedicated jenkins project to keep a (site-wide) updated version of this github production repository (instead of relying on the version maintained for Piz Daint).
=> Use EB from common instead of daint

easybuild/easyconfigs/m/moose/moose-d2193ae-CrayGNU-2016.11.eb
The installation log can be found at:
/apps/daint/UES/6.0.UP02/sandbox-vh/easybuild/software/moose/d2193ae-CrayGNU-2016.11/easybuild/easybuild-moose-d2193ae-20170622.012818.log
=> Newer moose version

jenkins-builds/6.0.UP02-2016.11-gpu, jenkins-builds/production.sh
Minor fix to remove trailing newline from production files
=> FIx for production script

jenkins-builds/production.sh
I have inserted the system Dom. Do we need to update xalt table of modulefiles on Dom as well?
=> Adding Dom to production script

easybuild/easyconfigs/o/OpenFOAM-Extend/OpenFOAM-Extend-4.0-foss-2016b.eb, easybuild/easyconfigs/p/ParMETIS/ParMETIS-4.0.3-foss-2016b.eb
(not all plugins are being built)
=> [leone] First attempt of foam-extend 4.0

easybuild/easyconfigs/n/nose-parameterized/nose-parameterized-0.5.0-CrayGNU-2016.11-Python-2.7.12.eb, easybuild/easyconfigs/t/Theano/Theano-0.9.0-CrayGNU-2016.11-Python-2.7.12.eb, easybuild/easyconfigs/t/Theano/Theano-0.9.0-CrayGNU-2016.11-Python-3.5.2.eb, jenkins-builds/6.0.UP02-2016.11-gpu
Daint-gpu version of Then 0.9.0
These versions are all GPU based.
=> [daint-gpu] Theano

easybuild/easyconfigs/v/Valgrind/Valgrind-3.13.0-gmvapich2-15.11_cuda_7.0_gdr.eb
@mmxcscs please let us know if that works
=> [kesch] valgrind mvapich gdr cuda 7.0

jenkins-builds/production.sh
Add the option to turn off XALT database generation
=> Adding no-xalt flag

easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.1.0-CrayGNU-2016.11-cuda-8.0-Python-3.5.2.eb, easybuild/easyconfigs/t/TensorFlow/tensorflow-v1.1.0-cuda-Python-3.5.2-cscs.patch
Needs to be tested, patch for disabling JEMALLOC (from TF 1.0) was removed.
=> [daint-gpu] adding TF1.1

jenkins-builds/6.0.UP02-2016.11-gpu
Removing VTK from `daint-gpu` production list.
=> [daint-gpu] Remove vtk

easybuild/easyconfigs/b/Boost/Boost-1.61.0-foss-2016b-Python-2.7.12.eb, easybuild/easyconfigs/e/ESyS/ESyS-2.3.5-foss-2016b-Python-2.7.12.eb
https://webrt.cscs.ch/Ticket/Display.html?id=28458
=> [leone] .eb for ticket 28458

easybuild/easyconfigs/a/abcpy/abcpy-0.3.0-CrayGNU-2016.11-Python-3.5.2.eb, easybuild/easyconfigs/c/cloudpickle/cloudpickle-0.3.1-CrayGNU-2016.11-Python-3.5.2.eb, easybuild/easyconfigs/g/glmnet/glmnet-2.0.0-CrayGNU-2016.11-Python-3.5.2.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.18.2-CrayGNU-2016.11-Python-3.5.2.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.18.2.patch
Added ABCpy including dependencies.
=> [daint] Abcpy

jenkins-builds/production.sh, login/daint.footer
I'm inserting the `--modules-footer` to update the library path on Cray systems.
Meanwhile, I'm also changing the way we force a build to address a bug.
=> [daint dom] Update production with footer

easybuild/easyconfigs/e/ESyS/ESyS-2.3.5-foss-2016b-Python-2.7.12.eb
- Updated `$PYTHONPATH` as requested by the user
- Adding Python as explicit dependency and using `pyver/pyshortver` variables
=> [leone] Updating ESyS

jenkins-builds/MCH-RH7.3-17.02
New Python modulefile on KeschTDS
=> [kesch] Adding Python 3.6.1 to production builds for KeschTDS

login/daint.footer
Fix footer for modules built on Cray systems
=> [daint dom] Fixing footer for Cray systems

jenkins-builds/production.sh
Fixing NAMD build after a `module purge` with `module load ugni`.
=> [daint-gpu] Fixing NAMD 

easybuild/easyconfigs/e/EasyBuild-custom/EasyBuild-custom-cscs.eb, easybuild/module/Easybuild
It will be useful for Jenkins projects where a different `EASYBUILD_SOURCEPATH` might be needed.
=> [daint dom kesch leone monch] Proposal to define sourcepath

easybuild/easyconfigs/g/grib_api/grib_api-1.21.0-gmvolf-17.02.eb, easybuild/easyconfigs/p/Python/Python-3.6.2-gmvolf-17.02.eb
To be in line with other software stacks (e. g. dom), which are currently being updated.
=> [kesch] Python 3.6.2 for MCH

easybuild/easyblocks/gromacs.py, easybuild/easyconfigs/g/GROMACS/GROMACS-2016.3-CrayGNU-2016.11-PLUMED-2.3.0-cuda-8.0.54.eb
Gromacs 2016.3 easyconfig file with PLUMED patch: `gromacs.py` is necessary until we get the development easyblock in production and to patch a software version not officially recognized.
=> Gromacs easyblock and recipe with PLUMED

easybuild/easyconfigs/v/VMD/VMD-1.9.3-egl.eb, easybuild/easyconfigs/v/VMD/VMD-1.9.3-ogl.eb, easybuild/easyconfigs/v/Visit/Visit-2.12.0-CrayGNU-2016.11.eb
The path `/apps/common/UES/easybuild/sources` is the source of tar files for manual installation.
=> [daint-gpu] Absolute path in easyconfig files for VisIt  and VMD

easybuild/easyconfigs/c/CMake/CMake-3.6.0-CrayGNU-2017.02-gcc-4.9.3.eb, easybuild/easyconfigs/c/CrayGNU/CrayGNU-2017.02-gcc-4.9.3.eb, easybuild/easyconfigs/d/DCA++/DCA++-1.0-CrayGNU-2017.02-gcc-4.9.3-cuda-7.5.18.eb, easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-2017.02-gcc-4.9.3-cuda-7.5.18.eb, easybuild/easyconfigs/m/magma/magma-2.2.0.patch, easybuild/easyconfigs/n/ncurses/ncurses-6.0-CrayGNU-2017.02-gcc-4.9.3.eb
Easyconfig files for DCA++/1.0-CrayGNU-2017.02-gcc-4.9.3-cuda-7.5.18 and all its dependencies including the toolchain CrayGNU-2017.02-gcc-4.9.3.
=> [daint] DCA++/1.0-CrayGNU-2017.02-gcc-4.9.3-cuda-7.5.18

easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-cray-python-17.06.1-cray-hdf5-1.10.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-cray-python-17.06.1-cray-hdf5-parallel-1.10.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
=> [dom] pe1708_h5py

easybuild/easyconfigs/i/IPython/IPython-6.1.0-CrayGNU-2016.11-Python-3.5.2.eb, easybuild/easyconfigs/l/libsodium/libsodium-1.0.13-CrayGNU-2016.11.eb, easybuild/easyconfigs/o/OpenPGM/OpenPGM-5.2.122-CrayGNU-2016.11.eb, easybuild/easyconfigs/p/PyZMQ/PyZMQ-17.0.0b1-CrayGNU-2016.11-Python-3.5.2-zmq4.eb, easybuild/easyconfigs/u/util-linux/util-linux-2.27.1-CrayGNU-2016.11.eb, easybuild/easyconfigs/z/ZeroMQ/ZeroMQ-4.2.2-CrayGNU-2016.11.eb
libsodium is used inside the IPython package
=> [daint-gpu] IPython-6.1.0 in CrayGNU2016.11 for Python-3.5.2

easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-CrayGNU-17.08.eb, easybuild/easyconfigs/a/Automake/Automake-1.15-CrayGNU-17.08.eb, easybuild/easyconfigs/a/Autotools/Autotools-20150215-CrayGNU-17.08.eb, easybuild/easyconfigs/g/gettext/gettext-0.19.8-CrayGNU-17.08.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-CrayGNU-17.08.eb, easybuild/easyconfigs/m/M4/M4-1.4.18-CrayGNU-17.08.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-CrayGNU-17.08.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.3-CrayGNU-17.08.eb, easybuild/easyconfigs/x/XZ/XZ-5.2.3-CrayGNU-2016.11.eb
XZ with dependencies: `libxml2` might be an issue as in some cases it has `XZ` as a depedency in its turn.
=> [dom] XZ and dependencies

easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-17.08-cuda-8.0.eb, jenkins-builds/6.0.UP04-17.08-gpu
=> [dom-gpu] magma for maintenance run

jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
=> [dom] adding spark to jenkins list

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-cuda-8.0.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-cuda-8.0.makefile.include, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08.makefile.include, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
VASP EasyBuild configuration files with include files and updated production lists
=> [dom-gpu] VASP recipes, include files and production lists updated

easybuild/easyconfigs/f/freetype/freetype-2.8-CrayGNU-17.08.eb, easybuild/easyconfigs/g/GMP/GMP-6.1.2-CrayGNU-17.08.eb, easybuild/easyconfigs/l/libreadline/libreadline-7.0-CrayGNU-17.08.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.20.0-CrayGNU-17.08.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.7-CrayGNU-17.08.eb, easybuild/easyconfigs/t/Tk/Tk-8.6.7-CrayGNU-17.08.eb
The recipes included in this pull request are the dependencies of Python modules built on Cray systems using EasyBuild: at present they are not listed as dependencies in `PyExtension`, but we still need to verify that they are not needed with `cray-python`: they might also be useful for other Python builds.
=> [dom] Python dependencies

jenkins-builds/MCH-RH7.3-17.02.dev
I need a temporary build list on Kesch to address some path issues.
=> [kesch] mch dev list

jenkins-builds/MCH-RH7.3-17.02
New release for CMake and Python
=> [kesch] mch production list

easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python2-parallel.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python2-serial.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python3-parallel.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.0-CrayGNU-17.08-python3-serial.eb
=> [dom] h5py + cray-python

jenkins-builds/MCH-RH7.3-17.02
=> [kesch] understand for kesch

easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-parallel-pat-6.5.1.eb
This should be installed using on a compute node.
=> [dom] Adding Amber parallel with craypat

easybuild/easyconfigs/p/ParaView/ParaView-5.4.1-EGL-CrayGNU-17.08.eb
=> [dom-gpu] ParaView-5.4.1-EGL + Python3

easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-CrayCCE-17.06.eb
=> [kesch] Update of CMake version

login/daint-gpu, login/daint-mc
Temporarily use dom for the software stack
=> [dom] Update login

easybuild/easyconfigs/g/GSL/GSL-2.4-CrayCCE-17.08.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
Could you please have a look to this easyconfig? Thanks!
=> [dom, daint] Easyconfig for GSL 2.4 CrayCCE 17.08 created

easybuild/easyconfigs/r/Ruby/Ruby-2.4.0-gmvolf-17.02.eb
https://webrt.cscs.ch/Ticket/Display.html?id=29008
=> [kesch] ruby + deps

jenkins-builds/production.sh
=> [daint dom kesc leone monch] Fix forcelist

easybuild/easyblocks/netcdf_python.py, easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.2.9-CrayGNU-17.08-python2.eb, easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.2.9-CrayGNU-17.08-python3.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
This fixes netcdf-python easyblock and updates netcdf-python to use the last toolchain and modules.
=> [daint-gpu,daint-mc] NetCDF 4 python

jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
As discussed at the last SCS meeting, I'm inserting PLUMED GNU in both production lists.
=> [daint] PLUMED GNU in production lists

easybuild/easyconfigs/n/netCDF/netCDF-4.4.1.1-gmvolf-17.02.eb
Could you please have a look? Thanks!
=> [kesch] Static library build added for netCDF-4.4.1.1

easybuild/easyconfigs/l/libxml2/libxml2-2.9.4-gmvolf-17.02.eb, easybuild/easyconfigs/r/R/R-3.3.2-gmvolf-17.02-libX11-1.6.3.eb
- removed cyclic XZ dependency
- updated GDAL version
=> [kesch] fixing r for gmvolf 17.02

easybuild/easyconfigs/f/freetype/freetype-2.8.1-CrayGNU-17.08.eb
Last stable release of `freetype`is `2.8.1`.
=> [daint,dom] Updating freetype to last release

easybuild/easyconfigs/f/freetype/freetype-2.8.1-gmvolf-17.02.eb, easybuild/easyconfigs/f/freetype/freetype-2.8.1.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.32-gmvolf-17.02.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.32.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-gmvolf-17.02.eb, easybuild/easyconfigs/m/M4/M4-1.4.18-gmvolf-17.02.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.11-gmvolf-17.02.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.11.eb
Last release of `freetype`is `2.8.1`
=> [kesch] Updating freetype to 2.8.1

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-17.08-pat-6.5.1.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.1.0-CrayIntel-17.08.eb
Adding `EPW` to `QuantumESPRESSO`
=> [daint,dom] Espresso epw

jenkins/JenkinsfileRegressionEB, jenkins/Machines.groovy, jenkins/util.groovy
* Create a groovy file `Machines.groovy` containing
the configurations of the machines available at CSCS.
* Create a groovy file `util.groovy` where various
utility methods used in jenkins pipelines are defined.
* Create the jenkins pipeline file `JenkinsfileRegressionEB`
which is used periodically to run a regression suite for
Easybuild.
=> Add a new directory `jenkins` for Jenkinsfiles

easybuild/easyconfigs/i/ImageMagick/ImageMagick-6.7.6-10-GCC-5.4.0-2.26-sysdeps.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-6.7.6-10.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-7-GCC-5.4.0-2.26-sysdeps.eb, easybuild/easyconfigs/i/ImageMagick/ImageMagick-7.0.7-7.eb, jenkins-builds/MCH-RH7.3-17.02
=> [kesch] Update MCH-RH7.3-17.02

jenkins-builds/MCH-RH7.3-17.02
@jgphpc  It is not clear to me: why the old recipe does not exist anymore?
=> [kesch] Understand version bump 

easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7-CrayGNU-17.08.eb
=> [daint] Add virtualenv to PyExtensions for Python2

easybuild/easyconfigs/p/Paraver/Paraver-4.6.4.rc1.eb
small change to the modulefile
=> [dom] cfgdir

easybuild/easyconfigs/t/TensorFlow/tensorflow-v1.3.0-cuda-python3-cscs.patch
Reverts eth-cscs/production#466
=> Revert "[dom, daint] Sha265sum of protobuf dependency changed."

easybuild/easyconfigs/p/Python/Python-2.7.12-foss-2016b.eb
Fixed link and updated version of Python package `scipy`
=> [leone] Python for Leone

jenkins/JenkinsfileRegressionEB, jenkins/util.groovy
* Add a method to send a message to Slack when finishing the jenkins
pipeline build.
* Color the message according to build result.
=> [daint dom kesch leone monch] Add Slack notification after build

easybuild/easyconfigs/r/reframe/reframe-2.7.eb, jenkins-builds/common-RH6.7-2016.10, jenkins-builds/common-SLES12-2016.10, jenkins-builds/monch-RH6.9-17.06
Also updated `sources` syntax.
=> [dom daint] Add ReFrame 2.7 easyconfig

jenkins/JenkinsfileTestingEB, jenkins/Machines.groovy
* Create a scratchCommand in each machine dictionary.
* Use the scratchCommand to find the actual scratch directory.
=> [dom kesch leone monch] Fix the scratch dirs in machines

jenkins/JenkinsfileTestingEB, jenkins/Machines.groovy
* Remove the particular `scratchCommand` key from each machine
dictionary.
* Fix typo in bash login.
=> [leone monch dom kesch] Remove scratch command from machines and fix bash login

easybuild/easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08-cuda-8.0.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08.eb
Adding the user-misc package to LAMMPS
=> [dom] Adding user-misc to LAMMPS

easybuild/easyconfigs/l/LAMMPS/LAMMPS-11Aug2017-CrayGNU-17.08-cuda-8.0.eb
As requested by an user.
I am extending the list of programs supplied by LAMMPS-cuda.
=> [daint-gpu] Extend the list of default packages LAMMPS

easybuild/easyconfigs/g/GSL/GSL-1.16-gmvolf-17.02.eb, easybuild/easyconfigs/r/Ruby/Ruby-2.2.2-gmvolf-17.02.eb, easybuild/easyconfigs/r/Ruby/Ruby-2.4.0-gmvolf-17.02.eb, jenkins-builds/MCH-RH7.3-17.02
Reverting back to Ruby 2.2.2 and GSL 1.16 due to problems reported by André Walser in ticket 29859.
=> [kesch] tds/ruby gem gsl

easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08-cuda-8.0.eb, easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08-cuda-8.0.psmp, easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08.eb, easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08.psmp
New EasyBuild recipes for CP2K last stable release 5.1
=> [daint, dom] CP2K 5.1

easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-cuda-8.0.eb
This fixes the Amber patch download failures for our regression
=> [daint-gpu] Avoid patch download Amber

easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-parallel.eb, easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-serial.eb
This fixes the Amber patch download failures for our regression.
=> [daint-mc] Avoid patch download Amber

easybuild/easyconfigs/l/LIGGGHTS/LIGGGHTS-3.8.eb, jenkins-builds/leone-RHEL6.7EUS-17.06
Based on https://webrt.cscs.ch/Ticket/Display.html?id=30237
Module file has been tested. (see ticket)
=> [leone] LIGGGHTS (used by Hilti)

easybuild/easyconfigs/v/VTK/VTK-8.1.0-CrayGNU-17.08-python2.eb, easybuild/easyconfigs/v/VTK/VTK-8.1.0-CrayGNU-17.08-python3.eb, easybuild/easyconfigs/v/VTK/VTK-8.1.0-EGL-CrayGNU-17.08-python2.eb, easybuild/easyconfigs/v/VTK/VTK-8.1.0-EGL-CrayGNU-17.08-python3.eb, jenkins-builds/6.0.UP04-17.08-gpu
No changes to the optional settings were made. I simply bumped up the version from 8.0.1. to 8.1
=> [daint-gpu] new version of VTK with OpenGL and EGL support

easybuild/easyconfigs/c/CDO/CDO-1.9.0-CrayGNU-17.08.eb, easybuild/easyconfigs/c/CDO/CDO-1.9.0-CrayIntel-17.08.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
Also removal of outdated comments in the CDO-CrayIntel.
=> [daint] Update of CDO-CrayGNU recipe

easybuild/easyconfigs/c/Circos/Circos-0.69-6.eb, easybuild/easyconfigs/g/GD/GD-2.66-Perl-5.26.1-bare.eb, easybuild/easyconfigs/g/GD/GD-2.66.patch, easybuild/easyconfigs/l/libgd/libgd-2.2.5.eb, easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-1.5.3.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.34.eb, easybuild/easyconfigs/o/OTF2/OTF2-2.1-CrayGNU-17.08-python3-bindings.eb, easybuild/easyconfigs/o/otfprofile/otfprofile-1.20.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.1-bare.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
=> [daint-gpu] otf2

easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08-cuda-8.0.eb, easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08.eb
Updating recipes based on request #30739 and following private communications with CP2K users.
=> [daint, dom] Updating CP2K recipes

easybuild/easyconfigs/b/byacc/byacc-20170709-CrayIntel-17.08.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-CrayIntel-17.08.eb, easybuild/easyconfigs/g/GMP/GMP-6.1.2-CrayIntel-17.08.eb, easybuild/easyconfigs/g/gc/gc-7.6.0-CrayIntel-17.08.eb, easybuild/easyconfigs/g/guile/guile-2.0.13-CrayIntel-17.08.eb, easybuild/easyconfigs/g/guile/guile-2.0.14-CrayGNU-17.08.eb, easybuild/easyconfigs/g/guile/guile-2.0.14-CrayIntel-17.08.eb, easybuild/easyconfigs/l/libffi/libffi-3.2.1-CrayIntel-17.08.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-CrayGNU-17.08.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-CrayIntel-17.08.eb, easybuild/easyconfigs/l/libreadline/libreadline-7.0-CrayIntel-17.08.eb, easybuild/easyconfigs/l/libtool/libtool-2.4.6-CrayIntel-17.08.eb, easybuild/easyconfigs/l/libunistring/libunistring-0.9.7-CrayIntel-17.08.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.0-CrayIntel-17.08.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-CrayGNU-17.08.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.0-CrayIntel-17.08.eb
New recipe to build `PLUMED-2.4.0` with the `CrayIntel` toolchain, including dependencies.
=> [daint] Plumed240 crayintel1708

jenkins-builds/6.0.UP04-17.08-gpu
The pull request is addressing CSCS request #30844
=> [daint-gpu] Adding GROMACS 2018

easybuild/easyconfigs/r/reframe/reframe-2.11-cscs-settings.patch, easybuild/easyconfigs/r/reframe/reframe-2.11.eb, jenkins-builds/MCH-RH7.3-17.02, jenkins-builds/common-SLES12-2016.10, jenkins-builds/leone-RHEL6.7EUS-17.06, jenkins-builds/monch-RH6.9-17.06
- Does not fetch the private `reframe-tests` repo. This needs to be discussed and resolved.
=> [daint dom monch leone kesch] ReFrame 2.11 easyconfig

easybuild/easyconfigs/d/ddt/ddt-18.1.1.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc, jenkins-builds/MCH-RH7.3-17.02, jenkins-builds/leone-RHEL6.7EUS-17.06, jenkins-builds/monch-RH6.9-17.06
https://developer.arm.com/products/software-development-tools/hpc/arm-forge/release-history
=> [daint leone monch kesch] ddt/1811

easybuild/easyconfigs/r/reframe/reframe-2.11-cscs-settings.patch, easybuild/easyconfigs/r/reframe/reframe-2.11.eb
Fixes https://github.com/eth-cscs/reframe/issues/190
=> [daint dom kesch leone monch] Install private tests also with ReFrame easyconfig

easybuild/easyconfigs/r/rstudio/rstudio-1.1.442.eb
=> [kesch] rstudio/1.1.442

easybuild/easyconfigs/o/ospray/ospray-1.5.0-CrayGNU-17.08.eb
when ParaView 5.5 is release, it should be compiled it with the newer OSPRay
=> [daint] newer OSPRay for the upcoming ParaView v5.5

jenkins-builds/MCH-RH7.3-17.02
https://webrt.cscs.ch/Ticket/Display.html?id=31082
Already tested with https://github.com/eth-cscs/production/pull/564
=> [kesch] rstudio for rt31082

easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-cuda-8.0.eb, easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-parallel.eb, easybuild/easyconfigs/a/Amber/Amber-16-CrayGNU-17.08-serial.eb
Fixing failure that appeared here:
https://jenkins.cscs.ch/blue/rest/organizations/jenkins/pipelines/RegressionEB/runs/763/nodes/41/steps/71/log/?start=0
=> [daint, dom] Fix of Amber-16 recipes

easybuild/easyconfigs/g/GROMACS/GROMACS-2018-CrayGNU-17.08.eb, jenkins-builds/6.0.UP04-17.08-mc
Release `2018` for the software stack `daint-mc`
=> [daint-mc, dom-mc] GROMACS-2018

easybuild/easyconfigs/p/ParaView/ParaView-5.5.0-EGL-CrayGNU-17.08.eb, jenkins-builds/6.0.UP04-17.08-gpu
Version 5.5 includes the NVIDIA IndeX plugin
=> [daint-gpu] new Paraview 5.5. Set default to 5.5

easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.2.9-CrayGNU-17.08-python2.eb
=> [daint] Update netcdf-python-1.2.9-CrayGNU-17.08-python2.eb

easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.2.9-CrayGNU-17.08-python3.eb
=> [daint] Update netcdf-python-1.2.9-CrayGNU-17.08-python3.eb

easybuild/easyconfigs/m/mpiP/mpiP-3.4.1-CrayCCE-17.08.eb, easybuild/easyconfigs/m/mpiP/mpiP-3.4.1-CrayGNU-17.08.eb, easybuild/easyconfigs/m/mpiP/mpiP-3.4.1-CrayIntel-17.08.eb, easybuild/easyconfigs/m/mpiP/mpiP-3.4.1-CrayPGI-17.08.eb
[----------] started processing mpip_check_21910 (mpip_check_21910)
[ RUN      ] mpip_check_21910 on dom:gpu using PrgEnv-cray
[ RUN      ] mpip_check_21910 on dom:gpu using PrgEnv-gnu
[ RUN      ] mpip_check_21910 on dom:gpu using PrgEnv-intel
[ RUN      ] mpip_check_21910 on dom:gpu using PrgEnv-pgi
[----------] finished processing mpip_check_21910 (mpip_check_21910)
[----------] waiting for spawned checks to finish
[       OK ] mpip_check_21910 on dom:gpu using PrgEnv-cray
[       OK ] mpip_check_21910 on dom:gpu using PrgEnv-gnu
[       OK ] mpip_check_21910 on dom:gpu using PrgEnv-intel
[       OK ] mpip_check_21910 on dom:gpu using PrgEnv-pgi
[----------] all spawned checks have finished
[  PASSED  ] Ran 4 test case(s) from 1 check(s) (0 failure(s))
=> [daint] mpip/341

easybuild/easyconfigs/g/GPAW/GPAW-1.3.0-CrayGNU-17.08-python2.eb, easybuild/easyconfigs/g/GPAW/gpaw-1.3.0-cray.patch
possible fix for ticket #31398 (BLASC and scaLAPACK on Daint)
enables the compilation of GPAW with ScaLAPACK; has to be tested by user
=> [daint] GPAW 1.3.0 fix

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.2.1-CrayIntel-17.08.eb
I have provided a recipe for `QuantumESPRESSO 6.2.1`, based on the request 31464. 
We still need to test the build, are there any known issues with this release?
=> [daint, dom] New release of QuantumESPRESSO

easybuild/easyconfigs/p/Python-bare/Python-bare-3.6.5.eb, easybuild/easyconfigs/r/reframe/reframe-2.12.eb, jenkins-builds/MCH-RH7.3-17.02, jenkins-builds/common-SLES12-2016.10, jenkins-builds/leone-RHEL6.7EUS-17.06, jenkins-builds/monch-RH6.9-17.06
- Also adapted the Python-bare package to include (again) nose.
=> [daint dom kesch leone monch] Easyconfig for ReFrame 2.12

easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08-cuda-8.0-pat-6.5.1.eb, easybuild/easyconfigs/c/CP2K/CP2K-5.1-CrayGNU-17.08-pat-6.5.1.eb
Recipes to build `CP2K` release 5.1. instrumented with `perftools-lite`
=> [daint dom] CP2K 5.1. with perftools-lite

easybuild/easyconfigs/s/SIRIUS/SIRIUS-5.5-CrayIntel-17.08-cuda-8.0.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-5.5-CrayIntel-17.08.eb, easybuild/easyconfigs/s/SIRIUS/platform.Intel.json
First trial to build SIRIUS on Daint.
=> [daint-gpu] Sirius 5.5 on Piz Daint

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.2-CrayIntel-17.08-cuda-8.0.eb
=> [daint-gpu] QE+Sirius on GPU

easybuild/easyconfigs/e/ELPA/ELPA-2017.11.001-CrayIntel-17.08.eb
=> [daint, dom] ELPA library 

jenkins/JenkinsfileProductionEB
Environment variable `EB_CUSTOM_REPOSITORY` used by the CSCS EasyBuild custom module
=> [daint dom kesch leone monch] Fix environment variable name

jenkins/JenkinsfileProductionEB
Adding chmod command to make logfiles readable
=> [daint dom kesch leone monch] Update JenkinsfileProductionEB

easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-parallel.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-serial.eb
Removed dependency `PyExtensions`
=> [dom-gpu] h5py

easybuild/easyconfigs/a/abcpy/abcpy-0.5.0-CrayGNU-17.12-python3.eb, easybuild/easyconfigs/c/cloudpickle/cloudpickle-0.3.1-CrayGNU-17.12-python3.eb, easybuild/easyconfigs/g/glmnet/glmnet-2.0.0-CrayGNU-17.12-python3.eb, easybuild/easyconfigs/s/scikit-learn/scikit-learn-0.18.2-CrayGNU-17.12-python3.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
=> [daint] ABCpy version 0.5

jenkins/JenkinsfileProductionEB
Allow builds in additional archs even if the script fails in previous ones.
=> [dom daint kesch monch leone] Bugfix/jenkins production failure

easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python2-parallel.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python2-serial.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-parallel.eb, easybuild/easyconfigs/h/h5py/h5py-2.7.1-CrayGNU-17.08-python3-serial.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
I have updated the `h5py` recipes in production and the version in the software stack as well.
=> [daint dom] new h5py version in production

easybuild/easyconfigs/c/CrayCCE/CrayCCE-18.04.eb, easybuild/easyconfigs/c/CrayGNU/CrayGNU-18.04.eb, easybuild/easyconfigs/c/CrayIntel/CrayIntel-18.04.eb, easybuild/easyconfigs/c/CrayPGI/CrayPGI-18.04.eb
april PE toolchains for testing cuda9 on dom
=> [dom-gpu] aprilPE

easybuild/easyconfigs/p/ParaView/ParaView-5.5.1-EGL-CrayGNU-17.08.eb
5.5.1 provides a critical bug fix for the BioMedical project of ETH-Z
My private build has been fully successful.
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.5.1-CrayGNU-17.08-EGL/easybuild/easybuild-ParaView-5.5.1-20180604.095819.log
=> [daint-gpu] ParaView 5.5.1 fixes a bug with the Ghost Cell Generator

easybuild/easyconfigs/o/ospray/ospray-1.6.1-CrayGNU-17.08.eb
upgrading ospray nice-to-have for ParaView
=> [daint-gpu] ospray pre-compiled lib upgrade from intel

easybuild/easyconfigs/h/HPX/HPX-1.1.0-CrayGNU-17.08.eb, easybuild/easyconfigs/j/jemalloc/jemalloc-5.1.0-CrayGNU-17.08.eb
This adds HPX and its (missing) dependency jemalloc.
=> [daint] HPX and jemalloc

easybuild/easyconfigs/p/Python-bare/Python-bare-3.6.5.eb
Current pygelf version is 0.3.3
=> [daint] Added pygelf in order to allow grafana logging

easybuild/easyconfigs/m/magma/magma-2.4.0-CrayIntel-17.08-cuda-8.0.eb, easybuild/easyconfigs/m/magma/make.inc-2.4.0
=> [daint-gpu] magma-2.4.0

easybuild/easyconfigs/c/CMake/CMake-3.10.1-foss-2016b.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-foss-2016b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108-foss-2016b.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108_cleanup.patch, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-20180108_fix-decomposedBlockData.patch, jenkins-builds/leone-RHEL6.7EUS-17.06
Installation requested by Hilti
=> [leone] OpenFOAM 5.0 20180108 + decomposedBlockData patch

easybuild/easyconfigs/d/dask/dask-0.17.0-CrayGNU-17.08-python3.eb, easybuild/easyconfigs/p/protobuf/protobuf-3.5.1-CrayGNU-17.08-python3.eb
This is to update the name of the PyExtensions module on the TensorFlow's dependencies.
=> [daint-gpu] TensorFlow deps: Update pyextensions name

easybuild/easyconfigs/c/CrayPGI/CrayPGI-18.07.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-Cray-18.07.patch, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayCCE-18.07.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayGNU-18.07.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayIntel-18.07.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayPGI-18.07.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-CrayGNU-18.07.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-CrayIntel-17.08.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.2.1-CrayIntel-18.07.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.2.1.eb, easybuild/easyconfigs/m/mxml/mxml-2.10-CrayGNU-18.07.eb, easybuild/easyconfigs/m/mxml/mxml-2.10-CrayIntel-18.07.eb
Will fix https://madra.cscs.ch/scs/doc/issues/318
waiting for CrayPGI toolchain
=> [dom-gpu]: ipm/cle6u06

easybuild/easyconfigs/i/IDL/IDL-8.5.1.eb, jenkins-builds/6.0.UP04-17.08-gpu, jenkins-builds/6.0.UP04-17.08-mc
will fix https://madra.cscs.ch/scs/doc/issues/351
=> [daint] idl

easybuild/easyconfigs/i/IDL/IDL-8.5.1.eb, jenkins-builds/6.0.UP06-18.07-gpu, jenkins-builds/6.0.UP06-18.07-mc
https://webrt.cscs.ch/Ticket/Display.html?id=32445
=> [dom] idl/cle6

easybuild/easyconfigs/p/Python-bare/Python-bare-3.6.6.eb
* Update python packages to latest versions.
=> [dom daint kesch monch] Add eb file for Python-bare-3.6.6

easybuild/easyconfigs/d/ddt/ddt-18.1.3-Redhat-6.0.eb, easybuild/easyconfigs/d/ddt/ddt-18.1.3-Redhat-7.0.eb, easybuild/easyconfigs/d/ddt/ddt-18.1.3-Suse-12.eb, jenkins-builds/6.0.UP06-18.07-gpu, jenkins-builds/6.0.UP06-18.07-mc
https://madra.cscs.ch/scs/doc/issues/310
=> [dom] ddt/18.1.3

easybuild/easyconfigs/v/vampir/vampir-9.5.0.eb
license issue
will fix https://madra.cscs.ch/scs/doc/issues/346
=> [dom] vampir/950

easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.13.1-CrayGNU-18.07.eb, easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.1.1-CrayGNU-18.07.eb
As agreed, I'm removing the extension `PyMySQL` from the list. For more details, see https://git.cscs.ch/scs/doc/issues/303
=> [dom] Removing PyMySQL from PyExtensions

jenkins-builds/6.0.UP06-18.07-gpu, jenkins-builds/6.0.UP06-18.07-mc
Remove obsolete elements in the list
=> [dom] Cleanup production file 18.07

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-gitlab-CrayGNU-17.08.eb
follow up of https://github.com/eth-cscs/production/pull/724
=> [daint-gpu] qe-6.3 (#2)

jenkins-builds/6.0.UP06-18.07-gpu, jenkins-builds/6.0.UP06-18.07-mc
Removing items not yet available in production repository.
=> [dom] Fix production

easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07-cuda-9.1.eb, easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07-cuda-9.1.psmp, easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07.eb, easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-18.07.psmp, easybuild/easyconfigs/l/Libint/Libint-1.1.4-CrayGNU-18.07.eb, easybuild/easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-18.07.eb, jenkins-builds/6.0.UP06-18.07-gpu, jenkins-builds/6.0.UP06-18.07-mc
`CP2K` latest stable release `6.1` with dependencies.
=> [dom] CP2K and dependencies

easybuild/easyconfigs/b/basicanalysis/basicanalysis-0.3.6.eb, easybuild/easyconfigs/e/Extrae/Extrae-3.5.4-CrayGNU-18.07.eb
=> [dom-gpu] extrae354_pe1807_gnu.x

easybuild/easyconfigs/b/Bison/Bison-3.0.5-CrayGNU-17.08.eb, easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-17.08-PLUMED-2.4.2-cuda-8.0.eb, easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-17.08-PLUMED-2.4.2-cuda-8.0.psmp, easybuild/easyconfigs/l/libxc/libxc-4.2.3-CrayGNU-17.08.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.2-CrayGNU-17.08.eb
Following a user request, I have prepared a recipe for CP2K patched with PLUMED.
=> [daint-gpu] CP2K with PLUMED

jenkins-builds/production.sh
Fix first build of a new software stack.
=> [dom-gpu] Postponing command module load

easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.15.1-CrayGNU-18.07.eb, easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.5.1-CrayGNU-18.07.eb
Recipes for `PyExtensions` that load the most recent `cray-python` on Dom.
=> [dom] PyExtensions with new cray-python

jenkins/Machines.groovy
Commenting out `Fulen` until the system will be available.
=> [daint dom leone] Update Machines.groovy

easybuild/easyconfigs/l/libxc/libxc-4.2.3-CrayIntel-17.08.eb
recipe for libxc-4.2.3 with CrayIntel
=> [daint-gpu] LibXC with CrayIntel

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.3-CrayIntel-17.08-cuda-8.0.eb
=> [daint-gpu] QE-6.3 + SIRIUS

jenkins/Machines.groovy
We need to add fulen before we enable the production list
=> Add fulen to available machines

easybuild/easyconfigs/p/ParaView/ParaView-5.5.2-EGL-CrayGNU-18.08.eb, easybuild/easyconfigs/p/ParaView/nek5000reader.patch
=> [dom-gpu] ParaView the GPU version with updates for 18.08

easybuild/easyconfigs/g/GSL/GSL-2.5-CrayCCE-18.08.eb, easybuild/easyconfigs/g/GSL/GSL-2.5-CrayGNU-18.08.eb, easybuild/easyconfigs/g/GSL/GSL-2.5-CrayIntel-18.08.eb
EasyBuild recipes for the most recent release of `GSL`.
=> [dom] GSL library

easybuild/easyconfigs/l/Lmod/Lmod-7.8.2.eb, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
https://madra.cscs.ch/scs/doc/issues/323
=> [dom] lmod

jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
The build of `GSL` has been successful and the recipes have already been merged in the repository.
=> [dom] Adding GSL in production

easybuild/cray_external_modules_metadata.cfg, easybuild/easyconfigs/s/SLEPc/SLEPc-3.7.4-CrayIntel-17.08-complex-64.eb
User request (https://webrt.cscs.ch/Ticket/Display.html?id=32866)
=> [daint] SLEPc/3.7.4 + updated deps and webpage

easybuild/easyconfigs/v/VTK/VTK-8.1.1-EGL-CrayGNU-18.08-python3.eb, jenkins-builds/6.0.UP07-18.08-gpu
VTK libs and vtkpython for batch-mode rendering
=> [dom-gpu] VTK for GPU+EGL for 18.08

easybuild/easyconfigs/p/petsc4py/petsc4py-3.7.0-CrayIntel-17.08-complex-64.eb, easybuild/easyconfigs/s/SLEPc/SLEPc-3.7.4-CrayIntel-17.08-complex-64.eb, easybuild/easyconfigs/s/slepc4py/slepc4py-3.7.0-CrayIntel-17.08-complex-64.eb
Needed for this [tiket](https://webrt.cscs.ch/Ticket/Display.html?id=32866)
=> [daint] Python bindings for PETSc and SLEPc

easybuild/easyconfigs/p/PROJ/PROJ-5.1.0-gmvolf-17.02.eb, jenkins-builds/MCH-RH7.3-17.02
Last release of `PROJ` as requested by CSCS RT #32729
=> [kesch] PROJ

easybuild/easyconfigs/a/absl/absl-0.2.2-CrayGNU-17.08-python3.eb, easybuild/easyconfigs/d/dask/dask-0.18.1-CrayGNU-17.08-python3.eb, easybuild/easyconfigs/p/protobuf-core/protobuf-core-3.6.0-CrayGNU-17.08.eb, easybuild/easyconfigs/p/protobuf/protobuf-3.6.0-CrayGNU-17.08-python3.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-CrayGNU-17.08-python3.eb, easybuild/easyconfigs/t/TensorFlow/tensorflow-v1.7.0-python3-cscs.patch
Requested in [this ticket](https://webrt.cscs.ch/Ticket/Display.html?id=32840)
=> [daint-mc] TensorFlow-1.7.0 without CUDA support

easybuild/easyconfigs/c/COSMO_pompa_crclim_dycore/COSMO_pompa_crclim_dycore-551f6b44dc13227d92225edfd6e3bfd58c782928-CrayGNU-18.08-float.eb, easybuild/easyconfigs/l/libgrib1_crclim/libgrib1_crclim-a1e4271bf3a99db84330f9ded82fd6fddfce2f61-CrayGNU-18.08.eb, easybuild/easyconfigs/s/STELLA_CRCLIM/STELLA_CRCLIM-4a5f9c53d3b159cbdf9cfaa2eb4450181780f594-CrayGNU-18.08-double.eb, easybuild/easyconfigs/s/STELLA_CRCLIM/STELLA_CRCLIM-4a5f9c53d3b159cbdf9cfaa2eb4450181780f594-CrayGNU-18.08-float.eb, easybuild/easyconfigs/s/Serialbox/Serialbox-2.4.1-CrayGNU-18.08.eb
https://madra.cscs.ch/scs/doc/issues/282
=> [dom-gpu] Cosmo2eb pe1808

easybuild/easyconfigs/i/IPython/IPython-5.7.0-CrayGNU-17.08-python2.eb, easybuild/easyconfigs/i/ipykernel/ipykernel-4.8.2-CrayGNU-17.08-python2.eb
The line `/opt/python/17.06.1/bin/python -m ipykernel_launcher $@` in `... /common/UES/ ... /IPython/py27launcher` changes then to `python -m ipykernel_launcher $@`.
=> [daint] Update python2 version on IPython and ipykernel

jenkins-builds/6.0.UP07-18.08-mc
add ParaView-OSMesa, Mesa and LLVM
=> [dom-mc] Update 6.0.UP07-18.08-mc

easybuild/easyconfigs/m/magma/magma-2.2.0-CrayGNU-18.08-cuda-9.1.eb, easybuild/easyconfigs/m/magma/magma-2.3.0-CrayIntel-18.08-cuda-9.1.eb, jenkins-builds/6.0.UP07-18.08-gpu
I get several performance errors
Furthermore there is in two regression tests infinity produced, but this happens also on daint
=> [dom-gpu] magma18.08cuda9.1

easybuild/easyconfigs/p/pgi/pgi-17.10-gcc-5.4.0-2.26.eb, jenkins-builds/MCH-RH7.3-17.02
for https://github.com/eth-cscs/production/pull/809
=> [kesch] Kesch+pgi

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-w90.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-17.08-w90.makefile.include
New recipe with pre-processor flag adding support for Wannier functions in VASP
=> [daint-mc] Adding recipe for VASP with Wannier 90

easybuild/easyconfigs/e/ELPA/ELPA-2018.05.001-CrayIntel-17.08.eb
add extra CPATH variable to module
=> [daint] add extra CPATH variable to module

easybuild/easyconfigs/d/ddt/ddt-18.2.2-Redhat-7.0.eb, jenkins-builds/MCH-RH7.3-17.02
https://madra.cscs.ch/scs/doc/issues/382
=> [kesch] ddt

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.3-CrayIntel-17.08-cuda-8.0.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-5.8-CrayIntel-17.08-cuda-8.0.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-5.8.1-CrayIntel-17.08-cuda-8.0.eb, easybuild/easyconfigs/s/SIRIUS/platform.Intel.json
* minor bug fixes
* enable scalapack
=> [daint-gpu] Update QE+Sirius

easybuild/easyconfigs/m/MUST/MUST-v1.6-rc1-CrayGNU-18.08.eb, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
https://webrt.cscs.ch/Ticket/Display.html?id=18392
=> [dom-gpu] must

easybuild/easyconfigs/c/COSMO_pompa_crclim_dycore/COSMO_pompa_crclim_dycore-551f6b4-CrayGNU-18.08-cordex-double.eb, easybuild/easyconfigs/c/COSMO_pompa_crclim_dycore/COSMO_pompa_crclim_dycore-551f6b4-CrayGNU-18.08-cuda-9.1-cordex-double.eb, easybuild/easyconfigs/s/STELLA_CRCLIM/STELLA_CRCLIM-4a5f9c5-CrayGNU-18.08-cordex-double.eb
Changed k-parameters (level and flat) in the STELLA-build.
(see https://webrt.cscs.ch/Ticket/Display.html?id=32909)
=> [dom]: CORDEX versions of Dycore and STELLA

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.08-cuda-9.1-pat-7.0.2.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-18.08-pat-7.0.2.eb
Modified recipe for `VASP` and new recipes for the perftools instrumented modules
=> [dom] Adding VASP recipes

jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
New recipes for `LAMMPS` and `QuantumESPRESSO`
=> [dom-gpu] Adding LAMMPS and QuantumESPRESSO in production list 18.08

login/daint-gpu, login/daint-mc
New software stack structure in the login folder under `production`.
=> [daint-gpu] Updating login modules for Piz Daint

jenkins-builds/production.sh
Adapting xalt` section of `production.sh`
=> [daint-gpu] Update xalt section in production

easybuild/easyconfigs/b/byacc/byacc-20170709-CrayGNU-18.08.eb, easybuild/easyconfigs/g/GMP/GMP-6.1.2-CrayGNU-18.08.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-CrayGNU-18.08-PLUMED-2.4.3-cuda-9.1.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2018.3-CrayGNU-18.08-PLUMED-2.4.3.eb, easybuild/easyconfigs/g/gc/gc-7.6.0-CrayGNU-18.08.eb, easybuild/easyconfigs/g/guile/guile-2.0.14-CrayGNU-18.08.eb, easybuild/easyconfigs/l/libmatheval/libmatheval-1.1.11-CrayGNU-18.08.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.4.3-CrayGNU-18.08.eb, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
PLUMED 2.4.3 released last Oct 5th does support GROMACS 2018.3
=> [daint, dom] Gromacs 18.03 and PLUMED 2.4.3

jenkins-builds/production.sh
The new `Lmod` modulefile is hidden and the pull request is addressing this change.
=> [daint-gpu] Changing Lmod module load command

jenkins/JenkinsfileRegressionEB, jenkins/util.groovy
* Fix checking for empty list.
=> [daint dom fulen kesch] Fix bug in 'getMachineConfiguration' method

easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-18.08-cordex-double.eb, easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-18.08-crclim-double.eb, easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-18.08-cuda-9.1-cordex-double.eb, easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-18.08-cuda-9.1-crclim-double.eb, easybuild/easyconfigs/s/STELLA/STELLA-4a5f9c5-CrayGNU-18.08-cordex-double.eb, easybuild/easyconfigs/s/STELLA/STELLA-4a5f9c5-CrayGNU-18.08-crclim-double.eb
These are the same deps used in #873, but without them already being merged to the master, the jenkins tests for COSMO fail.
=> [daint] COSMO deps as preparatory PR

easybuild/easyconfigs/a/adios/adios-1.13.1-CrayIntel-18.08.eb, easybuild/easyconfigs/b/Blosc/Blosc-1.14.4-CrayIntel-18.08.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayGNU-18.08.eb, easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-CrayIntel-18.08.eb, easybuild/easyconfigs/l/lz4/lz4-1.8.3-CrayIntel-18.08.eb, easybuild/easyconfigs/m/mxml/mxml-2.12-CrayIntel-18.08.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-CrayIntel-18.08.eb
This ADIOS recipe features support for many different compression algorithms including those used by the PRACE group of HZDR (blosc and zlib). Moreover, it is optimized for Cray and Lustre.
=> [daint]  ADIOS recipe with dependencies for CrayIntel-18.08

jenkins/Machines.groovy
=> [dom-gpu] Disable fulen

easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.5-CrayGNU-18.08.eb, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.6-CrayGNU-18.08.eb
This build is intended to allow users of OpenFOAM to reduce the number of installed packages on $HOME.
See, e. g., webRT ticket [33885](https://webrt.cscs.ch/Ticket/Display.html?id=33885).
=> [daint] Scotch for open foam

easybuild/easyconfigs/p/PyMySQL/PyMySQL-0.9.2-CrayGNU-18.08-python2.eb, easybuild/easyconfigs/p/pygelf/pygelf-0.3.1-CrayGNU-18.08-python2.eb, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
fix for 
https://github.com/eth-cscs/production/pull/729#issuecomment-435660633
=> [dom] pygelf+pymysql

easybuild/easyconfigs/c/CMake/CMake-3.12.4.eb
This patch version 3.12.4 fixes a bug concerning MPI and CUDA
=> [daint] Add CMake 3.12.4

easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08.eb
Updated packages, adding user-meamc
=> [daint-mc] Update LAMMPS-22Aug2018-CrayGNU-18.08.eb

easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb
Updated list of packages, adding user-meamc.
=> [daint-gpu] LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb

easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb
Reverts eth-cscs/production#922
=> Revert "[daint-gpu] LAMMPS-22Aug2018-CrayGNU-18.08-cuda-9.1.eb"

easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08.eb
Reverts eth-cscs/production#923
=> Revert "[daint-mc] Update LAMMPS-22Aug2018-CrayGNU-18.08.eb"

easybuild/easyconfigs/b/Bison/Bison-3.0.5-GCCcore-6.2.0.eb, easybuild/easyconfigs/b/binutils/binutils-2.30-GCCcore-6.2.0.eb, easybuild/easyconfigs/f/FFTW/FFTW-3.3.7-gmvapich2-16.11.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-6.2.0.eb, easybuild/easyconfigs/g/GCC/GCC-6.2.0-2.30.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-6.2.0.eb, easybuild/easyconfigs/g/gmvapich2/gmvapich2-16.11.eb, easybuild/easyconfigs/g/gmvolf/gmvolf-16.11.eb, easybuild/easyconfigs/h/help2man/help2man-1.47.6-GCCcore-6.2.0.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.8-gmvolf-16.11.eb, easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-6.2.0.eb, easybuild/easyconfigs/m/MVAPICH2/MVAPICH2-2.3-GCC-6.2.0-2.30.eb, easybuild/easyconfigs/o/OpenBLAS/OpenBLAS-0.2.20-GCC-6.2.0-2.30.eb, easybuild/easyconfigs/s/ScaLAPACK/ScaLAPACK-2.0.2-gmvapich2-16.11-OpenBLAS-0.2.20.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-6.2.0.eb
This should be compatible with CUDA 9.2 currently installed on Fulen
=> [fulen]Add gmvolf 16.11 with GCC 6.20 and MVAPICH2.3

easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-18.08-PLUMED-2.4.3-cuda-9.1.eb
The recipe will build `LAMMPS-22Aug18` patched with `PLUMED-2.4.3`.
=> [daint-gpu] LAMMPS with PLUMED

easybuild/easyconfigs/o/ospray/ospray-1.7.2-CrayGNU-18.08.eb
=> [daint] ospray version update

jenkins-builds/6.0.UP07-18.08-mc
Adding Dask 1.0.0 as a set default module
=> [dom-mc,daint-mc] Update 6.0.UP07-18.08-mc

easybuild/easyconfigs/d/ddt/ddt-18.3-Ubuntu-16.04.eb, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
=> [daint] ddt_shifter

jenkins/Machines.groovy
Removing Monch and updating paths for Leone after the recent upgrade
=> [dom] Update Machines.groovy

easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.1-CrayGNU-18.08.eb, easybuild/easyconfigs/x/x264/x264-20181218-CrayGNU-18.08.eb, easybuild/easyconfigs/y/Yasm/Yasm-1.3.0-CrayGNU-18.08.eb
As per user request [here](https://webrt.cscs.ch/Ticket/Display.html?id=34433).
=> [daint dom] Easyconfig for FFmpeg 4.1 with CrayGNU 18.08

easybuild/easyconfigs/f/flex/flex-2.6.4.eb, easybuild/easyconfigs/g/GCC/GCC-8.2.0-2.30.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0-fix-find-isl.patch, easybuild/easyconfigs/g/GCCcore/GCCcore-8.2.0.eb, easybuild/easyconfigs/g/GCCcore/gcc-8.2.0-isl-0.20-missing-include.patch
gcc/8.x for https://jira.cscs.ch/browse/UES-29 (openacc evaluation)
=> [daint-gpu] gcc8

easybuild/easyconfigs/s/Serialbox/Serialbox-2.5.1-CrayGNU-18.08.eb
https://jira.cscs.ch/browse/UES-137
=> [dom] serialbox/251

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.3-rc3-sirius-CrayIntel-18.08-cuda-9.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.0.0-CrayIntel-18.08-cuda-9.1.eb
I'm changing a name convention for the QE eb script because I sync with QE's develop branch which is always v6.3
=> [daint-gpu] update QE+SIRIUS to the latest version

easybuild/easyconfigs/f/fltk/fltk-1.3.4-1.eb, easybuild/easyconfigs/l/LibVNCServer/LibVNCServer-0.9.12.eb, easybuild/easyconfigs/t/TigerVNC/TigerVNC-1.9.0.eb
system's version is rather old (xorg-x11-Xvnc-1.6.0), need a more recent one.
=> [dom-gpu] vncserver

easybuild/easyconfigs/i/IPython/IPython-7.2.0-gmvolf-17.02-Python-3.7.2.eb, easybuild/easyconfigs/o/OpenSSL/OpenSSL-1.1.0c-gmvolf-17.02.eb, easybuild/easyconfigs/p/Perl/Perl-5.26.1-gmvolf-17.02-bare.eb, easybuild/easyconfigs/p/Python/Python-3.7.2-gmvolf-17.02.eb, jenkins-builds/MCH-RH7.3-17.02
This will produce a Python/3.7.2 module
How to deal with the dependencies? E. g., in case someone wants to install a python module requiring other deps, this would require a change, no?
=> [kesch] Kesch/python 3.7

easybuild/easyconfigs/g/GCCcore/GCCcore-7.3.0-cuda-9.1-offload.eb, easybuild/easyconfigs/n/newlib/newlib-3.1.0.20181231.eb, easybuild/easyconfigs/n/nvptx-tools/nvptx-tools-5f6f343-cuda-9.1.eb
=> [dom-gpu] openmp45_support

jenkins-builds/production.sh
=> [dom] Update production.sh

easybuild/easyconfigs/p/Python/Python-3.5.2-foss-2016b.eb, jenkins-builds/leone-RHEL6.7EUS-17.06
To allow installation of the qd-module.
=> [leone] Python3

easybuild/module/EasyBuild-custom/cscs
=> [daint] Adapt EB module to Tsa EnvironmentModules

easybuild/module/EasyBuild-custom/cscs
Temporary fix for Tcl modules to avoid the failure in `ProductionEB`:
https://jenkins.cscs.ch/blue/organizations/jenkins/ProductionEB/detail/ProductionEB/593/pipeline
=> [daint] Fix EasyBuild-custom/cscs

easybuild/easyconfigs/g/git-lfs/git-lfs-2.7.1.eb
=> [daint] lfs

easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.1.5-CrayIntel-18.08-cuda-9.1.eb
=> [daint] SIRIUS/6.1.5

easybuild/easyconfigs/i/IPM/IPM-2.0.6-Cray-19.03.patch, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayCCE-19.03.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayGNU-19.03.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayIntel-19.03.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.2.1.eb, easybuild/easyconfigs/m/mxml/mxml-2.10-CrayGNU-19.03.eb, easybuild/easyconfigs/p/ploticus/ploticus-2.42-ipm.eb, jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
wrong branch name (not mpip, ipm in reality) but ok
=> [dom] ipm for 19.03

easybuild/easyconfigs/m/mpiP/mpiP-57fc864-CrayCCE-19.03.eb, easybuild/easyconfigs/m/mpiP/mpiP-57fc864-CrayIntel-19.03.eb
Production list: 
```
mpiP-57fc864-CrayCCE-19.03.eb                                           --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
mpiP-57fc864-CrayGNU-19.03.eb                      --set-default-module --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
mpiP-57fc864-CrayIntel-19.03.eb                                         --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
mpiP-57fc864-CrayPGI-19.03.eb                                           --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
```
```
mpiP-57fc864-CrayCCE-19.03.eb                                           --installpath=$APPS/UES/jenkins/7.0.UP00/mc/easybuild/tools
mpiP-57fc864-CrayGNU-19.03.eb                      --set-default-module …
```
=> [dom] mpip for 19.03

easybuild/easyconfigs/g/gperftools/gperftools-2.7.eb, easybuild/easyconfigs/p/pprof/pprof-9daae4f.eb
```
pprof-9daae4f.eb                     --set-default-module --installpath=$APPS/UES/jenkins/7.0.UP00/gpu/easybuild/tools
```
```
pprof-9daae4f.eb                     --set-default-module --installpath=$APPS/UES/jenkins/7.0.UP00/mc/easybuild/tools
```
=> [dom] pprof for PE 19.03

easybuild/easyconfigs/l/likwid/likwid-4.3.3-perf_event.eb
https://jira.cscs.ch/browse/MAINT-31
=> [dom] likwid for PE 19.03

jenkins/JenkinsfileTestingEB
Temporary change to run on Dom login node for testing
=> [daint-gpu] Update JenkinsfileTestingEB

easybuild/easyconfigs/a/advisor/advisor_2019_update3.eb, easybuild/easyconfigs/a/advisor/advisor_2019_update3.patch, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
Moving to latest tool's version to try to fix the daily failures:
https://jenkins.cscs.ch/blue/organizations/jenkins/reframe-daint-production-daily/detail/reframe-daint-production-daily/483/pipeline/#step-15-log-2067
=> [daint-mc] advisor2019

easybuild/easyconfigs/a/advisor/advisor_2019_update3.eb
https://jira.cscs.ch/browse/UES-335
=> [daint, dom-gpu] fix for jenkins

easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03-cuda-10.0.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03-cuda-10.0.makefile.include, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03.makefile.include
I have inserted a symbolic link to the `makefile.include`, since it is the same as before.
=> [dom-gpu] VASP recipes for cle7

easybuild/easyconfigs/c/cURL/cURL-7.61.1-CrayGNU-19.03.eb, easybuild/easyconfigs/c/cftime/cftime-1.0.0-CrayGNU-19.03-python2.eb, easybuild/easyconfigs/c/cftime/cftime-1.0.2.1-CrayGNU-19.03-python3.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.6.2-CrayGNU-19.03.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.03-cuda-10.0.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.03.eb, easybuild/easyconfigs/l/libspatialindex/libspatialindex-1.8.5-CrayGNU-19.03.eb, easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.4.1-CrayGNU-19.03-python2.eb, easybuild/easyconfigs/n/netcdf4-python/netcdf-python-1.4.1-CrayGNU-19.03-python3.eb, easybuild/easyconfigs/o/oq-engine/oq-engine-3.2.0-CrayGNU-19.03.eb, easybuild/easyconfigs/o/ospray/ospray-1.8.4-CrayGNU-19.03.eb, easybuild/easyconfigs/p/pycuda/pycuda-2018.1.1-CrayGNU-19.03-python2-cuda-10.0.eb, easybuild/easyconfigs/p/pycuda/pycuda-2018.1.1-CrayGNU-19.03-python3-cuda-10.0.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03-cuda-10.0.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03-cuda-10.0.makefile.include, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03.eb, easybuild/easyconfigs/v/VASP/VASP-5.4.4-CrayIntel-19.03.makefile.include
N.B. This is different that the GL version which runs on the GPU.
This version runs on the mc partition
== Results of the build can be found in the log file(s) /scratch/snx1600tds/jfavre/daint/software/ParaView/5.6.0-CrayGNU-19.03-OSMesa/easybuild/easybuild-ParaView-5.6.0-20190410.154740.log
== Build succeeded for 2 out of 2
=> [dom-mc] ParaView-OSMesa default version ready for TC 19.03

jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
Adding successful builds to the production list.
=> [dom-gpu] Updating production list gpu and mc

easybuild/easyconfigs/s/spectral/spectral-3.4.1.eb
=> [dom] Remove checksum

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4-rc1-sirius-CrayIntel-18.08-cuda-9.1.eb
regular synchronisation with QE development branch
=> [daint-gpu] Latest QE with SIRIUS library

jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
The pull request is currently work in progress (`WIP`). 
It will be merged in production when more items will be added to the software lists.
=> [dom-gpu] Update production list

easybuild/easyconfigs/l/libsodium/libsodium-1.0.17-gmvolf-17.02.eb, easybuild/easyconfigs/s/sodium/sodium-1.1-gmvolf-17.02-R-3.5.2.eb
This is a recipe with the easyblock `RPackage` to provide the R package`sodium`, release `1.1`:
https://cran.r-project.org/web/packages/sodium/index.html
=> [kesch] RPackage sodium

easybuild/module/EasyBuild-custom/cscs
Set recursive module unload for Arolla/Tsa (the subject matches `Kesch` since `Tsa` is not yet available in the list of systems)
=> [kesch] EasyBuild recursive unload

easybuild/module/EasyBuild-custom/cscs
Remove statement setting `EASYBUILD_PREFIX` to `$SCRATCH`
=> [daint-gpu] Update EasyBuild-custom/cscs

easybuild/easyconfigs/a/advisor/advisor_2019_update4.eb, easybuild/easyconfigs/a/advisor/advisor_2019_update4.patch, easybuild/easyconfigs/v/vtune_amplifier/vtune_amplifier_2019_update4.eb, easybuild/easyconfigs/v/vtune_amplifier/vtune_amplifier_2019_update4.patch
=> [dom-mc] Updating intel tools

easybuild/module/EasyBuild-custom/cscs
RPATH on Arolla/Tsa to avoid inconsistent builds
=> [kesch] Setting RPATH

easybuild/easyconfigs/s/singularity/singularity-3.2.0-daint.eb, easybuild/easyconfigs/s/singularity/singularity-3.2.1-daint.eb, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc
Includes binds for cray-mpi and nvidia gpus.
=> [daint] singularity 3.2.1 wrapper module for Daint

easybuild/easyconfigs/i/inspector/inspector_2019_update4.eb, easybuild/easyconfigs/i/inspector/inspector_2019_update4.patch
=> [dom] Adding latest intel inspector

easybuild/module/EasyBuild-custom/cscs
This is a suggestion for a fix, which became necessary for the lmod installed on Tsa (tsa-cn017/cn018).
=> [daint-gpu] Suggest EB module fix w.r.t lmod

jenkins/JenkinsfileRegressionEB, jenkins/Machines.groovy
This adds also a step for removing the files after building and archiving the logs in RegressionEB
=> [dom] Add unuse paths for regression on dom

easybuild/easyconfigs/s/Spack/Spack-daint-git-master.eb, easybuild/easyconfigs/s/Spack/Spack-daint.eb
Add Spack EB recipe pre-configure for the current Piz Daint.
=> [daint] Spack for Piz Daint

jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
Add JupyterHub 1.0.0 release! Also made default so to be consistent with jupyter-dev.
=> [dom] jupyterhub 1.0

easybuild/easyconfigs/j/jupyterhub/jupyterhub-1.0.0-CrayGNU-19.03.eb
JHub version 1.0.0 to match jupyter-dev VM.
=> [dom] Create jupyterhub-1.0.0-CrayGNU-19.03.eb

easybuild/easyconfigs/c/CMake/CMake-3.14.5.eb, jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
=> [dom] CMake/3.14.5

easybuild/easyconfigs/d/ddt/ddt-19.1-Suse-15.0.eb, jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
Will fix [MAINT-86](https://jira.cscs.ch/browse/MAINT-86)
=> [dom] ddt for cuda10

easybuild/easyconfigs/n/nvidia-nsight/nvidia-nsight-2019.3.1.eb, easybuild/easyconfigs/n/nvtop/nvtop-1.0.0-CrayGNU-19.03-cuda-10.0.eb, jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
Will fix https://jira.cscs.ch/browse/MAINT-87
=> [dom-gpu] nvprof

easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.06-clang.eb, easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.06-classic.eb, easybuild/easyconfigs/c/CrayCCE/CrayCCE-19.06.eb, easybuild/easyconfigs/c/CrayGNU/CrayGNU-19.06.eb, easybuild/easyconfigs/c/CrayIntel/CrayIntel-19.06.eb, easybuild/easyconfigs/c/CrayPGI/CrayPGI-19.06.eb
=> [dom] PE/19.06 toolchains 

README.md
=> [daint] Update README.md

easybuild/easyconfigs/d/dask/dask-1.2.2-CrayGNU-19.03-python3.eb
1.2.2 for Dom, to match new version proposed for daint.
=> [dom] dask-1.2.2-CrayGNU-19.03-python3.eb

jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc, jenkins-builds/7.0.UP00-19.03-gpu, jenkins-builds/7.0.UP00-19.03-mc
=> [daint dom]  Update production list to include dask 1.2.2

easybuild/easyconfigs/h/h5py/h5py-2.8.0-CrayGNU-19.06-python3-serial.eb, easybuild/easyconfigs/m/mdl/NVIDIA-mdl-317500.2554-CrayGNU-19.06.eb, easybuild/easyconfigs/o/OpenImageDenoise/oidn-0.9.0-CrayGNU-19.06.eb, easybuild/easyconfigs/o/OptiX/NVIDIA-OptiX-6.0.0-CrayGNU-19.06.eb, easybuild/easyconfigs/o/ospray/ospray-1.8.5-CrayGNU-19.06.eb, easybuild/easyconfigs/v/VisRTX/VisRTX-0.1.5-CrayGNU-19.06.eb
I have tested the Release Candidate 1 with these extras. ParaView itself will be a separate MR when the release is official
== Results of the build can be found in the log file(s) /scratch/snx1600tds/jfavre/daint/software/ParaView/5.7.0-RC1-CrayGNU-19.06-EGL/easybuild/easybuild-ParaView-5.7.0-RC1-20190703.163315.log
=> [dom-gpu] all extras necessary for ParaView 5.7 on Dom

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.06-cuda-10.1.eb
Adding recipe for latest QE release that fixes the issue https://jira.cscs.ch/browse/MAINT-74
=> [dom-gpu] QE 6.4.1 with CUDA 10.1

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.4.1-CrayIntel-19.06.eb
EasyBuild recipe for QuantumESPRESSO release 6.4.1
=> [dom-mc] QE 6.4.1

easybuild/module/EasyBuild-custom/cscs
Temporary fix for `tsa-cn017` with RedHat 7.6 and PrgEnv-cray 19.4 with Lmod
=> [dom-gpu] Update EasyBuild-custom/cscs

easybuild/module/EasyBuild-custom/cscs
Reverting to EnvironmentModules on tsa-cn017
=> [dom-gpu] Update cscs

jenkins-builds/production.sh
Fixing order of checks for MODULEPATH
=> [dom-gpu] Fix production

jenkins-builds/production.sh
Only users in group `idlethz` should be able to load `IDL`.
=> [daint] IDL in restricted list idlethz

jenkins-builds/production.sh
Fixing command `chgrp` with correct group name.
=> [daint, dom] IDL in restricted list idlethz

easybuild/module/EasyBuild-custom/cscs
=> [dom-gpu] Update EasyBuild module for Tsa

easybuild/easyconfigs/p/PrgEnv-Kesch/PE-18.12.eb, easybuild/easyconfigs/p/pgi_PE/pgi_PE-18.10.eb
Including missing recipe `PE-18.12.eb` in the master.
=> [kesch] Adding 18.12

easybuild/easyconfigs/i/IPM/IPM-2.0.6-Cray-19.06.patch, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayCCE-19.06-classic.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayCCE-19.06.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayGNU-19.06.eb, easybuild/easyconfigs/i/IPM/IPM-2.0.6-CrayPGI-19.06.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-CrayCCE-19.06.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-CrayGNU-19.06.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.3.1-CrayIntel-19.06.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.3.1.eb, easybuild/easyconfigs/m/mxml/mxml-3.0-CrayGNU-19.06.eb, easybuild/easyconfigs/m/mxml/mxml-3.0.eb, jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
https://jira.cscs.ch/browse/MAINT-102
=> [dom] ipm_1906

jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
Will fix [114](https://jira.cscs.ch/browse/MAINT-114)
=> [dom] inspector

jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
Will fix [115](https://jira.cscs.ch/browse/MAINT-115)
=> [dom] advisor

jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
Will fix [116](https://jira.cscs.ch/browse/MAINT-116)
=> [dom] vtune

easybuild/easyconfigs/v/vampir/vampir-9.7.0.eb
Will fix [MAINT-145](https://jira.cscs.ch/browse/MAINT-145)
=> [dom] vampir

easybuild/easyconfigs/m/mpiP/mpiP-57fc864-CrayCCE-19.06-classic.eb, easybuild/easyconfigs/m/mpiP/mpiP-57fc864-CrayPGI-19.06.eb, jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
=> [dom] mpip

easybuild/easyconfigs/s/scorep_binding_python/scorep_binding_python-1.1-CrayGNU-19.06-python3.eb, jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
=> [dom] scorep

easybuild/easyconfigs/c/clang+llvm/clang+llvm-8.0.1-x86_64-linux-sles11.3.eb, easybuild/easyconfigs/f/FileCheck/FileCheck-master-CrayGNU-19.06.eb, easybuild/easyconfigs/g/googlebenchmark/googlebenchmark-1.5.0-CrayGNU-19.06.eb, easybuild/easyconfigs/g/googletest/googletest-1.8.1-CrayGNU-19.06.eb, easybuild/easyconfigs/m/MIPP/MIPP-master.eb, easybuild/easyconfigs/n/nsimd/nsimd-5790840-CrayGNU-19.06.eb, easybuild/easyconfigs/s/sleef/sleef-3.4.0-CrayGNU-19.06.eb
Will fix [488](https://jira.cscs.ch/browse/UES-488)
=> [dom] nsimd

jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc, jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
add dask 2.2.0 and make it default.
=> [daint,dom] Update production lists to add dask 2.2.0

easybuild/cray_external_modules_metadata.cfg, easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.06-APEX.eb, easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-19.06.eb, easybuild/easyconfigs/h/HPX/git_external.patch, easybuild/easyconfigs/o/OTF2/OTF2-2.2.eb
Adds:
- HPX 1.3.0 with latest Boost, hwloc
- Latest OTF2
- HPX 1.3.0 with latest Boost, hwloc, and profiling options enabled (APEX, PAPI, OTF2, RelWithDebInfo)
Apologies if I've messed up the tags. This is intended for daint-mc.
=> [dom-mc] HPX 1.3.0 with and without profiling options

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.0.4-CrayGNU-19.06.eb
=> [dom] New kernels for JLab

easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-18.08-APEX.eb, easybuild/easyconfigs/h/HPX/HPX-1.3.0-CrayGNU-18.08.eb, jenkins-builds/6.0.UP07-18.08-gpu, jenkins-builds/6.0.UP07-18.08-mc, jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
Also adds HPX 1.3.0 recipes for CrayGNU 18.08. Continuation of #1260.
=> [daint,dom] Update production lists with HPX

jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
Add julia 1.1.1 to dom. This is not targetted for final production on Daint but is a placeholder for testing purposes for creating an IJulia kernel for jupyterlab
=> [dom] Update 7.0.UP00-19.06-gpu

jenkins-builds/production.sh
I am prepending `module load daint-gpu` to `module unuse ...` in the script `production.sh`, otherwise the latter is useless.
=> [daint-gpu] Updating order of operations

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.0.4-CrayGNU-19.06.eb
This merge request fixes the incorrect assignment of julia as an external module; thanks @gppezzi
=> [dom] Update jupyterlab-1.0.4-CrayGNU-19.06.eb

easybuild/easyconfigs/l/likwid/likwid-4.3.4-perf_event.eb, easybuild/easyconfigs/l/likwid/likwid-4.3.4.patch, jenkins-builds/7.0.UP00-19.06-gpu, jenkins-builds/7.0.UP00-19.06-mc
=> [dom] install likwid/434

easybuild/module/EasyBuild-custom/cscs
=> [dom-gpu] Update EasyBuild-custom on Tsa

easybuild/easyconfigs/j/julia/julia-1.2.0.eb
Comparison of the behavior of environment variables across julia versions.
=> [dom] Create julia-1.2.0.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-19.06.eb
Adding 1.1.1 because 1.0.X is now unbuildable thanks to changes in the javascript package manager. Also added graphviz module and associated graphviz python module  for visualising dask task graphs.
=> [dom] Create jupyterlab-1.1.1-CrayGNU-19.06.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-18.08.eb
Will be announcing JLab 1.1.1 at the user lab day. Looks like Julia is not going to ready, but I need to test dask lab extension in production (via jupyter.cscs.ch) to ensure ports are open as necessary etc, so this cannot be delayed any further
=> [daint] Create jupyterlab-1.1.1-CrayGNU-18.08.eb

easybuild/easyconfigs/j/jupyterhub/jupyterhub-1.0.0-CrayGNU-18.08.eb
Add JHub 1.0.0 to support legacy 0.35.2 jupyterlab (newer JLab has jupyterhub in-built)
=> [daint] Create jupyterhub-1.0.0-CrayGNU-18.08.eb

easybuild/easyconfigs/i/IDL/IDL-8.5.1-OPR.eb, jenkins-builds/MCH-RH7.5-17.06, jenkins-builds/production.sh
The module is added in production on Escha and Kesch, fixing licensing and bugs.
=> [kesch] Adding IDL OPR in production

jenkins-builds/6.0.UP07-18.08-gpu
Adding JuliaExtensions in the GPU software stack
=> [daint-gpu] Update 6.0.UP07-18.08-gpu with JuliaExtensions

easybuild/cray_external_modules_metadata.cfg
This is the updated metadata for CDT 19.09
=> [dom] Add 19.09 cray metadata

easybuild/cray_external_modules_metadata.cfg
=> [dom] Remove duplicate cudatoolkit entries in metadata

jenkins-builds/7.0.UP00-19.06-gpu
Remove non existing julia recipes
=> [dom-gpu] Update 7.0.UP00-19.06-gpu

jenkins-builds/7.0.UP00-19.06-mc
Remove non existing julia recipe
=> [dom-mc] Update 7.0.UP00-19.06-mc

jenkins-builds/6.0.UP07-18.08-gpu
=> [daint-gpu] Update 6.0.UP07-18.08-gpu

easybuild/easyconfigs/a/Amber/Amber-18-14-14-CrayGNU-19.09-cuda-10.1.eb, easybuild/easyconfigs/a/Amber/Amber-18-14-14-CrayGNU-19.09.eb
Removing commented dependencies
=> [dom-gpu]  Amber in PE 19.09

jenkins-builds/7.0.UP01-19.09-gpu, jenkins-builds/7.0.UP01-19.09-mc
=> [dom-gpu] Remove legacy dask from production lists on Dom

easybuild/easyconfigs/j/Julia/Julia-1.2.0-CrayGNU-18.08-cuda-9.1.eb, easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.2.0-CrayGNU-18.08-cuda-9.1.eb, jenkins-builds/6.0.UP07-18.08-gpu
Addition of the recipe for the latest Julia release.
=> [daint-gpu] Julia v1.2.0

easybuild/easyconfigs/b/basicanalysis/basicanalysis-0.3.6.eb, easybuild/easyconfigs/b/basicanalysis/basicanalysis-0.eb, easybuild/easyconfigs/c/clusteringsuite/clusteringsuite-2.6.9.eb, easybuild/easyconfigs/c/clusteringsuite/clusteringsuite-2.eb, easybuild/easyconfigs/d/Dimemas/Dimemas-5.4.1.eb, easybuild/easyconfigs/d/Dimemas/Dimemas-5.eb, easybuild/easyconfigs/e/Extrae/Extrae-3.7.1-CrayGNU-19.09.eb, easybuild/easyconfigs/f/folding/folding-1.3.2.eb, easybuild/easyconfigs/f/folding/folding-1.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.8.eb, easybuild/easyconfigs/p/Paraver/Paraver-4.8.2.eb, easybuild/easyconfigs/p/Paraver/Paraver-4.eb, easybuild/easyconfigs/s/spectral/spectral-3.4.1.eb, easybuild/easyconfigs/s/spectral/spectral-3.eb, jenkins-builds/7.0.UP01-19.09-gpu, jenkins-builds/7.0.UP01-19.09-mc
Will fix https://jira.cscs.ch/browse/MAINT-166
=> [dom] extrae/3.7.1

easybuild/easyconfigs/n/nvidia-nsight-systems/nvidia-nsight-systems-2019.5.1.eb, jenkins-builds/7.0.UP01-19.09-gpu
Will fix https://jira.cscs.ch/browse/UES-554
=> [dom-gpu] nvidia-nsight-systems

easybuild/easyconfigs/g/GROMACS/GROMACS-2018.6-CrayGNU-18.08-PLUMED-2.5.1-cuda-9.1.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-18.08.eb
The recipe is addressing RT #37142
=> [daint-gpu] New recipe for GROMACS with PLUMED

easybuild/easyconfigs/l/LLVM/LLVM-8.0.0-CrayGNU-18.08.eb, easybuild/easyconfigs/m/Mako/Mako-1.0.7-CrayGNU-18.08-Python-3.6.eb, easybuild/easyconfigs/m/Mesa/Mesa-18.3.3-CrayGNU-18.08.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.7.0-OSMesa-CrayGNU-18.08.eb, jenkins-builds/6.0.UP07-18.08-mc
Build completed.
== COMPLETED: Installation ended successfully (took 17 min 38 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.7.0-CrayGNU-18.08-OSMesa/easybuild/easybuild-ParaView-5.7.0-20190927.082213.log
Removing also older version 5.5.2  from jenkins-build
=> [daint-mc] ParaView 5.7 multi-core Final Release set as default. 

easybuild/easyconfigs/p/PAPI/PAPI-5-7-0.eb, easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayCCE-19.09.eb, easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayIntel-19.09.eb, easybuild/easyconfigs/p/papi-wrap/papi-wrap-1.0-CrayPGI-19.09.eb, jenkins-builds/7.0.UP01-19.09-gpu, jenkins-builds/7.0.UP01-19.09-mc
=> [dom] papi-wrap

easybuild/easyconfigs/n/nvidia-nsight-compute/nvidia-nsight-compute-2019.4.0.12.eb, jenkins-builds/7.0.UP01-19.09-gpu
=> [dom-gpu]  NVIDIA Nsight Compute

jenkins/JenkinsfileProductionEB, jenkins/JenkinsfileRegressionEB, jenkins/JenkinsfileTestingEB, jenkins/Machines.groovy, jenkins/README.md
Remove also fulen from the supported Machines
=> [daint dom kesch] Add cpus-per-task for srun commands

jenkins/JenkinsfileRegressionEB, jenkins/JenkinsfileTestingEB
Also set EASYBUILD_HIDE_DEPS to an empty string
=> [daint dom kesch] Set num tasks to 1 for srun

easybuild/easyconfigs/m/mpi4py/mpi4py-3.0.2-CrayGNU-18.08-python3-cuda9.1.eb
New recipe with mpi4py 3.0.2 requested in CSCS RT #37239.
=> [daint-gpu] mpi4py 3.0.2 on Piz Daint

easybuild/easyconfigs/l/LLVM/LLVM-8.0.0-CrayGNU-19.09.eb, easybuild/easyconfigs/m/Mako/Mako-1.0.7-CrayGNU-19.09-Python-3.6.eb, easybuild/easyconfigs/m/Mesa/Mesa-18.3.3-CrayGNU-19.09.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.7.0-OSMesa-CrayGNU-19.09.eb, jenkins-builds/7.0.UP01-19.09-mc
Testing also the multi-threading build...
=> [dom-mc] Mesa version of ParaView for Dom. 

easybuild/module/EasyBuild-custom/cscs, jenkins-builds/production.sh
Change the metadata file for dom on production.sh in order for jenkins to install the new PE
=> [dom-gpu] Production metadata dom

easybuild/cray_external_modules_metadata-19.10.cfg
Fix cudatoolkit version in 19.10 metadata
=> [dom] Fix cudatoolkit version

jenkins-builds/production.sh
* Also remove loading of additional cray modules.
=> [daint dom kesch] Add cray-mpich after module purge in production.sh

easybuild/easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayCCE-18.08.eb, easybuild/easyconfigs/e/ecCodes/ecCodes-2.12.2-CrayGNU-18.08.eb
=> [daint] updated ecCodes to v2.12.2

jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-mc
Fixes [MAINT-158](https://jira.cscs.ch/browse/MAINT-158).
=> [dom] Fix default CMake version for CLE7

easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.4-CrayGNU-18.08-python3.eb
Add ipyparallel 6.2.4 to Daint
=> [daint] ipyparallel-6.2.4-CrayGNU-18.08-python3.eb

easybuild/easyblocks/pycuda.py, easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.08-cuda-10.1-cordex-double.eb, easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.08-cuda-10.1-crclim-double.eb, easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.09-cordex-double.eb, easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.09-crclim-double.eb, easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.09-cuda-10.1-cordex-double.eb, easybuild/easyconfigs/c/COSMO_pompa/COSMO_pompa-31d7227-CrayCCE-19.09-cuda-10.1-crclim-double.eb, easybuild/easyconfigs/c/COSMO_pompa/patch_COSMO_dom_cray_cpu.patch, easybuild/easyconfigs/c/COSMO_pompa/patch_COSMO_dom_cray_gpu.patch, easybuild/easyconfigs/c/COSMO_pompa/patch_COSMO_dom_cray_gpu_CrayCCE-19.08.patch, easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-19.08-cuda-10.1-cordex-double.eb, easybuild/easyconfigs/d/Dycore/Dycore-551f6b4-CrayGNU-19.08-cuda-10.1-crclim-double.eb, easybuild/easyconfigs/s/STELLA/STELLA-4a5f9c5-CrayGNU-19.08-cordex-double.eb, easybuild/easyconfigs/s/STELLA/STELLA-4a5f9c5-CrayGNU-19.08-crclim-double.eb
Reverts eth-cscs/production#1355
Waiting for @kraushm...
=> Revert "[dom-gpu] Modify Cosmo recipes to point to correct netCDF"

easybuild/easyconfigs/h/h5py/h5py-2.8.0-CrayGNU-19.10-python2-parallel.eb, easybuild/easyconfigs/h/h5py/h5py-2.8.0-CrayGNU-19.10-python2-serial.eb, easybuild/easyconfigs/h/h5py/h5py-2.8.0-CrayGNU-19.10-python3-parallel.eb, easybuild/easyconfigs/h/h5py/h5py-2.8.0-CrayGNU-19.10-python3-serial.eb
This fix is based on the ticket https://webrt.cscs.ch/Ticket/Display.html?id=37499
=> [daint] fixing HDF5 version used for python setup command

easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-19.10.eb
Libxc-4.3.4 with CrayIntel-19.10
=> [daint dom] libxc-4.3.4 with CrayIntel-19.10

easybuild/easyconfigs/g/GROMACS/GROMACS-2018.6-CrayGNU-19.10-PLUMED-2.5.1-cuda-10.1.eb
Based on the request in https://webrt.cscs.ch/Ticket/Display.html?id=37537
=> [daint-gpu] GROMACS/2018.6_PLUMED_2.5.1 

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc2-CrayIntel-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.1-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.1-CrayIntel-19.10-cuda-10.1.eb
- GNU/Intel
- q-e SIRIUS (only Intel)
=> [daint-gpu] (q-e) SIRIUS v6.4.1 

easybuild/easyconfigs/g/GROMACS/GROMACS-2018.4-CrayGNU-19.10-PLUMED-2.5.0-cuda-10.1.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.0-CrayGNU-19.10.eb
Requested in ticket https://webrt.cscs.ch/Ticket/Display.html?id=37518
=> [daint-gpu] GROMACS-2018.4 + PLUMED 2.5.0 TC GNU 19.10

easybuild/easyconfigs/a/absl/absl-0.2.2-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/b/Bazel/Bazel-0.11.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/b/backports.weakref/backports.weakref-1.0.post1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/d/DeePMD/DeePMD-0.10.2-CrayGNU-19.10.eb, easybuild/easyconfigs/d/dask/dask-0.18.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/t/TensorFlow/TensorFlow-1.7.0-CrayGNU-19.10-cc-python3.eb, easybuild/easyconfigs/w/Werkzeug/Werkzeug-0.14.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/w/wheel/wheel-0.31.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/x/xdrfile/xdrfile-1.1.4-CrayGNU-19.10.eb
Based on ticket https://webrt.cscs.ch/Ticket/Display.html?id=37633
=> [daint] DeePMD-0.10.2 CrayGNU 19.10

easybuild/easyconfigs/c/COSMO_pompa/patch_COSMO_daint_cray_gpu_CrayCCE-19.08.patch
Addition of a patch for Marie-Estelle (supposed to be for the current version of the crclim branch)
=> [daint-gpu] COSMO-POMPA-crclim patch update

easybuild/easyconfigs/s/SLEPc/SLEPc-3.9.2-CrayIntel-19.10-complex.eb
William adapted the user recipe for the new version of the operating system.
=> [daint] SLEPc with version workaround from William

easybuild/easyconfigs/g/GROMACS/GROMACS-2018.4-CrayGNU-19.10-PLUMED-2.5.0-cuda-10.1.eb
Based on #1426
Request based on ticket https://webrt.cscs.ch/Ticket/Display.html?id=37518
=> [daint] GROMACS PLUMED Add configopts to account for CPU+GPU

jenkins/JenkinsfileProductionEB, jenkins/Machines.groovy, jenkins/README.md, login/daint-gpu, login/daint-mc, test_naming_scheme/tools/module_naming_scheme/lowercase_module_naming_scheme.py
The pull request will update the login paths to match the new modules on the CLE7 operating system.
=> [daint-gpu] Update Piz Daint login

easybuild/easyconfigs/c/CP2K/CP2K-6.1-CrayGNU-19.10-cuda-10.1-pat-7.1.1.eb
`CP2K` recipe with the latest toolchain `19.10` and `perftools-lite`
=> [daint-gpu] CP2K instrumented with perftools-lite 7.1.1

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.4-rc3-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.2-CrayGNU-19.10-cuda-10.1.eb
- update SIRIUS 6.4.2 CrayGNU
- add QuantumESPRESSO-SIRIUS 6.4-rc3 for CrayGNU
=> [daint-gpu] SIRIUS 6.4.2/QE-SIRIUS 6.4-rc for CrayGNU 

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6.0-CrayGNU-19.10.eb, easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-6.0-20190620, easybuild/easyconfigs/s/SCOTCH/SCOTCH-6.0.7-CrayGNU-19.10.eb
Build to support https://webrt.cscs.ch/Ticket/Display.html?id=37504
=> [daint-mc] OpenFOAM 6.0 + dependency SCOTCH

easybuild/easyconfigs/n/nvidia-nsight-systems/nvidia-nsight-systems-2019.6.1.85.eb
Will fix [UES-640](https://jira.cscs.ch/browse/UES-640)
=> [dom-gpu] nvidia-nsight-systems/2019.6

easybuild/easyconfigs/d/ddt/ddt-20.0-Suse-15.0.eb, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-mc
=> [dom] ddt/20

easybuild/easyconfigs/l/LAMMPS/LAMMPS-22Aug2018-CrayGNU-19.10-deepmd-0.10.2.eb
Easyconfig updated for ticket #37821
=> [daint-mc] Easyconfig for LAMMPS with deepmd for CrayGNU 19.10 created

easybuild/easyblocks/darshan.py, easybuild/easyconfigs/d/Darshan/Darshan-3.1.8-CrayGNU-19.10.eb, easybuild/easyconfigs/d/Darshan/darshan-pkgconfig-fix.patch
In order to instrument `helloworld_mpi.c ` with Darshan, please just do
```
module load Darshan
cc helloworld_mpi.c -o helloworld_mpi
```
When running 
```
module load Darshan
export DARSHAN_LOGFILE=$PWD/darshan.log
srun ./helloworld_mpi
```
This should generate the `darshan.log` file which contains the i/o data
=> [daint-gpu] Add Darshan

easybuild/easyblocks/xalt.py, easybuild/easyconfigs/x/xalt/Daint_config.py, easybuild/easyconfigs/x/xalt/xalt-2.7.24.eb, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/production.sh
One cannot have xalt loaded before installing xalt...
=> [dom-gpu] Add support for XALT installation in production.sh

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-19.10-batchspawner.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1b-CrayGNU-19.10.eb
With the coming update of batchspawner to the asyncio version there is a new dependency of some compute-side batchspawner components.
=> [dom] Create jupyterlab-1.1.1b-CrayGNU-19.10.eb

easybuild/easyconfigs/b/Buildah/Buildah-1.11.5.eb, easybuild/easyconfigs/g/go/go-1.13.4.linux-amd64.eb, easybuild/easyconfigs/r/runc/runc-1.0.0-rc9.eb
This only works on a particular node on Dom for the moment (CI will most likely fail)
=> [dom] Create Buildah recipe

easybuild/easyconfigs/a/advisor/advisor_2020.eb, easybuild/easyconfigs/a/advisor/advisor_2020.patch, easybuild/easyconfigs/i/inspector/inspector_2020.eb, easybuild/easyconfigs/i/inspector/inspector_2020.patch, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-mc
Will install latest tools versions
- https://software.intel.com/sites/default/files/managed/b4/9e/Intel_Inspector_2020_release_notes.pdf
- https://software.intel.com/sites/default/files/managed/f2/25/Intel_Advisor_2020_release_notes.pdf
=> [dom] intel/2020

easybuild/easyconfigs/v/vtune_profiler/vtune_profiler_2020.eb, easybuild/easyconfigs/v/vtune_profiler/vtune_profiler_2020.patch, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-mc
=> [dom] vtune/2020

jenkins-builds/7.0.UP01-19.10-mc
typo - missing .eb extension. Not sure why this didn't flag any errors on the testing.
=> [daint,dom] Update 7.0.UP01-19.10-mc

jenkins-builds/7.0.UP01-19.10-gpu-dom, jenkins-builds/7.0.UP01-19.10-mc-dom
Added the new batchspawner-enabled jupyterlab to the production dom list.
=> [dom] Update 7.0.UP01-19.10-gpu-dom

easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.3-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.3-CrayIntel-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayGNU-19.10-cuda-10.1-mkl.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayIntel-19.10-cuda-10.1.eb
- added SIRIUS 6.4.3 (GNU and Intel)
- added SpFFT 0.9.10 (GNU and Intel)
=> [daint-gpu] SIRIUS 6.4.3, SpFFT 0.9.10 

jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-gpu-dom, jenkins-builds/7.0.UP01-19.10-mc-dom
Buildah-1.13.1.eb should be the only difference between the production lists.
=> [dom] Update dom production list to be in sync with daint

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc1-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc1-CrayIntel-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.4-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.4.4-CrayIntel-19.10-cuda-10.1.eb
=> [daint-gpu] SIRIUS 6.4.4 / QE-SIRIUS 6.5-rc1

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.4-CrayGNU-19.10-batchspawner.eb
Testing the compatibility of "JupyterLab GPU Dashboards" from the RAPIS folks at https://github.com/rapidsai/jupyterlab-nvdashboard.
=> [dom] Create jupyterlab-1.2.4-CrayGNU-19.10-batchspawner.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.4-CrayGNU-19.10-cuda-10.1-batchspawner.eb
This is the gpu partition recipe.
=> [daint-gpu,dom-gpu] Add IJulia to jupyterlab-1.2.4 (gpu recipe)

easybuild/easyconfigs/o/otf2_cli_profile/otf2_cli_profile-4ef9d3f-CrayGNU-19.10.eb, easybuild/easyconfigs/o/otf2_cli_profile/otf2_cli_profile-4ef9d3f.patch, easybuild/easyconfigs/r/rapidjson/rapidjson-a895ce1.eb, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-gpu-dom, jenkins-builds/7.0.UP01-19.10-mc, jenkins-builds/7.0.UP01-19.10-mc-dom
=> [dom] otf2_cli_profile

easybuild/easyconfigs/m/mdl/mdl-317500.2554-CrayGNU-19.10.eb, easybuild/easyconfigs/v/VisRTX/VisRTX-0.1.6-CrayGNU-19.10.eb
ParaView 5.8 new release will need these updates
=> [daint-gpu, dom-gpu] minor tweaks for shared lib loading for ParaView

easybuild/easyconfigs/m/mdl/mdl-317500.2554-CrayGNU-19.10.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-OSMesa-CrayGNU-19.10.eb, easybuild/easyconfigs/v/VisRTX/VisRTX-0.1.6-CrayGNU-19.10.eb
== COMPLETED: Installation ended successfully (took 21 min 45 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.8.0-CrayGNU-19.10-OSMesa/easybuild/easybuild-ParaView-5.8.0-20200218.082254.log
=> [daint-mc, dom-mc] New official release of ParaView v5.8 for the mc partition

easybuild/easyconfigs/m/Mako/Mako-1.1.2-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/p/PyFR/PyFR-1.9.0-CrayGNU-19.10-python3.eb
Fix for https://webrt.cscs.ch/Ticket/Display.html?id=38491
=> [dom-gpu] pyfr

easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-19.10.eb
I provide the recipe for the latest ELPA release with CrayIntel.
=> [daint-gpu] Latest ELPA release with CrayIntel

easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10.eb
LAMMPS 3 March 2020 release cpu version
=> [dom-mc,daint-mc] Create LAMMPS-03Mar2020-CrayGNU-19.10.eb

easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1.eb
GPU enabled LAMMPS 3 March 2020 version
=> [dom-gpu,daint-gpu] Create LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1.eb

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc3-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc3-CrayIntel-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.1-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.1-CrayIntel-19.10-cuda-10.1.eb
add SIRIUS v6.5.1 for GNU/Intel
=> [dom-gpu] SIRIUS 6.5.1

easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayGNU-19.10.eb, easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayIntel-19.10.eb
- sha256sums for libxc from tddft.org
- use https for download
=> [daint-gpu] libxc: add checksums / use https

easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1-pat-7.1.1.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1-pat7.1.1.eb
LAMMPS 2 March 2020 with cuda and pat.
=> [dom-gpu] LAMMPS-03Mar2020-CrayGNU-19.10-cuda-10.1-pat-7.1.1.eb

easybuild/easyconfigs/a/ack/ack-v3.3.1.eb, easybuild/easyconfigs/b/bash/bash-5.0.eb, easybuild/easyconfigs/c/colordiff/colordiff-1.0.18.eb, easybuild/easyconfigs/c/colordiff/colordiff-1.0.18.patch, easybuild/easyconfigs/c/cpu-features/cpu-features-v0.4.1.eb, easybuild/easyconfigs/c/cpu_features/cpu_features-v0.4.1.eb, easybuild/easyconfigs/e/elfutils/elfutils-0.178.eb, easybuild/easyconfigs/f/fzf-bin/fzf-bin-0.21.0-linux_amd64.eb, easybuild/easyconfigs/g/global/global-6.6.4.eb, easybuild/easyconfigs/h/htop/htop-2.2.0.eb, easybuild/easyconfigs/k/kcov/kcov-38.eb, easybuild/easyconfigs/m/MPI-Bash/MPI-Bash-0b396b6-CrayCCE-19.10.eb, easybuild/easyconfigs/m/MPI-Bash/MPI-Bash-0b396b6-CrayGNU-19.10.eb, easybuild/easyconfigs/m/multitail/multitail-6.5.0.eb, easybuild/easyconfigs/m/multitime/multitime-1.4.eb, easybuild/easyconfigs/n/numdiff/numdiff-5.9.0.eb
=> [dom] tools

easybuild/easyconfigs/c/cgdb/cgdb-v0.7.1.eb, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-mc
=> [dom] cgdb

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.2-CrayGNU-19.10-cuda-10.1.eb
=> [daint-gpu] QE-SIRIUS 6.5.2 for CrayGNU

jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-gpu-dom, jenkins-builds/7.0.UP01-19.10-mc, jenkins-builds/7.0.UP01-19.10-mc-dom
GPU version 4.3 -> daint-gpu
CPU version 4.3 -> daint-mc
=> [dom-gpu ] cpmd 4.3 to jenkins

jenkins/Machines.groovy
Restore all systems in Machines.groovy
=> [TSAtds] Fix Machines

easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10-python3.eb, easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayIntel-19.10.eb, easybuild/easyconfigs/b/Boost/Boost-1.72.0-CrayIntel-19.10.eb
Replace `SOURCEFORGE` with the official repository to get `.bz2` format (fix for #1569 and #1570).
=> [daint-gpu] Fix Boost download link

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.eb, easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10.psmp
EasyBuild recipe for the latest stable release of CP2K (multicore build only) with CrayIntel
=> [daint-mc] CP2K 7.1 multicore with CrayIntel

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.eb, easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayIntel-19.10-cuda-10.1.psmp
Minor change with a fix: adding MKL include and link line options and unloading `cray-libsci` before building.
=> [daint-gpu] CP2K 7.1 gpu with CrayIntel

README.md
I have checked the file `README.md` and fixed some outdated content.
=> [daint-gpu] Fix outdated content in README

easybuild/easyblocks/boostcray.py, easybuild/easyconfigs/b/Boost/Boost-1.67.0-CrayGNU-19.08.eb
Cosmo no longer builds after PR #1511, this should fix it.
=> [daint-gpu] revert deleted boostcray easyblock (required for older versions of boost)

easybuild/easyconfigs/n/nvidia-nsight-systems/nvidia-nsight-systems-2020.2.1.71.eb, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-gpu-dom
Will fix [UES-855](https://jira.cscs.ch/browse/UES-855)
=> [dom-gpu] nsys/2020.2

easybuild/easyconfigs/l/libxsmm/libxsmm-1.14-CrayGNU-19.10.eb, easybuild/easyconfigs/l/libxsmm/libxsmm-1.14-CrayIntel-19.10.eb, easybuild/easyconfigs/l/libxsmm/libxsmm-1.15-CrayGNU-19.10.eb, easybuild/easyconfigs/l/libxsmm/libxsmm-1.15-CrayIntel-19.10.eb
The library `libxsmm` is a dependency of `CP2K` (see #1599).
=> [dom-gpu] libxsmm easyconfig files

easybuild/easyconfigs/p/ParaView/ParaView-5.7.0-EGL-CrayGNU-19.10.eb
one more missing ParaView recipe for Jupyterlab
=> [daint-gpu] more updates to run on Jupyer-lab

easybuild/easyconfigs/a/archspec/archspec-0.1.0-CrayGNU-19.10-python3.eb
=> [dom] archspec

easybuild/easyconfigs/r/rstudio/rstudio-1.1.463.eb, jenkins-builds/MCH-RH7.6-19.04, jenkins-builds/MCH-RH7.7-19.04
Rstudio v1.2.1335 exhibits issue on Red Hat - see https://webrt.cscs.ch/Ticket/Display.html?id=38532, v1.1.463 does not show the issue.
=> [tsa, TSAtds] Downgrade rstudio version to 1.1.463

easybuild/easyconfigs/v/VTK/VTK-9.0.0-EGL-CrayGNU-19.10-python3.eb, jenkins-builds/7.0.UP01-19.10-gpu
== COMPLETED: Installation ended successfully (took 13 min 44 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VTK/9.0.0-EGL-CrayGNU-19.10/easybuild/easybuild-VTK-9.0.0-EGL-20200505.093350.log
=> [daint-gpu] A new major update of VTK

easybuild/easyconfigs/a/adept-utils/adept-utils-606ebad-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/c/callpath/callpath-0d234e1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/d/dyninst/dyninst-10.1.0-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/g/GObject-Introspection/GObject-Introspection-1.64.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/g/graphlib/graphlib-v3.0.0-CrayGNU-19.10.eb, easybuild/easyconfigs/l/launchmon/launchmon-v1.0.2-CrayGNU-19.10.eb, easybuild/easyconfigs/l/launchmon/launchmon-v1.0.2.patch, easybuild/easyconfigs/l/llnl-hires-timers/llnl-hires-timers-e6d8308-CrayGNU-19.10.eb, easybuild/easyconfigs/m/Meson/Meson-0.53.2-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/m/mrnet/mrnet-7375ba5-CrayGNU-19.10.eb, easybuild/easyconfigs/n/Ninja/Ninja-1.10.0-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.44.eb, easybuild/easyconfigs/p/PyCairo/PyCairo-1.19.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/p/PyGObject/PyGObject-3.36.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/s/SWIG/SWIG-4.0.1-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/s/stat/stat-4.0.2-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/s/stat/stat-4.0.2.patch, easybuild/easyconfigs/s/stat/stat.dot, easybuild/easyconfigs/x/xdot/xdot-1.1-CrayGNU-19.10-python3.eb
will fix [UES-624](https://jira.cscs.ch/browse/UES-624)
=> [dom] add python3 stat

easybuild/easyblocks/juliapackage.py, easybuild/easyconfigs/j/Julia/Julia-1.4.1-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/j/Julia/Julia-1.4.1-CrayGNU-19.10.eb
This PR adds support to the MPI package in the `juliapackages.py` file.
=> [dom-gpu] Add Julia 1.4.1 with MPI and CUDA packages

easybuild/easyconfigs/j/Julia/Julia-1.4.1-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/j/Julia/Julia-1.4.1-CrayGNU-19.10.eb
Remove checksums from extensions as do not seem to work (although injected by EasyBuild).
=> [dom] Julia-1.4.1- remove checksums from extensions

easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-19.10-python2.eb, easybuild/easyconfigs/b/Boost/Boost-1.70.0-CrayGNU-19.10-python3.eb
Since #1616 is getting too big, I am splitting the PR into smaller ones.
=> [dom-gpu, daint-gpu] Eb templates in boost

easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1-APEX.eb, easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1-nonetworking.eb, easybuild/easyconfigs/h/HPX/HPX-1.4.0-CrayGNU-19.10-cuda-10.1.eb
Since #1616 is getting too big, I am splitting the PR into smaller ones.
=> [dom-gpu, daint-gpu] use eb templates in HPX

easybuild/cray_external_modules_metadata-19.10.cfg, easybuild/easyconfigs/d/dask/dask-2.2.0-CrayGNU-19.10-python3.eb, easybuild/easyconfigs/n/numpy/numpy-1.17.2-CrayGNU-19.10.eb, easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.15.6-CrayGNU-19.10.eb, easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.15.7-CrayGNU-19.10.eb, easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.5.6-CrayGNU-19.10.eb, easybuild/easyconfigs/p/PyExtensions/PyExtensions-3.6.5.7-CrayGNU-19.10.eb, easybuild/easyconfigs/p/PyExtensionsDS/PyExtensionsDS-3.6.5.7-CrayGNU-19.10.eb, easybuild/easyconfigs/s/SWIG/SWIG-3.0.12-CrayGNU-19.10-python3.eb
Since #1616 is getting too big, I am splitting the PR into smaller ones.
=> [dom-gpu, daint-gpu] Eb templates in dask, numpy, SWIG and PyExtensions

easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.4.1-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.4.1-CrayGNU-19.10.eb
This also need to be build with umask 022 as Julia itself.
=> [dom] Add JuliaExtensions-1.4.1

easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10-cuda-10.1.eb, easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-19.10-cuda-10.1.makefile.include, jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-gpu-dom, jenkins-builds/7.0.UP01-19.10-mc, jenkins-builds/7.0.UP01-19.10-mc-dom, jenkins-builds/production.sh
The new modules of `VASP 6.1.0` will be installed on Dom and Piz Daint as non default.
=> [daint-gpu] Add VASP 6.1.0 in production

easybuild/module/EasyBuild-custom/cscs
Making the setting of the RH7.7 test nodes the new default.
=> [TSAtds] Change modules tool for RH7.7

jenkins-builds/MCH-RH7.7-19.04
=> [tsa] Update production list

jenkins/JenkinsfileProductionEB
The path will become unique enough to prevent the issue reported by @kraushm in #1684.
=> [tsa] Adding BUILD_ID to the build path in ProductionEB

easybuild/easyconfigs/n/nvhpc/nvhpc-2020_205-cuda-10.1.eb, jenkins-builds/7.0.UP01-19.10-gpu-dom
=> [dom-gpu] NVIDIA HPC SDK

easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-foss-2019b.eb, easybuild/easyconfigs/p/PyExtensions/PyExtensions-2.7.16-fosscuda-2019b.eb
The Python module `pyparsing` was listed twice.
=> [tsa] Remove extension duplicate

easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.4-CrayGNU-19.10-python3.eb
minor: eb templates 
ipyparallel uses -batchspawner as requested
=> [dom, daint] eb py templates for ipyparallel

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-19.10-PLUMED-2.6.0-cuda-10.1.eb, easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-PLUMED-2.6.0-cuda-10.1.psmp, easybuild/easyconfigs/p/PLUMED/PLUMED-2.6.0-CrayGNU-19.10.eb
I provide an updated EasyBuild recipe for the latest stable release of CP2K with the PLUMEd plugin.
=> [daint-gpu] CP2K 7.1 with PLUMED 2.6.0

easybuild/easyconfigs/o/oq-engine/oq-engine-3.2.0-CrayGNU-19.10.eb
hopefully this is the last one in prod
=> [dom-mc, daint-mc] oq-engine: eb templates and pyext3

jenkins-builds/7.0.UP01-19.10-gpu, jenkins-builds/7.0.UP01-19.10-gpu-dom
Fix for https://webrt.cscs.ch/Ticket/Display.html?id=39664
=> [dom-gpu, daint-gpu] removing olderunsupported nsight versions

easybuild/easyconfigs/b/binutils/binutils-2.32-GCCcore-8.3.0.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-GCCcore-8.3.0.eb, easybuild/easyconfigs/g/GCC/GCC-8.3.0.eb, easybuild/easyconfigs/g/GCCcore/GCCcore-8.3.0.eb, easybuild/easyconfigs/h/HDF5/HDF5-1.10.5-PGI-20.4-GCC-8.3.0.eb, easybuild/easyconfigs/h/help2man/help2man-1.47.8-GCCcore-8.3.0.eb, easybuild/easyconfigs/m/M4/M4-1.4.18-GCCcore-8.3.0.eb, easybuild/easyconfigs/n/netCDF-C++/netCDF-C++-4.3.0-PGI-20.4-GCC-8.3.0.eb, easybuild/easyconfigs/n/netCDF-Fortran/netCDF-Fortran-4.4.5-PGI-20.4-GCC-8.3.0.eb, easybuild/easyconfigs/n/netCDF/netCDF-4.7.0-PGI-20.4-GCC-8.3.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-20.4-GCC-8.3.0-cuda-10.1.eb, easybuild/easyconfigs/p/PGI/PGI-20.4-GCC-8.3.0.eb, easybuild/easyconfigs/u/UCX/UCX-1.6.1-GCC-8.3.0.eb, easybuild/easyconfigs/z/zlib/zlib-1.2.11-GCCcore-8.3.0.eb
New PE based on most recent version of PGI. (see https://jira.cscs.ch/browse/LRIII-115)
In addition, all easyconfig files for this PE are now added to this repository.
=> [tsa] PE modules based on PGI 20.4

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-GCC-8.3.0.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-20.4-GCC-8.3.0-cuda-10.1.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-PGI-20.4-GCC-8.3.0-nocuda.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.0.2-gcccuda-2019b-cuda-10.1.eb, easybuild/easyconfigs/p/PGI/PGI-20.4-GCC-8.3.0-nocuda.eb, easybuild/easyconfigs/u/UCX/UCX-1.8.1-GCC-8.3.0-cuda-10.1.eb, easybuild/easyconfigs/u/UCX/UCX-1.8.1-GCC-8.3.0.eb
This UCX version showed performance improvement for some applications.
=> [tsa] Add updated easyconfigs for UCX 1.8.1 + OpenMPI

easybuild/easyconfigs/o/oidn/oidn-1.2.2-CrayGNU-19.10.eb, easybuild/easyconfigs/o/ospray/ospray-2.2.0-CrayGNU-19.10.eb
== COMPLETED: Installation ended successfully (took 5 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/oidn/1.2.2-CrayGNU-19.10/easybuild/easybuild-oidn-1.2.2-20200723.092936.log
== COMPLETED: Installation ended successfully (took 37 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ospray/2.2.0-CrayGNU-19.10/easybuild/easybuild-ospray-2.2.0-20200723.093031.log
=> [daint-mc,daint-gpu] new libraries for Intel raytracing

easybuild/cray_external_modules_metadata-20.06.cfg, easybuild/module/EasyBuild-custom/cscs
Fix modules tool with TMOD 4 and Cudatoolkit version
=> [dom-gpu] Set modules tool and metadata

easybuild/module/EasyBuild-custom/cscs
I think we should wait for Matteo to revert back on dom101.
=> [dom-gpu] Revert Dom back to modules 3.2

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-19.10-batchspawner.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-19.10-cuda-10.1-batchspawner.eb
Remake of PR 1738, which will be deleted. Was reviewed in 1738.
=> JupyterLab 1.2.16

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.1.1-CrayGNU-20.06-batchspawner.eb
This passed.
"Could not update commit status of the Pull Request on GitHub.
org.kohsuke.github.HttpException: {"message":"API rate limit exceeded for user ID 21236385"
=> [dom] jupyterlab-1.1.1-CrayGNU-20.06-batchspawner.eb

jenkins-builds/7.0.UP02-20.06-gpu-dom, jenkins-builds/7.0.UP02-20.06-mc-dom
Removing old versions of CP2K LAMMPS and VASP as agreed for the update.
=> [dom-gpu] Remove old versions of applications

easybuild/easyconfigs/c/CP2K/CP2K-7.1-CrayGNU-cuda.psmp
Fix CP2K build in ProductionEB
=> [dom-gpu] Add CP2K arch file without CUDA version

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-20.06-cuda.eb
Recipe for QuantumESPRESSO with a fix for the PGI issue with `cdt/20.06 `.
=> [dom-gpu] QuantumESPRESSO 6.5a1 with CrayPGI 

easybuild/easyconfigs/b/Bison/Bison-3.3.2-CrayIntel-20.06.eb, easybuild/easyconfigs/b/binutils/binutils-2.32-CrayIntel-20.06.eb, easybuild/easyconfigs/f/flex/flex-2.6.4-CrayIntel-20.06.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-20.06.eb
The eb procedure seems only to work if PrgEnv-intel is loaded before eb is executed, otherwise with PrgEnv-cray it hangs?
=> [dom] Plumed with CrayIntel

easybuild/cray_external_modules_metadata-20.06.cfg, easybuild/easyconfigs/e/ELPA/ELPA-2019.11.001-CrayIntel-20.06.eb, easybuild/easyconfigs/m/magma/magma-2.5.3-CrayIntel-20.06-cuda.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc4-CrayIntel-20.06-cuda.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-6.5.3-CrayIntel-20.06-cuda.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.10-CrayIntel-20.06-cuda.eb
The pull requests provides the recipe of `QuantumESPRESSO-SIRIUS` with the missing dependencies.
=> [dom-gpu] QuantumESPRESSO-SIRIUS and dependencies with cdt/20.06

easybuild/easyconfigs/j/jupyter-utils/jupyter-utils-0.1.eb, jenkins-builds/7.0.UP02-20.06-gpu-dom, jenkins-builds/7.0.UP02-20.06-mc-dom
The recipe uses the Python templates available in EasyBuild 4.2.2.
=> [dom] Update Jupyter utils recipe and production files

easybuild/easyblocks/juliapackage.py, easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-19.10-cuda-10.1.eb, easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-19.10.eb
Add MPI environment variables to facilitate correct custom MPI build for user if desired.
=> [daint-gpu] Improve Julia 1.5.0 for PE 19.10

easybuild/easyconfigs/i/ipyparallel/ipyparallel-6.2.4-CrayGNU-20.06-python3.eb, jenkins-builds/7.0.UP02-20.06-gpu-dom, jenkins-builds/7.0.UP02-20.06-mc-dom
The new recipe will use the updated toolchain and Python templates.
=> [dom] Updated ipyparallel recipe for cdt/20.06 and production lists 

easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-CrayGNU-20.06-EGL-python3.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.8.0-EGL-CrayGNU-20.06.eb, jenkins-builds/7.0.UP02-20.06-gpu-dom
The recipe is provided with the updated dependencies and Python templates of EasyBuild 4.2.2.
=> [dom-gpu] Update Paraview 5.8.0 EGL recipe and production list 

easybuild/easyconfigs/j/Julia/Julia-1.5.0-CrayGNU-20.06.eb, easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.5.0-CrayGNU-20.06.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.06-batchspawner.eb
This requires JuliaExtensions/1.4.2-CrayGNU-20.06 (help wanted, Sam)
=> [dom-mc] jupyterlab-1.2.16-CrayGNU-20.06-batchspawner.eb with Julia[Extensions]

easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-cuda.eb, easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-cuda.makefile.include
Recipe of VASP6 with cdt 20.08.
=> [dom-gpu] VASP6 with cdt 20.08

jenkins-builds/7.0.UP02-20.08-dom-gpu
Add the newly created recipe to the gpu production list.
=> [dom-gpu] Add VASP6 GPU in production

easybuild/easyconfigs/o/OSU-Micro-Benchmarks/OSU-Micro-Benchmarks-5.6.3-CrayGNU-20.08.eb
I have used the OSU microbenchmarks on Dom for basic testing of the MPI library: they might be useful sometimes.
=> [dom-mc] OSU MicroBenchmarks

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-19.10-cuda-10.1-batchspawner.eb
change a comment to force rebuild
=> [daint-gpu] jupyterlab-1.2.16-CrayGNU-19.10-cuda-10.1-batchspawner.eb

easybuild/easyconfigs/a/adept-utils/adept-utils-606ebad-CrayGNU-20.08-python3.eb, easybuild/easyconfigs/a/adiak/adiak-0.2.1-CrayGNU-20.08.eb, easybuild/easyconfigs/c/Caliper/Caliper-2.4.0-CrayGNU-20.08.eb, easybuild/easyconfigs/c/cppcheck/cppcheck-1.90-CrayGNU-20.08.eb, easybuild/easyconfigs/d/dyninst/dyninst-10.2.0-CrayGNU-20.08-python3.eb, easybuild/easyconfigs/g/GOTCHA/GOTCHA-1.0.3-CrayGNU-20.08.eb, easybuild/easyconfigs/l/llnl-hires-timers/llnl-hires-timers-e6d8308-CrayGNU-20.08.eb, easybuild/easyconfigs/p/profvis/profvis-fe18867-CrayGNU-20.08.eb, easybuild/easyconfigs/u/Uncrustify/Uncrustify-0.70.1-CrayGNU-20.08.eb
will update the jenkins list afterwards
=> [dom] caliper

easybuild/easyconfigs/c/CMake/CMake-3.18.1.eb
=> [daint,dom] Create CMake-3.18.1.eb

jenkins-builds/7.0.UP02-20.08-dom-gpu, jenkins-builds/7.0.UP02-20.08-dom-mc
=> [dom] update dom production lists for jupyterlab 2.0.2

easybuild/easyconfigs/m/mdl/mdl-317500.2554-CrayGNU-19.10.eb, easybuild/easyconfigs/m/mdl/mdl-317500.2554-CrayGNU-20.08.eb
=> [daint-gpu,dom-gpu] provided the correct LD_LIBRARY_PATH 

easybuild/easyconfigs/v/Visit/Visit-3.1.2-CrayGNU-20.08.eb, jenkins-builds/7.0.UP02-20.08-dom-mc
== COMPLETED: Installation ended successfully (took 49 min 51 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/Visit/3.1.2-CrayGNU-20.08/easybuild/easybuild-Visit-3.1.2-20200904.215355.log
=> [dom-mc] VisIt 3.1.2 for CDT-20.08

easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-20.08-pat-20.08.0.eb, easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-20.08-pat.eb
This is CPMD with the most recent CrayPAT version.
=> [dom-gpu] cpmd + pat-20.08.0

easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.2-CrayGNU-20.08.eb, easybuild/easyconfigs/n/NASM/NASM-2.14.02-CrayGNU-20.08.eb, jenkins-builds/7.0.UP02-20.08-dom-gpu, jenkins-builds/7.0.UP02-20.08-dom-mc
== COMPLETED: Installation ended successfully (took 18 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/NASM/2.14.02-CrayGNU-20.08/easybuild/easybuild-NASM-2.14.02-20200909.075703.log
== COMPLETED: Installation ended successfully (took 1 min 20 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/FFmpeg/4.2.2-CrayGNU-20.08/easybuild/easybuild-FFmpeg-4.2.2-20200909.073913.log
=> [dom] FFmpeg for matplotlib animation or stand-alone video encoding

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6.0-CrayGNU-20.08.eb, easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-6.0-20190620
Modify to use CRAY-TPSL instead of SCOTCH
=> [daint-mc] Adapt OpenFOAM 6.0 to CrayGNU 20.08

jenkins/Machines.groovy, login/cdt
The pull request aims at fixing `Machines.groovy` and the link to the `cdt` custom modulefile.
=> [daint-gpu] Fix Machines.groovy and link to cdt custom modulefile

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5a1-CrayPGI-20.08-cuda-pat.eb
EasyBuild recipe of QuantumESPRESSO CUDA with `perftools-lite` (default from `cdt/20.08`).
=> [daint-gpu] QuantumESPRESSO CUDA recipe with perftools-lite

easybuild/easyconfigs/v/VASP/VASP-6.1.0-CrayIntel-20.08-cuda-pat.eb
EasyBuild recipe of VASP CUDA with perftools-lite (default from `cdt/20.08`).
=> [daint-gpu] VASP CUDA recipe with perftools-lite

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.5-CrayIntel-20.08-pat.eb
EasyBuild recipe of QuantumESPRESSO with `perftools-lite` (default from `cdt/20.08`).
=> [daint-mc] QuantumESPRESSO recipe with perftools-lite

easybuild/easyconfigs/l/libxc/libxc-4.3.4-CrayPGI-20.08.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.08-cuda.eb
I provide the recipe to build the latest release of QuantumESPRESSO (GPU): I have linked HDF5 and libxc: I have tested pw.x with AUSURF112 and the performance looks faster with respect to the previous release.
=> [daint-gpu] QuantumESPRESSO 6.6a2 (GPU)

easybuild/easyconfigs/v/VTK/VTK-9.0.0-CrayGNU-20.08-EGL-python3.eb
this addresses https://webrt.cscs.ch/Ticket/Display.html?id=40226
=> [daint-gpu, dom-gpu] remove an old reference to a library

easybuild/easyconfigs/p/PDT/PDT-3.25.1.eb, easybuild/easyconfigs/s/Score-P/Score-P-6.0-CrayGNU-20.08-cuda.eb, easybuild/easyconfigs/s/Score-P/Score-P-6.0-CrayGNU-20.08.eb
Will fix https://jira.cscs.ch/browse/UES-1148
=> [dom-mc] PDT version bump

easybuild/easyconfigs/o/ovito/ovito-3.2.0-CrayGNU-20.08.eb
== COMPLETED: Installation ended successfully (took 30 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ovito/3.2.0-CrayGNU-20.08/easybuild/easybuild-ovito-3.2.0-20200925.121959.log
=> [daint-gpu,dom-gpu] new install of Ovito

easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-cuda-pat.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-03Mar20-CrayGNU-20.08-pat.eb
Adds the perftools-lite versions of the production LAMMPS software.
=> [daint] LAMMPS 20.08 with pat

jenkins-builds/7.0.UP02-20.08-daint-gpu, jenkins-builds/7.0.UP02-20.08-daint-mc, jenkins-builds/7.0.UP02-20.08-dom-gpu, jenkins-builds/7.0.UP02-20.08-dom-mc
=> [daint,dom] Add HPX 1.5.0 to production lists

easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayGNU-20.08.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.5.1-CrayIntel-20.08.eb
The web page https://www.plumed-code.org does not seem up to date any longer...
=> [daint] Update PLUMED-2.5.1 metadata

easybuild/easyconfigs/d/Darshan/Darshan-3.2.1-CrayGNU-20.08.eb
Enables HDF5 (cray-hdf5-parallel) instrumentation and setting of log-path by environment variable.
=> [daint, dom] Darshan with HDF5 support for PE 20.08

jenkins-builds/production.sh
Temporarily commenting out XALT reverse map due to a problem with Lmod
=> [daint] Comment out xalt reverse map

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-SIRIUS-6.5-rc6-CrayGNU-20.08-cuda.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.0.2-CrayGNU-20.08-cuda.eb, easybuild/easyconfigs/s/SPLA/SPLA-1.2.0-CrayGNU-20.08-cuda-mkl.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-0.9.13-CrayGNU-20.08-cuda-mkl.eb
this should fix the LDA+U tress tensor and forces on GPU
=> [daint-gpu] update QE+SIRIUS to 7.0.2 version

jenkins/Machines.groovy
I have removed Kesch from `Machines.groovy`.
=> [dom] Remove Kesch from machines list

easybuild/module/EasyBuild-custom/cscs, jenkins/Machines.groovy
I provide the updated files to deploy the software stack on Eiger using the Jenkins project https://jenkins.cscs.ch/job/EigerProductionEB
=> [dom] Update Machines list and EasyBuild modulefile

easybuild/easyconfigs/a/ANTLR/ANTLR-2.7.7-cpeGNU-20.10-python3.eb, easybuild/easyconfigs/j/JasPer/JasPer-2.0.14-cpeGNU-20.10.eb, easybuild/easyconfigs/n/NCO/NCO-4.9.5-cpeGNU-20.10.eb, jenkins-builds/1.3.1-20.10-eiger
I provide the recipe to build NCO on Eiger and I update the production list as well.
=> [eiger] NCO latest release with dependencies

easybuild/cray_external_modules_metadata-20.10.cfg, easybuild/easyconfigs/v/VASP/VASP-6.1.0-cpeGNU-20.10.eb, easybuild/easyconfigs/v/VASP/VASP-6.1.0-cpeGNU.makefile.include, easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-cpeGNU-20.10.eb, jenkins-builds/1.3.1-20.10-eiger
Adding VASP with dependencies on Eiger
=> [eiger] VASP 6.1.0 and dependencies 

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-20.10.eb, jenkins-builds/1.3.1-20.10-eiger
Adds JupyterLab (not working yet) to force build of nodejs, needed for testing purposes
=> [eiger] Update 1.3.1-20.10-eiger with Jupyter

easybuild/easyconfigs/n/nodejs/libuv.patch, easybuild/easyconfigs/n/nodejs/nodejs-14.15.0-cpeGNU-20.10.eb
This should fix your jupyter issues on eiger
=> [eiger] Added libuv patch for shasta DVS

easybuild/module/EasyBuild-custom/cscs
Set Lua module syntax on Eiger.
=> [eiger] Update EasyBuild-custom

jenkins/JenkinsfileUpdateEB
Append `$machineLabel` to `buildpath` to avoid conflicts between builds, add some `echo` statements to increase verbosity and don't copy `SYSTEM` recipes to the local branch before submitting the pull request on GitHub (they are not changed in the update).
=> [dom-gpu] Minor changes in UpdateEB

easybuild/easyconfigs/c/cpeCCE/cpeCCE-20.10.eb, easybuild/easyconfigs/c/cpeGNU/cpeGNU-20.10.eb
The two recipes are a workaround for Lmod on Eiger after the upgrade.
=> [eiger] Workaround for Lmod on Eiger

easybuild/easyconfigs/d/ddt/ddt-20.2-Suse-15.0.eb, jenkins-builds/7.0.UP02-20.08-daint-gpu, jenkins-builds/7.0.UP02-20.08-daint-mc, jenkins-builds/7.0.UP02-20.08-dom-gpu, jenkins-builds/7.0.UP02-20.08-dom-mc, jenkins-builds/7.0.UP02-20.10-dom-gpu, jenkins-builds/7.0.UP02-20.10-dom-mc
=> [dom] ddt/20.2

jenkins-builds/1.3.2-20.10-eiger
Add jupyter-utils to eiger production lists
=> [eiger] Update 1.3.2-20.10-eiger

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6-cpeGNU-20.10.eb
I provide a workaround for the recipe of `QuantumESPRESSO` on Eiger.
=> [eiger] Workaround for QE recipe

easybuild/easyconfigs/l/libreadline/libreadline-8.1-cpeGNU-20.10.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.2-cpeGNU-20.10.eb, easybuild/easyconfigs/p/PROJ/PROJ-7.2.0-cpeGNU-20.10.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.34.0-cpeGNU-20.10.eb
I provide the recipes for `PROJ` and dependencies as required by the custom `CDO` release (https://jira.cscs.ch/browse/SD-51043).
=> [eiger] PROJ and dependencies

easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.2.2-CrayGNU-20.10.eb
Recipe of `FFmpeg` with Cray PE 20.10 on Dom.
=> [dom] FFmpeg with 20.10

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.10-batchspawner-cuda.eb, easybuild/easyconfigs/n/nvhpc/nvhpc-2020_209-cuda-11.0.eb, easybuild/easyconfigs/p/pycuda/pycuda-2018.1.1-CrayGNU-20.10-python3-cuda.eb, jenkins-builds/7.0.UP02-20.10-dom-gpu
=> [dom-gpu] Add missing recipes

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.7.0-CrayIntel-20.10.eb, jenkins-builds/7.0.UP02-20.10-dom-mc
Add recipe of QuantumESPRESSO 6.7.0 and remove older releases in production file on Dom.
=> [dom-mc] QE 6.7.0 on Dom

jenkins-builds/7.0.UP02-20.10-dom-gpu
Remove temporarily Score-P cuda (see https://jira.cscs.ch/browse/UES-1324).
=> [dom-gpu] Remove temporarily Score-P cuda

jenkins/JenkinsfileUpdateEB
=> [dom] Fix if test in UpdateEB

easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU-20.08.eb, easybuild/easyconfigs/c/CP2K/CP2K-8.1-CrayGNU.psmp
I provide the recipes of the latest stable release of CP2K with Cray PE 20.08 on Piz Daint.
=> [daint-mc] CP2K 8.1 (multicore) recipe and configuration file

easybuild/easyconfigs/e/expat/expat-2.2.10.eb, easybuild/easyconfigs/u/UDUNITS/UDUNITS-2.2.28.eb
I provide the recipes of the latest stable release of `UDUNITS` and its dependency `expat`.
=> [dom daint eiger tsa] Updated UDUNITS and expat

easybuild/easyconfigs/o/oidn/oidn-1.2.4-CrayGNU-20.08.eb, easybuild/easyconfigs/o/ospray/ospray-2.4.0-CrayGNU-20.08.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.08-EGL-python3.eb, jenkins-builds/7.0.UP02-20.08-daint-gpu
== COMPLETED: Installation ended successfully (took 22 min 54 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.9.0-CrayGNU-20.08-EGL-python3/easybuild/easybuild-ParaView-5.9.0-20210125.140621.log
=> [daint-gpu] new, major upgrade of ParaView5.9 with new ospray/oidn

easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.08-OSMesa-python3.eb, jenkins-builds/7.0.UP02-20.08-daint-mc
== COMPLETED: Installation ended successfully (took 52 min 52 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.9.0-CrayGNU-20.08-OSMesa-python3/easybuild/easybuild-ParaView-5.9.0-20210125.121744.log
=> [daint-mc] ParaView5.9 for software rendering on daint-mc

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner.eb
JupyterHub 1.3 (and deps) to align with update of JupyterHub on VM.
=> [dom] Update jupyterlab-1.2.16-CrayGNU-20.11-batchspawner-cuda.eb

jenkins/util.groovy
Function to create a Jira SD ticket (based on `create_jsd_issue` created by @GiuseppLoRe at https://git.cscs.ch/misc/storage_scripts/-/blob/master/cscs_tools/cscs_tools.py).
=> [daint dom eiger tsa] Add createJiraSD to util.groovy

easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.08-EGL-python3.eb
== COMPLETED: Installation ended successfully (took 22 min 12 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.9.0-CrayGNU-20.08-EGL-python3/easybuild/easybuild-ParaView-5.9.0-20210212.154953.log
=> [daint-gpu] fix loading the NVIDIA Index Library

easybuild/easyconfigs/c/cpeCCE/cpeCCE-21.02.eb, easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.02.eb, easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.02.eb, easybuild/easyconfigs/g/GSL/GSL-2.6-cpeCCE-21.02.eb, easybuild/easyconfigs/g/GSL/GSL-2.6-cpeGNU-21.02.eb, easybuild/easyconfigs/g/GSL/GSL-2.6-cpeIntel-21.02.eb, jenkins-builds/1.3.2-21.02-pilatus
I provide the recipes of the toolchains for Cray PE 21.02 on Pilatus and the easyconfig files of GSL.
=> [pilatus] Toolchain recipes and GSL in production list

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.08-batchspawner.eb
JupyterHub 1.3 (and deps)  to match change on jupyter VM
=> [daint] Update jupyterlab-1.2.16-CrayGNU-20.08-batchspawner-cuda.eb

easybuild/cray_external_modules_metadata-21.02.cfg, easybuild/easyblocks/cpetoolchain.py, easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.02.eb, easybuild/easyconfigs/g/GSL/GSL-2.6-cpeAMD-21.02.eb, jenkins-builds/1.3.2-21.02-pilatus
I provide the toolchain `cpeAMD` with the recipe for `GSL.
=> [pilatus] cpeAMD toolchain with GSL

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.0.2-CrayGNU-20.08-batchspawner.eb
This PR adds nglview and its JupyterLab extension.  This version is prepared for EMPA course starting 24 Feb.
=> [daint] jupyterlab-2.0.2-CrayGNU-20.08-batchspawner-cuda.eb

easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.3-cpeGNU-21.02.eb, easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-21.02.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-21.02.eb, easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-21.02.eb, easybuild/easyconfigs/n/nodejs/nodejs-14.16.0-cpeGNU-21.02.eb
I have updated the dependencies using the latest stable release available: I did not update the versions of the Python extensions and the version of JupyterLab itself, though.
=> [pilatus] Jupyterlab and dependencies

easybuild/easyconfigs/l/LLVM/LLVM-8.0.0-cpeCray-21.02.eb, easybuild/easyconfigs/m/Mako/Mako-1.1.2-cpeCray-21.02-python3.eb, easybuild/easyconfigs/m/Mesa/Mesa-18.3.3-cpeCray-21.02.eb, easybuild/easyconfigs/o/oidn/oidn-1.2.4-cpeCray-21.02.eb, easybuild/easyconfigs/o/ospray/ospray-2.4.0-cpeCray-21.02.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-cpeCray-21.02-OSMesa-python3.eb, jenkins-builds/1.3.2-21.02-pilatus
I provide the recipe of the latest stable release of `ParaView` with dependencies for the toolchain `cpeCray` with Cray PE 21.02 on Pilatus.
=> [pilatus] ParaView with PE 21.02 

easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-20.11-python3.eb, easybuild/easyconfigs/b/Boost/Boost-1.75.0-CrayGNU-20.11.eb, easybuild/easyconfigs/b/Boost/Boost-1.75.0-python3.patch, easybuild/easyconfigs/b/bzip2/bzip2-1.0.8-CrayGNU-20.11.eb
I provide the recipes and the patch for Boost 1.75.0 on Dom with Cray Programming Environment 20.11 (required by @aurianer  for HPX 1.6.0).
=> [dom] Add Boost 1.75.0 with CrayPE 20.11

easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-20.10.eb
Fix for python. Previous recipe included a workaround for missing python, and although it built it did not execute.
=> [eiger] LAMMPS python fix

easybuild/easyconfigs/v/VMD/VMD-1.9.4.eb, jenkins-builds/7.0.UP02-20.08-daint-gpu
== COMPLETED: Installation ended successfully (took 12 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VMD/1.9.4a51/easybuild/easybuild-VMD-1.9.4-20210302.150958.log
=> [daint-gpu] update VMD to the latest 1.9.4

jenkins-builds/7.0.UP02-20.08-dom-gpu, jenkins-builds/7.0.UP02-20.11-dom-gpu
add VMD-1.9.4 to dom, as well as suggested by @lucamar
=> [dom-gpu] Add VMD to 7.0.UP02-20.11-dom-gpu

easybuild/easyconfigs/b/Boost/Boost-1.75.0-cpeGNU-21.02-python3.eb, easybuild/easyconfigs/b/Boost/Boost-1.75.0-cpeGNU-21.02.eb, easybuild/easyconfigs/c/CP2K/CP2K-8.1-cpeGNU-21.02.eb, jenkins-builds/1.3.2-21.02-pilatus
I provide the recipes for the latest stable releases of Boost and CP2K on Pilatus with Cray PE 21.02.
=> [pilatus] Boost and CP2K

easybuild/easyconfigs/v/Vc/Vc-1.4.1-cpeGNU-20.10.eb, jenkins-builds/1.3.2-20.10-eiger
For https://github.com/eth-cscs/reframe/pull/1839
=> [eiger] Vc

easybuild/easyconfigs/v/Vc/Vc-1.4.1-CrayGNU-20.08.eb, jenkins-builds/7.0.UP02-20.08-daint-gpu, jenkins-builds/7.0.UP02-20.08-daint-mc
For https://github.com/eth-cscs/reframe/pull/1839
=> [daint] Vc

easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-20.11-cuda-pat.eb, easybuild/easyconfigs/v/VASP/VASP-6.2.0-CrayIntel-20.11-pat.eb
I provide the easyconfigs of VASP (`gpu` and `mc`) with Cray Perftools 20.11.
=> [dom] VASP recipes with CrayPAT 20.11

easybuild/easyconfigs/p/ParaView/ParaView-5.9.0-CrayGNU-20.11-EGL-python3.eb
work-around for https://gitlab.kitware.com/paraview/paraview/-/issues/20487
=> [dom-gpu] force autoload of ParaView NVIDIA Index lib plugin

easybuild/easyconfigs/c/CPMD/CPMD-4.1-CrayIntel-20.11-pat.eb
workaround for bug in craypat 20.10.0
=> [dom] cpmd

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-CrayGNU-20.11.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-6.0-CrayGNU-20.11.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-7.0-CrayGNU-20.11.eb, easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-5.x
Updating OpenFOAM recipes for CrayGNU 20.11
=> [daint-mc] Updated OF recipes

easybuild/easyconfigs/n/nvidia-nsight-systems/nvidia-nsight-systems-2021.1.1.66-6c5c5cb.eb, jenkins-builds/7.0.UP02-20.11-daint-gpu, jenkins-builds/7.0.UP02-20.11-dom-gpu
=> [dom-gpu, daint-gpu] nvidia nsys/2021.1

spack/0.15.4/dom/packages.yaml
This fixes a typo in the packages.yaml file.
=> [dom] Update Spack config for version 0.15.4 on dom

spack/0.16.1/dom/packages.yaml
This fixes a typo in the packages.yaml file.
=> [dom] Update Spack config for version 0.16.1 on dom

spack/dom/packages.yaml
This fixes a typo in the packages.yaml file.
=> [dom] Update Spack config for version develop on dom

easybuild/easyconfigs/m/magma/magma-2.5.4-CrayIntel-20.11-cuda.eb
Changing to configure make since the pckgconfig is configured with `make install`
=> [dom-gpu daint-gpu] Use ConfigureMake easyblock for Magma

easybuild/easyblocks/cpetoolchain.py, easybuild/easyconfigs/c/CMake/CMake-3.20.1.eb, easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.03.eb, easybuild/easyconfigs/c/cpeCray/cpeCray-21.03.eb, easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.03.eb, easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.03.eb, easybuild/easyconfigs/g/GROMACS/GROMACS-2020.5-cpeGNU-21.03.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-29Oct20-cpeGNU-21.03.eb, easybuild/easyconfigs/l/LLVM/LLVM-8.0.0-cpeCray-21.03.eb, easybuild/easyconfigs/l/libxc/libxc-4.3.4-cpeGNU-21.03.eb, easybuild/easyconfigs/l/libxc/libxc-5.1.3-cpeGNU-21.03.eb, easybuild/easyconfigs/m/Mesa/Mesa-18.3.3-cpeCray-21.03.eb, easybuild/easyconfigs/v/Vc/Vc-1.4.1-cpeGNU-21.03.eb, easybuild/module/EasyBuild-custom/cscs, jenkins-builds/1.4.0-21.03-eiger
Recipes to complete PE 21.03 (outdated) in preparation of 21.04 (current one). The recipes have already been tested in https://jenkins.cscs.ch/blue/organizations/jenkins/UpdateEB/detail/UpdateEB/2/pipeline, so I'll merge immediately.
=> [eiger] Complete 21.03 and prepare for 21.04

easybuild/easyblocks/boost.py, easybuild/easyblocks/bzip2cce.py, easybuild/easyblocks/darshan.py, easybuild/easyblocks/esmfcray.py, easybuild/easyblocks/hpcg3.py, easybuild/easyblocks/idl.py, easybuild/easyblocks/julia.py, easybuild/easyblocks/juliabundle.py, easybuild/easyblocks/juliapackage.py, easybuild/easyblocks/libqglviewer.py, easybuild/easyblocks/netcdf4_python.py, easybuild/easyblocks/netcdf_python.py, easybuild/easyblocks/openfoamdev.py, easybuild/easyblocks/pgi.py, easybuild/easyblocks/pycuda.py, easybuild/easyblocks/qt.py, easybuild/easyblocks/rmpi.py, easybuild/easyblocks/scons.py, easybuild/easyblocks/xalt.py
I used pylint, so most of the changes are whitespace and unused imports. There might still be issues in the files:
- `easybuild/easyblocks/juliapackage.py`:
```
easybuild/easyblocks/juliapackage.py:156:2: W1401: Anomalous backslash in string: '\s'. String constant might be missing an r prefix. (anomalous-backslash-in-string)
easybuild/easyblocks/juliapackage.py:137:72: E0602: Undefined variable 'stdin' (undefined-variable)
```
@victorusu I didn't know how to substitute the `stdin` variable. Could you have look?
- `easybuild/easyblocks/darshan.py`:
```
easybuild/easyblocks/darshan.py:63:101: E0602: Undefined variable 'envvar' (undefined-variable)
```
so I assume envvar was `MPICC`
- `easybuild/easyblocks/openfoamdev.py`:
```
easybuild/easyblocks/openfoamdev.py:238:0: W1401: Anomalous …
```
=> [daint dom eiger pilatus tsa] Update easyblocks to python 3

easybuild/easyblocks/juliapackage.py
Seems like you need to use sys.stdin
=> [daint dom] Fix stdin syntax error in juliapackage.py

easybuild/easyblocks/juliapackage.py
=> [daint dom] Import sys in juliapackage.py

easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11-cuda.eb, easybuild/easyconfigs/j/Julia/Julia-1.6.0-CrayGNU-20.11.eb
To hopefully fix packe download issues
=> [daint dom] Set JULIA_PKG_SERVER to empty string to disable it

jenkins-builds/7.0.UP02-20.11-dom-gpu
Bugfix. I had added the mc version to the gpu prod list. Sorry about that!
=> [dom-gpu] 7.0.UP02-20.11-dom-gpu

spack/reframe/src/spack_util/spack_config.py
This PR adds the netcdf-c and parallel-netcdf packages that were missing.
Thanks @rsarm for pointing that out!
=> Update list of mapped packages

easybuild/easyconfigs/b/Bazel/Bazel-4.0.0-CrayGNU-20.11.eb
Adding Bazel 4.0.0, due to a user request.
=> [daint] Add Bazel 4.0.0

easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.0-cpeGNU-21.04.eb, jenkins-builds/1.4.0-21.04-eiger
Add JuliaExtensions and Julia 1.6 to the production list.
=> [eiger] Create JuliaExtensions-1.6.0-cpeGNU-21.04.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.8-cpeGNU-21.04.eb
Adding ijulia kernel. If you could check the syntax I've used for the modluafooter and improve if necessary, that would be great (you can compare against the tcl version in e.g. the easyconfig jupyterlab-1.2.16... for daint).
=> [eiger] Update jupyterlab-2.2.8-cpeGNU-21.04.eb

easybuild/easyconfigs/f/FFmpeg/FFmpeg-4.4-CrayGNU-20.11.eb, easybuild/easyconfigs/o/ogg/ogg-1.3.1-CrayGNU-20.11.eb, easybuild/easyconfigs/t/theora/theora-1.2.0alpha1-CrayGNU-20.11.eb, easybuild/easyconfigs/v/vorbis/vorbis-1.3.3-CrayGNU-20.11.eb, jenkins-builds/7.0.UP02-20.11-daint-gpu, jenkins-builds/7.0.UP02-20.11-daint-mc
this enables ipywidgets.Video viewing 
== COMPLETED: Installation ended successfully (took 1 min 57 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/FFmpeg/4.4-CrayGNU-20.11/easybuild/easybuild-FFmpeg-4.4-20210501.151005.log
=> [daint] New version of FFmpeg with the Theora encoder 

easybuild/easyconfigs/j/Julia/Julia-1.6.1-CrayGNU-20.11-cuda.eb, easybuild/easyconfigs/j/Julia/Julia-1.6.1-CrayGNU-20.11.eb, easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.1-CrayGNU-20.11-cuda.eb, easybuild/easyconfigs/j/JuliaExtensions/JuliaExtensions-1.6.1-CrayGNU-20.11.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.16-CrayGNU-20.11-batchspawner.eb
=> [dom] Bump julia to 1.6.1

easybuild/easyconfigs/c/CrayGNU/CrayGNU-21.02.eb, easybuild/easyconfigs/c/CubeLib/CubeLib-4.6-CrayGNU-21.02.eb, easybuild/easyconfigs/c/CubeW/CubeW-4.6-CrayGNU-21.02.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.4.0-CrayGNU-21.02.eb, easybuild/easyconfigs/s/SIONlib/SIONlib-1.7.6l-CrayGNU-21.02.eb, easybuild/easyconfigs/s/Score-P/Score-P-7.0-CrayGNU-21.02.eb
https://jira.cscs.ch/browse/UES-1576
=> [dom] Enable scorep/7 on Cray XC

easybuild/easyconfigs/b/Bison/Bison-3.7.5-CrayGNU-20.11.eb, easybuild/easyconfigs/c/cURL/cURL-7.76.1-CrayGNU-20.11.eb, easybuild/easyconfigs/e/expat/expat-2.2.10-CrayGNU-20.11.eb, easybuild/easyconfigs/g/GDAL/GDAL-3.3.0-CrayGNU-20.11-python3.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.9.1-CrayGNU-20.11-python3.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-CrayGNU-20.11.eb, easybuild/easyconfigs/j/JasPer/JasPer-2.0.32-CrayGNU-20.11.eb, easybuild/easyconfigs/l/LibTIFF/LibTIFF-4.2.0-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libaec/libaec-1.0.4-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.6.0-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libjpeg-turbo/libjpeg-turbo-2.0.90-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.37-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libreadline/libreadline-8.1-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libxml2/libxml2-2.9.10-CrayGNU-20.11.eb, easybuild/easyconfigs/n/ncurses/ncurses-6.2-CrayGNU-20.11.eb, easybuild/easyconfigs/p/PCRE/PCRE-8.44-CrayGNU-20.11.eb, easybuild/easyconfigs/p/PROJ/PROJ-8.0.0-CrayGNU-20.11.eb, easybuild/easyconfigs/s/SQLite/SQLite-3.35.5-CrayGNU-20.11.eb, easybuild/easyconfigs/s/SWIG/SWIG-4.0.2-CrayGNU-20.11-python3.eb
EasyBuild script to build the latest release of GDAL and its dependencies, addressing a [recent request](https://jira.cscs.ch/browse/SD-52075).
=> [daint] GDAL and dependencies

easybuild/easyconfigs/o/OTF2/OTF2-2.3.eb, easybuild/easyconfigs/o/OTF2/OTF2-2.3.patch, easybuild/easyconfigs/s/Scalasca/Scalasca-2.6-CrayGNU-21.02.eb
depends on https://github.com/eth-cscs/production/pull/2300
=> [dom] scalasca

jenkins-builds/7.0.UP02-20.11-dom-gpu, jenkins-builds/7.0.UP02-20.11-dom-mc
Upgrade julia to 1.6.1 for testing SD-52054
=> [dom] Update dom production lists with julia 1.6.1

jenkins-builds/1.4.0-21.04-eiger
https://jira.cscs.ch/browse/C4KCUST-268
=> [pilatus] scalasca

easybuild/easyconfigs/c/Charm++/Charm++-6.10.2-cpeGNU-21.04.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.14-cpeGNU-21.04.eb, easybuild/easyconfigs/t/Tcl/Tcl-8.6.10-cpeGNU-21.04.eb, jenkins-builds/1.4.0-21.04-eiger
NAMD built with the GNU compiler.
=> [eiger] NAMD with cpeGNU

jenkins-builds/1.4.0-21.04-eiger
Please add the missing recipe or revert eth-cscs/production#2305
```
ERROR: One or more files not found: Scalasca-2.6-cpeGNU-21.04.eb (search paths: /tmp/jenscscs/workspace/ProductionEB/easybuild/easyconfigs, /tmp/jenscscs/workspace/ProductionEB/easybuild/easyconfigs, /apps/common/UES/easybuild/software/EasyBuild/4.3.2/easybuild/easyconfigs)
```
=> [eiger] scalasca

easybuild/easyconfigs/v/Visit/Visit-3.2.0-CrayGNU-20.11.eb, jenkins-builds/7.0.UP02-20.11-daint-gpu, jenkins-builds/7.0.UP02-20.11-daint-mc
== COMPLETED: Installation ended successfully (took 59 min 12 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Visit/3.2.0-CrayGNU-20.11/easybuild/easybuild-Visit-3.2.0-20210514.083741.log
=> [daint] new version of VisIt 3.2 for Piz Daint

easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-CrayGNU-20.11-OSMesa-python3.eb, jenkins-builds/7.0.UP02-20.11-daint-mc
== COMPLETED: Installation ended successfully (took 23 min 37 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.9.1-CrayGNU-20.11-OSMesa-python3/easybuild/easybuild-ParaView-5.9.1-20210514.174514.log
=> [daint-mc] minor update to ParaView v5.9.1 for Multicore

easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-CrayGNU-20.11-EGL-python3.eb, jenkins-builds/7.0.UP02-20.11-daint-gpu
== COMPLETED: Installation ended successfully (took 25 min 24 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.9.1-CrayGNU-20.11-EGL-python3/easybuild/easybuild-ParaView-5.9.1-20210514.174557.log
=> [daint-gpu] minor update to ParaView v5.9.1 for Hybrid

spack/eiger/compilers.yaml, spack/eiger/packages.yaml
Added a first working version of compiler.yaml and package.yaml for eiger.
These files are not complete but are a good starting point to use spack on eiger.
=> [eiger] Initial working spack package.yaml file.

easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-cpeCray-21.04-OSMesa-python3.eb, jenkins-builds/1.4.0-21.04-eiger
== COMPLETED: Installation ended successfully (took 21 min 29 sec)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/ParaView/5.9.1-cpeCray-21.04-OSMesa-python3/easybuild/easybuild-ParaView-5.9.1-20210526.173541.log
=> [eiger] patched version of ParaView, with TBB acceleration

jenkins-builds/7.0.UP02-20.11-dom-gpu, jenkins-builds/7.0.UP02-20.11-dom-mc
Sync the default production lists of Dom with Piz Daint and keep only the latest release on Dom.
=> [dom] Sync Dom with Piz Daint

easybuild/easyconfigs/v/Visit/Visit-3.2.0-CrayGNU-21.02.eb
== COMPLETED: Installation ended successfully (took 55 min 0 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/Visit/3.2.0-CrayGNU-21.02/easybuild/easybuild-Visit-3.2.0-20210609.115701.log
=> [dom-mc] turn off LIBSIM compilation until dust settles on python3 migration

spack/eiger/compilers.yaml, spack/eiger/packages.yaml
Version of modules and packages has been updated to match what is available after the maintenance.
=> [eiger] Update spack configs for eiger

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-6.6a2-CrayPGI-20.11-cuda.eb
Minor change in preparation to 21.02 on Cray XC50 (see [UES-1604](https://jira.cscs.ch/browse/UES-1604)).
=> [daint-gpu dom-gpu] Fix QE 6.6a2

easybuild/easyconfigs/c/CP2K/CP2K-8.1-cpeIntel-21.04.eb, easybuild/easyconfigs/c/CP2K/CP2K-8.1-cpeIntel.psmp
Update architecture file based on GitHub project.
=> [eiger] CP2K with MKL

easybuild/easyconfigs/o/ovito/ovito-3.5.2-CrayGNU-21.02.eb, jenkins-builds/7.0.UP02-20.11-daint-gpu, jenkins-builds/7.0.UP02-20.11-dom-gpu, jenkins-builds/7.0.UP02-21.02-dom-gpu
== COMPLETED: Installation ended successfully (took 17 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ovito/3.5.2-CrayGNU-21.02/easybuild/easybuild-ovito-3.5.2-20210617.112750.log
=> [daint-gpu,dom-gpu] update to ovito/3.5.2

easybuild/easyconfigs/o/ovito/ovito-3.5.2-CrayGNU-20.11.eb
I provide the missing recipe, as discussed with @jfavre.
=> [daint-gpu dom-gpu] Add missing ovito for 20.11

easybuild/easyconfigs/x/xalt/Daint_config.py, easybuild/easyconfigs/x/xalt/xalt-2.8.10-eiger.eb
Assigning a machine to this PR title is irrelevant...
It is just to avoid the blocking of the CI failure.
=> [eiger] Add XALT eiger recipe

easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.06.eb, easybuild/easyconfigs/c/cpeCray/cpeCray-21.06.eb, easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.06.eb, easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.06.eb
I provide the easyconfigs of the toolchains for PE 21.06.
=> [pilatus] Toochain recipes 21.06

easybuild/easyconfigs/v/VTK/VTK-9.0.3-CrayGNU-20.11-EGL-python3.eb, easybuild/easyconfigs/v/VTK/VTK-9.0.3-CrayGNU-21.02-EGL-python3.eb, easybuild/easyconfigs/v/Visit/Visit-3.2.0-CrayGNU-20.11.eb, easybuild/easyconfigs/v/Visit/Visit-3.2.0-CrayGNU-21.02.eb, jenkins-builds/7.0.UP02-20.11-daint-gpu, jenkins-builds/7.0.UP02-20.11-dom-gpu, jenkins-builds/7.0.UP02-21.02-dom-gpu
== COMPLETED: Installation ended successfully (took 1 hour 0 min 54 sec)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Visit/3.2.0-CrayGNU-21.02/easybuild/easybuild-Visit-3.2.0-20210708.115211.log
=> [daint] Visit xdmf patch

easybuild/cpe_external_modules_metadata-21.07.cfg, easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.04.eb, easybuild/easyconfigs/c/cpeAMD/cpeAMD-21.05.eb, easybuild/easyconfigs/c/cpeCray/cpeCray-21.04.eb, easybuild/easyconfigs/c/cpeCray/cpeCray-21.05.eb, easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.04.eb, easybuild/easyconfigs/c/cpeGNU/cpeGNU-21.05.eb, easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.04.eb, easybuild/easyconfigs/c/cpeIntel/cpeIntel-21.05.eb
Add metadata file for PE 21.07 and simpler toolchain recipes (EasyBuild 4.4.0 or more recent required).
=> [eiger pilatus] Add metadata 21.07 and simpler toolchain recipes

easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-cpeCray-21.05-OSMesa-python3.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.9.1-cpeCray-21.06-OSMesa-python3.eb
Missing recipes of `ParaView` on Alps added to the production repository.
=> [eiger pilatus] Add missing recipes of ParaView

easybuild/easyconfigs/c/CP2K/CP2K-8.2-cpeGNU.psmp, easybuild/easyconfigs/c/CP2K/CP2K-8.2.69b8c2e-cpeGNU-21.05.eb, easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-cpeGNU-21.05.eb, easybuild/easyconfigs/g/GSL/GSL-2.7-cpeGNU-21.05.eb, easybuild/easyconfigs/l/libvori/libvori-210412-cpeGNU-21.05.eb, easybuild/easyconfigs/l/libxc/libxc-5.1.5-cpeGNU-21.05.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-cpeGNU-21.05.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.5-cpeGNU-21.05.eb, easybuild/easyconfigs/s/SPLA/SPLA-1.5.1-cpeGNU-21.05.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.4-cpeGNU-21.05.eb, easybuild/easyconfigs/s/spglib/spglib-1.16.0-cpeGNU-21.05.eb, jenkins-builds/1.4.0-21.05-eiger
I provide the recipes of CP2K 8.2 (commit 69b8c2e) and dependencies for PE 21.05 on Eiger (see [SD-52307](https://jira.cscs.ch/browse/SD-52307)).
=> [eiger] CP2K 8.2 (PE 21.05)

easybuild/easyconfigs/c/CP2K/CP2K-8.2-CrayGNU.psmp, easybuild/easyconfigs/c/CP2K/CP2K-8.2.69b8c2e-CrayGNU-20.11.eb, easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-CrayGNU-20.11.eb, easybuild/easyconfigs/g/GSL/GSL-2.7-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libvori/libvori-210412-CrayGNU-20.11.eb, easybuild/easyconfigs/l/libxc/libxc-5.1.5-CrayGNU-20.11.eb, easybuild/easyconfigs/p/PLUMED/PLUMED-2.7.1-CrayGNU-20.11.eb
I provide a custom CP2K recipe to address [SD-52886](https://jira.cscs.ch/browse/SD-52886).
=> [daint-mc] CP2K 8.2 with libvori and PLUMED

easybuild/easyconfigs/c/CubeLib/CubeLib-4.5-cpeGNU-21.07.eb, jenkins-builds/1.4.0-21.07-eiger
found issue in cubelib/4.6, adding 4.5 as a workaround.
=> [pilatus] fix cube deps

easybuild/easyconfigs/c/CubeLib/CubeLib-4.5-cpeGNU-21.04.eb, jenkins-builds/1.4.0-21.04-eiger
found issue in cubelib/4.6, adding 4.5 as a workaround.
=> [eiger] fix cube deps

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-21.02-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-21.02-batchspawner.eb
update notebook and jupyterlab and deps
=> [dom] jupyterlab-1.2.21-CrayGNU-21.02-batchspawner-cuda.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner.eb
Updates for notebook and lab and required deps.
=> [daint] Create jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb

jenkins-builds/7.0.UP02-20.11-daint-gpu, jenkins-builds/7.0.UP02-20.11-daint-mc
=> [daint] Update 7.0.UP02-20.11-daint-gpu

jenkins-builds/1.4.0-21.04-eiger
Fixes a bug in the earlier version of JupyterLab
=> [eiger] Update 1.4.0-21.04-eiger

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner.eb
upgrade juputerlab and notebook and deps
=> [daint] Create jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.02-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.02-batchspawner.eb
updates of jupyterlab and notebook and deps
=> [dom] Create jupyterlab-2.2.10-CrayGNU-21.02-batchspawner-cuda.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner.eb
Fix cosmetic bug with module show
=> [dom] Update jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb

spack/readme.md
So that other people than Victor know how this works too
=> Document spack reframe config bump

spack/reframe/src/spack_util/spack_config.py
=> Remove non-existing variants for netcdf-fortran

spack/reframe/spack.py
=> Bump spack 0.16.x

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-cpeGNU-21.08.eb
Add R kernel from cray-R module
=> [pilatus] Update jupyterlab-2.2.10-cpeGNU-21.08.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-1.2.21-CrayGNU-20.11-batchspawner.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-20.11-batchspawner.eb
Fixes small typo, which was cosmetic apparently...
=> [dom] update jupyterlab fix typo

easybuild/easyconfigs/a/ABINIT/ABINIT-9.4.1-cpeGNU-21.08.eb, easybuild/easyconfigs/w/Wannier90/Wannier90-3.1.0-cpeGNU-21.08.eb, easybuild/easyconfigs/w/Wannier90/Wannier90-3x_ignore_makeinc.patch
Based on Jira SD ticket: https://jira.cscs.ch/projects/SD/queues/custom/3/SD-53377
=> [eiger] ABINIT for Eiger

easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-cpeCray-21.08.eb, easybuild/easyconfigs/m/Mesa/Mesa-21.2.1-cpeCray-21.08.eb, easybuild/easyconfigs/m/Meson/Meson-0.59.1-cpeCray-21.08-python3.eb, easybuild/easyconfigs/n/Ninja/Ninja-1.10.2-cpeCray-21.08-python3.eb
== COMPLETED: Installation ended successfully (took 1 min 42 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/Mesa/21.2.1-cpeCray-21.08/easybuild/easybuild-Mesa-21.2.1-20211004.085143.log
=> [eiger] major Mesa upgrade for the (upcoming) ParaView v5.10

easybuild/easyconfigs/g/GROMACS/GROMACS-2021.3-CrayGNU-21.02-cuda.eb
Commit based on https://jira.cscs.ch/projects/SD/queues/custom/3/SD-53414
=> [daint-gpu] Gromacs 2021.3

jenkins-builds/1.4.0-21.08-eiger
=> [eiger] Update 1.4.0-21.08-eiger

easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.3-cpeGNU-21.09.eb, easybuild/easyconfigs/n/nodejs/nodejs-14.16.0-cpeGNU-21.09.eb
Adds configurable-http-proxy, which is a jupyterlab dependency.
=> [pilatus] configurable-http-proxy-4.2.3-cpeGNU-21.09.eb

easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-21.09.eb
Adds graphviz, which is a dep of jupyterlab
=> [pilatus] graphviz-2.46.1-cpeGNU-21.09.eb

easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-21.09.eb
Adds libffi which is a dep of jupyterlab
=> [pilatus] libffi-3.3-cpeGNU-21.09.eb

jenkins-builds/1.4.0-21.09-eiger
Add jupyterlab-2.2.10-cpeGNU-21.09.eb to production list
=> [eiger pilatus] Update production list 21.09

easybuild/module/EasyBuild-custom/cscs
Switch to external metadata 21.09 on Dom
=> [dom] Update EasyBuild-custom

easybuild/easyconfigs/l/LLVM/LLVM-9.0.1-cpeCray-21.09.eb, easybuild/easyconfigs/v/VTK/VTK-9.1.0-cpeCray-21.09-OSMesa-python3.eb
== COMPLETED: Installation ended successfully (took 9 mins 32 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/VTK/9.1.0-cpeCray-21.09-OSMesa-python3/easybuild/easybuild-VTK-9.1.0-20211213.110111.log
=> [pilatus] restore sanity check and update LD_LIBRARY_PATH

jenkins-builds/7.0.UP03-21.09-dom-gpu, jenkins-builds/7.0.UP03-21.09-dom-mc
Add the recently fixed NAMD recipe (see #2561) in production on Dom.
=> [dom] Add NAMD 2.14 in production

easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-CrayGNU-21.09-cuda.eb, easybuild/easyconfigs/e/ELPA/ELPA-2021.05.002-CrayGNU-21.09.eb, easybuild/easyconfigs/l/libxc/libxc-5.1.7-CrayGNU-21.09.eb, easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.2.8-CrayGNU-21.09-cuda.eb, easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-CrayGNU-21.09-cuda-mkl.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.5-CrayGNU-21.09-cuda-mkl.eb, easybuild/easyconfigs/s/spglib/spglib-1.16.3-CrayGNU-21.09.eb
I add the recipe for the last version of SIRIUS and the dependencies with CDT 21.09 on Dom.
=> [dom-gpu] SIRIUS 7.2.8

easybuild/easyconfigs/p/PyTorch/PyTorch-1.10.1-CrayGNU-20.11.eb, jenkins-builds/7.0.UP02-20.11-daint-gpu
=> [daint-gpu] PyTorch 1.10.1 20.11

easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-CrayGNU-21.09-OSMesa.eb, jenkins-builds/7.0.UP03-21.09-dom-mc
== COMPLETED: Installation ended successfully (took 45 mins 33 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000tds/jfavre/daint/software/ParaView/5.10.0-CrayGNU-21.09-OSMesa/easybuild/easybuild-ParaView-5.10.0-20211221.073947.log
=> [dom-mc] ParaView v5.10-OSMesa for Dom 21.09

jenkins-builds/7.0.UP03-21.09-dom-gpu
Add Horovod recipe to dom-gpu production list.
=> [dom-gpu] Add Horovod in production

easybuild/easyconfigs/l/libxc/libxc-5.1.7-CrayNvidia-21.09.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayNvidia-21.09.eb, jenkins-builds/7.0.UP03-21.09-dom-gpu
I provide the recipe of the latest release of QuantumESPRESSO (7.0) with CrayNvidia 21.09.
=> [dom-gpu] QuantumESPRESSO 7.0 (CrayNvidia)

easybuild/easyconfigs/b/basicanalysis/basicanalysis-0.3.9.eb, easybuild/easyconfigs/b/basicanalysis/basicanalysis-0.eb, easybuild/easyconfigs/d/Dimemas/Dimemas-5.4.2.eb, easybuild/easyconfigs/e/Extrae/Extrae-3.8.3-CrayGNU-21.09.eb
Fix https://jira.cscs.ch/browse/AVAILAPPS-22
Fix https://jira.cscs.ch/browse/AVAILAPPS-30
=> [dom] extrae383

easybuild/easyconfigs/l/libxc/libxc-5.1.7-cpeIntel-21.12.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-cpeIntel-21.12.eb, jenkins-builds/1.4.0-21.12-eiger
I provide the recipe of the latest release of QuantumESPRESSO with dependencies.
=> [pilatus] QuantumESPRESSO 7.0 with 21.12

easybuild/easyconfigs/j/jupyterlab/jupyterlab-2.2.10-CrayGNU-21.09-batchspawner-cuda.eb
- incorporated IPython and its deps 
- incorporated dask to help ensure compatibility with labextension 
- updated many python modules to work with 3.9. 
- most labextensions are working. Topbar extension is not yet working.
- ipyparaview functionality needs to be tested.
- removed bqplot (can be readded if requested by users)
I would like this to be merged to be able to test on Dom in prod-like environments.
=> [dom-gpu] Create jupyterlab-2.2.10-CrayGNU-21.09-batchspawner-cuda.eb

jenkins-builds/7.0.UP03-21.09-dom-gpu
Add jupyterlab-2.2.10-CrayGNU-21.09-batchspawner-cuda.eb to production list
=> [dom-gpu] Update 7.0.UP03-21.09-dom-gpu

easybuild/easyconfigs/c/CubeLib/CubeLib-4.6-CrayGNU-21.09.eb, easybuild/easyconfigs/o/otf2_cli_profile/otf2_cli_profile-33c89b7-CrayGNU-21.09.eb, easybuild/easyconfigs/r/rapidjson/rapidjson-fd3dc29.eb
Fix for https://jira.cscs.ch/browse/AVAILAPPS-40
Fix for https://jira.cscs.ch/browse/AVAILAPPS-29
=> [dom] otf2_cdt2109

easybuild/easyconfigs/c/CubeLib/CubeLib-4.6-CrayGNU-21.09.eb, easybuild/easyconfigs/c/CubeW/CubeW-4.6-CrayGNU-21.09.eb, easybuild/easyconfigs/l/libunwind/libunwind-1.4.0-CrayGNU-21.09.eb, easybuild/easyconfigs/s/Score-P/Score-P-7.1-CrayGNU-21.09.eb
Fix for https://jira.cscs.ch/browse/AVAILAPPS-44
Fix for https://jira.cscs.ch/browse/AVAILAPPS-37
=> [dom] scorep_cdt2109

easybuild/easyconfigs/s/Scalasca/Scalasca-2.6-CrayGNU-21.09.eb, easybuild/easyconfigs/s/scorep_binding_python/scorep_binding_python-3.4.0-CrayGNU-21.09-python3.eb
Fix for https://jira.cscs.ch/browse/AVAILAPPS-43
Fix for https://jira.cscs.ch/browse/AVAILAPPS-45
Fix for https://jira.cscs.ch/browse/AVAILAPPS-35
Fix for https://jira.cscs.ch/browse/AVAILAPPS-38
=> [dom] scalasca_cdt2109

easybuild/easyconfigs/s/spack-config/spack-config-1.4-cdt-21.09.eb, easybuild/easyconfigs/s/spack-config/spack-config-1.4-cdt-cuda-21.09.eb, jenkins-builds/7.0.UP03-21.09-dom-gpu, jenkins-builds/7.0.UP03-21.09-dom-mc
Testing on dom the latest spack-config which add `pgi` compiler to the provided config.
=> [dom] spack-config update: add pgi compiler

easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-dom-mc
I provide the recipe for the latest GROMACS release 2021.5 with CDT 21.09.
=> [dom-mc] Update GROMACS multicore with 21.09

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Adds nbresuse module which was missing and prevented the memory usage monitor from working
=> [dom] Update jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb

easybuild/easyconfigs/c/CP2K/CP2K-9.1-cpeGNU-21.12.eb, easybuild/easyconfigs/c/CP2K/CP2K-9.1-cpeGNU.psmp, easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-cpeGNU-21.12.eb, easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-cpeGNU-21.12.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.5-cpeGNU-21.12.eb
I provide the recipe for CP2K 9.1 with the latest release of SIRIUS that includes ELPA.
=> [pilatus] CP2K 9.1 with SIRIUS

easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-21.05-acc.eb, easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-acc.makefile.include
I provide the recipe of VASP 6.3.0 with `PrgEnv-nvidia` on Piz Daint (see [SD-54276](https://jira.cscs.ch/browse/SD-54276)).
=> [daint-gpu] VASP 6.3.0

easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-21.09.eb, easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU.psmp, easybuild/easyconfigs/s/SIRIUS/SIRIUS-7.3.1-CrayGNU-21.09-mkl.eb, easybuild/easyconfigs/s/SPLA/SPLA-1.5.2-CrayGNU-21.09-mkl.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.5-CrayGNU-21.09-mkl.eb
I provide the recipe of CP2K 9.1 with the latest SIRIUS including ELPA (see comment in #2627 for `-DUSE_CRAY_LIBSCI=0` and `-DUSE_MKL=1`).
=> [dom-mc] CP2K 9.1 with SIRIUS (multicore)

easybuild/easyconfigs/g/GROMACS/GROMACS-2021.5-cpeGNU-21.12.eb, jenkins-builds/1.4.0-21.12-eiger
I provide the recipe of GROMACS 2021.5 with CPE 21.12 and updated production list.
=> [pilatus] Update Gromacs with CPE 21.12

easybuild/easyconfigs/c/CP2K/CP2K-9.1-CrayGNU-cuda.psmp
Fix CP2K architecture file (missing SIRIUS flags)
=> [dom-gpu]  Fix CP2K cuda with SIRIUS

easybuild/easyconfigs/c/CrayNvidia/CrayNvidia-21.09.eb, easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-21.09-acc.eb, easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayNvidia-acc.makefile.include, jenkins-builds/7.0.UP03-21.09-dom-gpu
Add VASP 6.3.0 in production on Dom
=> [dom-gpu] VASP 6.3.0 OpenACC

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8.0-CrayGNU-20.11.eb, easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-8.0-20210316
User request https://jira.cscs.ch/projects/SD/queues/custom/3/SD-54313
=> [daint-mc] OpenFOAM8

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-8.0-CrayGNU-21.09.eb
In view of the upcoming maintenance, this is the corresponding version of OF8 for the 21.09 toolchain.
(based on user request: https://jira.cscs.ch/projects/SD/queues/custom/3/SD-54313)
=> [dom-mc] OpenFOAM 8

easybuild/easyconfigs/v/VASP/VASP-6.2.1-CrayIntel.makefile.include, easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayIntel-21.09.eb, easybuild/easyconfigs/v/VASP/VASP-6.3.0-CrayIntel.makefile.include, jenkins-builds/7.0.UP03-21.09-daint-mc
I provide the recipe of the latest VASP release for the multicore nodes.
=> [dom-mc] VASP 6.3.0 multicore

easybuild/easyconfigs/v/VASP/VASP-6.3.0-cpeIntel-21.12.eb, easybuild/easyconfigs/v/VASP/VASP-6.3.0-cpeIntel.makefile.include, jenkins-builds/1.4.0-21.12-eiger
I provide the recipe of the latest VASP release with CPE 21.12.
=> [pilatus] VASP 6.3.0

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2112-CrayGNU-20.11.eb, easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-v2112
PR based on user request: https://jira.cscs.ch/projects/SD/queues/custom/3/SD-54669
=> [daint-mc] OpenFOAM v2112

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner.eb
Add the nbextension installation.
Fixed the permissions issue by putting the user's local directory earlier in the JUPYTER_CONFIG_PATH
=> [dom] jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb

easybuild/easyconfigs/c/CGAL/CGAL-5.1-CrayGNU-21.09.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2112-CrayGNU-21.09.eb
Update to new software stack version in view of system upgrade.
=> [dom-mc] OpenFOAM v2112

easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-CrayGNU-21.09-OSMesa.eb
Use production release source file instead of RC2
=> [daint-mc,dom-mc] update recipe

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2.eb
I provide the recipe for OpenMPI 4.1.2 with the system toolchain (see [SD-52831](https://jira.cscs.ch/browse/SD-52831)).
=> [daint-gpu] OpenMPI 4.1.2

easybuild/easyconfigs/s/spack-config/spack-config-1.5-cdt-21.09.eb, easybuild/easyconfigs/s/spack-config/spack-config-1.5-cdt-cuda-21.09.eb
=> [dom,daint] Bring back spack-config/1.5

easybuild/easyconfigs/e/expat/expat-2.2.10-CrayGNU-21.09.eb, easybuild/easyconfigs/g/GDAL/GDAL-3.4.1-CrayGNU-21.09-python3.eb, easybuild/easyconfigs/g/GEOS/GEOS-3.10.2-CrayGNU-21.09-python3.eb, easybuild/easyconfigs/h/HDF/HDF-4.2.15-CrayGNU-21.09.eb, easybuild/easyconfigs/l/libgeotiff/libgeotiff-1.7.0-CrayGNU-21.09.eb
Add GDAL and dependencies (expat, GEOS, HDF and libgeotiff) for CrayGNU-21.09.
=> [daint] GDAL-3.4.1-CrayGNU-21.09 with depenencies

login/daint-gpu/21.09, login/daint-mc/21.09
I provide a fix to the path error in the meta-modules merged in #2693.
=> [daint] Fix path error in meta-modules

easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2.eb
I have added Cray `pmi` include and library paths.
=> [daint dom] OpenMPI with Cray pmi

easybuild/easyconfigs/n/ncview/ncview-2.1.7-CrayGNU-21.09.eb
=> [daint dom] Update ncview

easybuild/easyconfigs/b/BAGEL/BAGEL-1.2.2-CrayGNU-21.09.eb
I add a new recipe for the software `BAGEL` with Cray PE 21.09 (see [SD-54169](https://jira.cscs.ch/browse/SD-54169)).
=> [daint dom] BAGEL with 21.09

easybuild/easyconfigs/v/VTK/VTK-9.1.0-CrayGNU-21.09-EGL-python3.eb
updates VTK, compatible with jupyter lab
=> [daint-gpu] VTK sync with ospray/tbb latest updates

easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-CrayGNU-21.09-OSMesa.eb
update ParaView for mc partition, compatible with jupyter lab
=> [daint-mc] ParaView OSMesa sync with ospray/tbb latest updates

easybuild/easyconfigs/b/BAGEL/BAGEL-1.2.2-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
I add the option `--set-default` to `CPMD` on the GPU software stack and define a runtime variable for `BAGEL` (see [SD-54169](https://jira.cscs.ch/browse/SD-54169)).
=> [daint dom] Minor updates

easybuild/easyconfigs/p/ParaView/ParaView-5.10.0-CrayGNU-21.09-EGL.eb
addresses https://jira.cscs.ch/projects/SD/queues/custom/48/SD-54939
=> [daint-gpu] missing h5py module

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2112-CrayGNU-21.09.eb, easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-v2112
Request based on https://jira.cscs.ch/projects/SD/queues/custom/3/SD-54933
Wrong cray-tpsl library used.
=> [daint-mc] Fix Scotch library dependency

easybuild/easyconfigs/f/FFmpeg/FFmpeg-5.0-CrayGNU-21.09.eb, easybuild/easyconfigs/x/x264/x264-20191217-CrayGNU-21.09.eb, easybuild/easyconfigs/x/x265/x265-3.2.1-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu, jenkins-builds/7.0.UP03-21.09-daint-mc
== COMPLETED: Installation ended successfully (took 3 mins 10 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/FFmpeg/5.0-CrayGNU-21.09/easybuild/easybuild-FFmpeg-5.0-20220315.161917.log
=> [daint] upgrade FFmpeg to version 5.0

easybuild/easyconfigs/a/Ascent/Ascent-0.8.0-CrayGNU-21.09.eb, easybuild/easyconfigs/c/Conduit/Conduit-0.8.2-CrayGNU-21.09-python3.eb, easybuild/easyconfigs/v/VTK-h/VTK-h-0.8.1-CrayGNU-21.09.eb, easybuild/easyconfigs/v/VTK-m/VTK-m-1.7.1-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu, jenkins-builds/7.0.UP03-21.09-daint-mc
== COMPLETED: Installation ended successfully (took 52 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Ascent/0.8.0-CrayGNU-21.09/easybuild/easybuild-Ascent-0.8.0-20220316.171545.log
=> [daint] first version of Ascent, in-situ visualization library

easybuild/easyconfigs/o/ovito/ovito-3.7.2-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 15 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ovito/3.7.2-CrayGNU-21.09/easybuild/easybuild-ovito-3.7.2-20220329.094439.log
=> [daint-gpu,dom-gpu] update Ovito v3.7.2

easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-21.09-cuda.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.14-CrayIntel-21.09.eb, easybuild/easyconfigs/n/NAMD/NAMD-2.14-pH.patch
Patch added for the following fix:
https://www.ks.uiuc.edu/Research/namd/2.14/bugfixes.html
=> [daint, dom] NAMD 2.14 pH fix

easybuild/easyconfigs/b/Boost/Boost-1.78.0-CrayGNU-20.08.eb, easybuild/easyconfigs/c/CGAL/CGAL-4.10.2-CrayGNU-20.08.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-CrayGNU-20.08-LABEL_SIZE_64-OpenMPI.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-5.0-CrayGNU-21.09-LABEL_SIZE_64-OpenMPI.eb, easybuild/easyconfigs/o/OpenFOAM/patch.OpenFOAM-5.x-LABEL_SIZE_64-OpenMPI, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2-CrayGNU-20.08.eb, easybuild/easyconfigs/o/OpenMPI/OpenMPI-4.1.2-CrayGNU-21.09.eb
PR based on https://jira.cscs.ch/projects/SD/queues/custom/614/SD-54960
=> [daint-mc] OF5 with OpenMPI

easybuild/easyconfigs/v/Visit/Visit-3.2.2-CrayGNU-21.09.eb
== COMPLETED: Installation ended successfully (took 1 hour 5 mins 5 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Visit/3.2.2-CrayGNU-21.09/easybuild/easybuild-Visit-3.2.2-20220406.180041.log
=> [daint-mc] enabling Conduit and the Blueprint reader

easybuild/easyconfigs/a/Ascent/Ascent-0.8.0-CrayGNU-21.09.eb, easybuild/easyconfigs/c/Conduit/Conduit-0.8.2-CrayGNU-21.09-python3.eb
== COMPLETED: Installation ended successfully (took 1 min 41 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Conduit/0.8.2-CrayGNU-21.09-python3/easybuild/easybuild-Conduit-0.8.2-20220407.181836.log
== COMPLETED: Installation ended successfully (took 1 min 6 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Ascent/0.8.0-CrayGNU-21.09/easybuild/easybuild-Ascent-0.8.0-20220407.181857.log
=> [daint] updating PYTHONPATH again

easybuild/easyconfigs/s/spack-config/spack-config-1.7-cdt-21.09.eb, easybuild/easyconfigs/s/spack-config/spack-config-1.7-cdt-cuda-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu, jenkins-builds/7.0.UP03-21.09-daint-mc
adds nvhpc compiler, removes upstreams.
=> [daint,dom] spack-config 1.7

easybuild/easyconfigs/p/ParaView/ParaView-5.10.1-CrayGNU-21.09-EGL.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
ParaView Cinema is part of the in-situ support needed for the Viz class of May 10
=> [daint-gpu, dom-gpu] fix ParaView Cinema crashing

easybuild/easyconfigs/a/Ascent/Ascent-0.8.0-cpeGNU-21.12.eb, easybuild/easyconfigs/c/Conduit/Conduit-0.8.3-cpeGNU-21.12-python3.eb, easybuild/easyconfigs/v/VTK-h/VTK-h-0.8.1-cpeGNU-21.12.eb, easybuild/easyconfigs/v/VTK-m/VTK-m-1.7.1-cpeGNU-21.12.eb, jenkins-builds/1.4.0-21.12-eiger
== COMPLETED: Installation ended successfully (took 1 min 39 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/Ascent/0.8.0-cpeGNU-21.12/easybuild/easybuild-Ascent-0.8.0-20220509.092321.log
== COMPLETED: Installation ended successfully (took 1 min 44 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/VTK-h/0.8.1-cpeGNU-21.12/easybuild/easybuild-VTK-h-0.8.1-20220509.091824.log
== COMPLETED: Installation ended successfully (took 3 mins 26 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/VTK-m/1.7.1-cpeGNU-21.12/easybuild/easybuild-VTK-m-1.7.1-20220509.090818.log
== COMPLETED: Installation ended successfully (took …
=> [eiger] adding Ascent in-situ library for eiger

easybuild/easyconfigs/a/angsd/angsd-0.936-CrayGNU-21.09.eb, easybuild/easyconfigs/h/HTSlib/HTSlib-1.15.1-CrayGNU-21.09.eb
I provide the recipes for `angsd` and `HTSlib` with CrayGNU 21.09 (see [SD-55649](https://jira.cscs.ch/browse/SD-55649)).
=> [daint dom] angsd and HTSlib

easybuild/easyconfigs/v/Visit/Visit-3.3.0-CrayGNU-21.09.eb
== COMPLETED: Installation ended successfully (took 1 hour 1 min 12 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Visit/3.3.0-CrayGNU-21.09/easybuild/easybuild-Visit-3.3.0-20220704.182528.log
=> [daint] updating VisIt to 3.3

jenkins-builds/1.4.0-21.12-eiger
I propose to update the default `reframe` module on Eiger and Pilatus to the latest release.
=> [eiger pilatus] Update ReFrame

easybuild/easyconfigs/o/ovito/ovito-3.7.7-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 13 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ovito/3.7.7-CrayGNU-21.09/easybuild/easybuild-ovito-3.7.7-20220720.125748.log
=> [daint-gpu, dom-gpu] update ovito to support CP2K trajectory format

easybuild/cpe_external_modules_metadata-22.02.cfg, easybuild/easyconfigs/h/HDF5/HDF5-1.12.2-cpeIntel-22.02.eb, easybuild/easyconfigs/s/SPLA/SPLA-1.5.4-cpeIntel-22.02.eb, easybuild/easyconfigs/s/SpFFT/SpFFT-1.0.6-cpeIntel-22.02.eb, easybuild/easyconfigs/s/Szip/Szip-2.1.1-cpeIntel-22.02.eb
I provide the metadata file and some recipes for CPE 22.02.
=> [eiger pilatus] Metadata and recipes for CPE 22.02

easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-CrayGNU-21.09-cuda.eb, easybuild/easyconfigs/l/LAMMPS/LAMMPS-23Jun2022-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu, jenkins-builds/7.0.UP03-21.09-daint-mc
I provide the recipes to add the latest stable release of LAMMPS in production.
=> [daint dom] LAMMPS latest stable release in production

easybuild/easyconfigs/c/Catalyst/Catalyst-2.0.0-CrayGNU-21.09.eb
to address https://jira.cscs.ch/browse/VCMSA-44
=> [daint,dom] introducing the Catalyst v2 as a new module

easybuild/easyconfigs/c/CLAPACK/CLAPACK-3.2.1-CrayGNU-21.09.eb
I provide the recipe to build `CLAPACK` on Piz Daint (see [SD-56374](https://jira.cscs.ch/browse/SD-56374)).
=> [daint] Recipe of CLAPACK

easybuild/easyconfigs/t/tree/tree-1.8.0.eb
Updating the URL as the FTP download fails and Gitlab is used for hosting according to http://mama.indstate.edu/users/ice/tree/.
=> [daint-mc] URL change in tree

easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.b190b0d-CrayIntel-21.09.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayIntel-21.09-PLUMED-2.8.0.eb, easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayIntel-21.09-PLUMED-2.9.b190b0d.eb
I provide a new recipe for QuantumESPRESSO 7.0 patched with PLUMED 2.9.0-dev (see [SD-56436](https://jira.cscs.ch/browse/SD-56436)).
=> [daint-mc] QuantumESPRESSO 7.0 with PLUMED 2.9.0-dev

jenkins-builds/1.4.0-21.12-eiger
Update reframe-cscs-tests with release 22.10
=> [eiger] Update release of reframe tests

easybuild/easyconfigs/x/XGandalf/XGandalf-b34a34ff02c-CrayGNU-21.09.eb
dependency to CrystFEL-0.10.1-CrayGNU-21.09 https://github.com/eth-cscs/production/pull/2803
=> [dom daint] XGandalf

easybuild/easyconfigs/c/CDI/CDI-2.1.0-CrayGNU-21.09.eb, easybuild/easyconfigs/g/git-lfs/git-lfs-3.2.0.eb, easybuild/easyconfigs/o/ospray/ospray-2.8.0-CrayGNU-21.09.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.11.0-CrayGNU-21.09-EGL.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 36 mins 3 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.11.0-CrayGNU-21.09-EGL/easybuild/easybuild-ParaView-5.11.0-20221114.114650.log
=> [daint-gpu, dom-gpu] ParaViewDaint5.11-EGL

easybuild/easyconfigs/p/ParaView/ParaView-5.11.0-CrayGNU-21.09-OSMesa.eb, jenkins-builds/7.0.UP03-21.09-daint-mc
this is the latest release for daint-mc with software rendering with Mesa
=> [daint-mc] ParaView v5.11 for mc partition

easybuild/easyconfigs/o/ospray/ospray-2.8.0-cpeGNU-21.12.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.11.0-cpeGNU-21.12-OSMesa.eb, jenkins-builds/1.4.0-21.12-eiger
based on the condition that I pre-loaded the following on my user terminal:
module load  Core/cpeGNU/21.12
== COMPLETED: Installation ended successfully (took 37 mins 55 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/ParaView/5.11.0-cpeGNU-21.12-OSMesa/easybuild/easybuild-ParaView-5.11.0-20221116.123933.log
=> [pilatus, eiger] ParaView v5.11 for Eiger with software rendering

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.1-CrayIntel-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-mc
Add recipe for QE 7.1 multicore and build it in production as non default.
=> [daint-mc dom-mc] QE 7.1 multicore

easybuild/easyconfigs/a/Ascent/Ascent-0.9.0-CrayGNU-21.09-667644.eb, easybuild/easyconfigs/c/Conduit/Conduit-0.8.4-CrayGNU-21.09-python3.eb, easybuild/easyconfigs/v/VTK-m/VTK-m-1.9.0-CrayGNU-21.09-cuda.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 3 mins 47 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Ascent/0.9.0-CrayGNU-21.09-667644/easybuild/easybuild-Ascent-0.9.0-20221118.092634.log
in support of https://jira.cscs.ch/browse/SD-56931
=> [daint-gpu] Ascent pre-version 0.9 with CUDA

easybuild/easyconfigs/v/Visit/Visit-3.3.1-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu, jenkins-builds/7.0.UP03-21.09-daint-mc
== COMPLETED: Installation ended successfully (took 1 hour 0 mins 31 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Visit/3.3.1-CrayGNU-21.09/easybuild/easybuild-Visit-3.3.1-20221128.155743.log
=> [daint,dom] updating VisIt to v3.3.1

easybuild/easyconfigs/p/ParaView/ParaView-5.11.0-cpeGNU-21.12-OSMesa.eb
== COMPLETED: Installation ended successfully (took 1 hour 11 mins 4 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/ParaView-sb/5.11.0-cpeGNU-21.12-OSMesa/easybuild/easybuild-ParaView-sb-5.11.0-20221203.115058.log
=> [eiger,pilatus] Add ParaView 5.11 recipe for Eiger including all dependencies

easybuild/easyconfigs/p/PLUMED/PLUMED-2.9.b190b0d-CrayIntel-21.09.eb
Fix `json/Makefile` using `plumed --no-mpi` during the build.
=> [daint] Fix PLUMED build

easybuild/easyconfigs/e/emacs/emacs-28.2-CrayGNU-21.09.eb
Addressing [SD-57111](https://jira.cscs.ch/browse/SD-57111).
=> [daint] emacs recipe

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayNvidia-21.09-ConfigureMake.eb
Minor fixes for QE 7.0 with ConfigureMake
=> [daint-gpu] Fix configure of QE 7.0 

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.0-CrayNvidia-21.09-PLUMED-2.9.b190b0d.eb
Minor fixes for QE with PLUMED
=> [daint-gpu] Fix configure of QE with PLUMED

easybuild/easyconfigs/a/Ascent/Ascent-0.9.0-CrayGNU-21.09.eb, easybuild/easyconfigs/c/Camp/Camp-2022.10.1-CrayGNU-21.09-cuda.eb, easybuild/easyconfigs/c/Conduit/Conduit-0.8.6-CrayGNU-21.09-python3.eb, easybuild/easyconfigs/m/mfem/mfem-4.4-CrayGNU-21.09.eb, easybuild/easyconfigs/r/RAJA/RAJA-2022.10.4-CrayGNU-21.09-cuda.eb, easybuild/easyconfigs/u/Umpire/Umpire-2022.10.0-CrayGNU-21.09-cuda.eb, easybuild/easyconfigs/v/VTK-m/VTK-m-1.9.0-CrayGNU-21.09-cuda.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 8 mins 49 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Ascent/0.9.0-CrayGNU-21.09/easybuild/easybuild-Ascent-0.9.0-20230131.074850.log
=> [daint-gpu,dom-gpu] Ascent v0.9 with CUDA

easybuild/easyconfigs/n/numpy/numpy-1.21.4-CrayGNU-21.09.eb
=> [dom] Use different openmpi library

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.2.8-CrayGNU-21.09-batchspawner-cuda.eb
=> [dom-gpu] Update ipcmagic on jupyterlab

easybuild/easyconfigs/v/Visit/Visit-3.3.1-cpeGNU-21.12.eb, jenkins-builds/1.4.0-21.12-eiger
== COMPLETED: Installation ended successfully (took 1 hour 5 mins 43 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/Visit/3.3.1-cpeGNU-21.12/easybuild/easybuild-Visit-3.3.1-20230110.161632.log
=> [eiger,pilatus] adding 1st version of VisIt for Alps

easybuild/easyconfigs/v/VTK/VTK-9.2.6-cpeGNU-21.12-OSMesa.eb, jenkins-builds/1.4.0-21.12-eiger
== COMPLETED: Installation ended successfully (took 15 mins 28 secs)
== Results of the build can be found in the log file(s) /scratch/e1000/jfavre/eiger/software/VTK/9.2.6-cpeGNU-21.12-OSMesa/easybuild/easybuild-VTK-9.2.6-20230222.074228.log
=> [pilatus, eiger] updating VTK to v9.2.6 for cpeGNU

easybuild/easyconfigs/p/ParaView/CDIreader.patch, easybuild/easyconfigs/p/ParaView/ParaView-5.11.0-CrayGNU-21.09-EGL.eb
== COMPLETED: Installation ended successfully (took 34 mins 25 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.11.0-CrayGNU-21.09-EGL/easybuild/easybuild-ParaView-5.11.0-20230320.102853.log
built and run-time test  OK!
=> [daint-gpu] bug fixes for CDI reader (ICON data)

easybuild/easyconfigs/c/Catalyst/Catalyst-2.0.0-CrayGNU-22.09-rc3.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.11.1-CrayGNU-21.09-EGL.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 30 mins 35 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.11.1-CrayGNU-21.09-EGL/easybuild/easybuild-ParaView-5.11.1-20230330.092716.log
=> [daint-gpu] update both ParaView and Catalyst

easybuild/easyconfigs/a/adios/adios-2.9.0-CrayGNU-21.09.eb, easybuild/easyconfigs/b/blosc2/blosc2-2.9.2-CrayGNU-21.09.eb, easybuild/easyconfigs/z/zfp/zfp-0.5.5-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 4 mins 19 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/adios/2.9.0-CrayGNU-21.09/easybuild/easybuild-adios-2.9.0-20230605.090220.log
=> [daint-gpu] adding a new ADIOS2.9 with plugin and BLOSC2 support

jenkins-builds/1.4.0-21.12-eiger
I propose to update `reframe` and `reframe-cscs-tests` on Eiger and Pilatus: this pull request can be merged only after #2887 gets merged.
=> [eiger pilatus] Update ReFrame and tests modules on Alps

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2212-CrayGNU-21.09.eb, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-v2212.patch
Request based on https://jira.cscs.ch/browse/SD-58800
=> [daint-mc] Adding OpenFOAM v2212

easybuild/module/EasyBuild-custom/cscs, jenkins-builds/production.sh, jenkins/JenkinsfileTestingEB
I have updated the `MODULEPATH` with the hierarchical naming scheme used by EasyBuild on Eiger and Pilatus to try fixing [VCUE-99](https://jira.cscs.ch/browse/VCUE-99), together with the option `--set-default-module` for the build list in `TestingEB`.
=> [eiger pilatus] Fix production for TestingEB

easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10-20230119.patch, easybuild/easyconfigs/o/OpenFOAM/OpenFOAM-10.0-CrayGNU-21.09-20230119.eb
I provide a tentative recipe with a patch file for OpenFOAM release 10 (see [SD-59305](https://jira.cscs.ch/browse/SD-59305)).
=> [daint dom] Recipe for OpenFOAM 10

easybuild/easyconfigs/a/adios/adios-2.9.1-CrayGNU-21.09.eb, easybuild/easyconfigs/c/CMake/CMake-3.26.5.eb, easybuild/easyconfigs/c/Catalyst/Catalyst-2.0.0-CrayGNU-21.09-rc4.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 4 mins 52 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/adios/2.9.1-CrayGNU-21.09/easybuild/easybuild-adios-2.9.1-20230921.182600.log
this update will be needed by ParaView 5.11.2
=> [daint-gpu] update ADIOS for daint

easybuild/easyconfigs/a/adios/adios-2.9.1-CrayGNU-21.09.eb
after discussion with @omlins , we agreed to remove the options which cause configuration errors with ParaView"
=> [daint] remove options creating conflict with ParaView build

easybuild/easyconfigs/p/ParaView/ParaView-5.11.2-CrayGNU-21.09-EGL.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 2 hours 7 mins 13 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.11.2-CrayGNU-21.09-EGL/easybuild/easybuild-ParaView-5.11.2-20231002.102453.log
=> [daint-gpu] minor update for Piz Daint ParaView

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda.eb
Update of julia kernel to use Julia 1.9.3
=> [dom-gpu] jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda.eb
donwgraded mistune to a version that is compatible with nbconvert and ipyparaview requirements
=> [dom-gpu] Update jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda.eb

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda.eb
Disable the minimize option to try to conserve memory (this built with testingEB but failed with productionEB)
=> [dom-gpu] jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda.eb

easybuild/easyconfigs/p/ParaView/ParaView-5.11.2-cpeGNU-21.12-OSMesa.eb, jenkins-builds/21.12-eiger
== COMPLETED: Installation ended successfully (took 1 hour 11 mins 21 secs)
== Results of the build can be found in the log file(s) /capstor/scratch/cscs/jfavre/eiger/software/ParaView/5.11.2-cpeGNU-21.12-OSMesa/easybuild/easybuild-ParaView-5.11.2-20231108.191218.log
=> [eiger] last ParaView v5.11* for Eiger with software rendering

easybuild/easyconfigs/v/VTK/VTK-9.3.0-CrayGNU-21.09-EGL.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 26 mins 25 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/VTK/9.3.0-CrayGNU-21.09-EGL/easybuild/easybuild-VTK-9.3.0-20231115.043829.log
=> [daint-gpu dom-gpu] updating VTK with EGL on daint

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner-cuda.eb, easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner.eb
This is using the updated julia module where all issues have been solved according to user feedback.
The jupyterlab recipe itself has been successfully used during the "GPU programming with Julia" course end of November.
=> [dom-gpu] update julia version in jupyterlab-3.4.5-CrayGNU-21.09-batchspawner

jenkins-builds/production.sh
Fix typo in production script.
=> [daint dom eiger pilatus] Fix typo in production.sh

jenkins/Machines.groovy
=> [pilatus] Update Machines.groovy

easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-cpeGNU-21.12-OSMesa.eb, easybuild/easyconfigs/p/patchelf/patchelf-0.18.0.eb, jenkins-builds/21.12-eiger
== COMPLETED: Installation ended successfully (took 46 mins 1 secs)
== Results of the build can be found in the log file(s) /capstor/scratch/cscs/jfavre/eiger/software/ParaView/5.12.0-cpeGNU-21.12-OSMesa/easybuild/easybuild-ParaView-5.12.0-20240131.194402.log
=> [eiger pilatus] ParaView 5.12 with OSMesa (superbuild)

easybuild/easyconfigs/j/jupyterlab/jupyterlab-3.4.5-CrayGNU-21.09-batchspawner.eb
Change the path to yarn temp file to avoid failures resulting from stale cache files. Increase the memory for nodejs.
Downgrade mistune package for compatibility.
=> [dom-mc] jupyterlab-3.4.5-CrayGNU-21.09-batchspawner.eb

jenkins-builds/7.0.UP03-21.09-daint-mc
=> [daint-mc] 7.0.UP03-21.09-daint-mc

easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-CrayGNU-21.09-EGL.eb
== COMPLETED: Installation ended successfully (took 43 mins 37 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.12.0-CrayGNU-21.09-EGL/easybuild/easybuild-ParaView-5.12.0-20240229.082429.log
=> [daint-gpu,dom-gpu] Final production release of ParaView 5.12 with EGL

easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-CrayGNU-21.09-OSMesa.eb
== COMPLETED: Installation ended successfully (took 38 mins 26 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/ParaView/5.12.0-CrayGNU-21.09-OSMesa/easybuild/easybuild-ParaView-5.12.0-20240229.122141.log
=> [daint-mc, dom-mc] final production release ParaView v5.12 OSMesa-mc

easybuild/module/EasyBuild-custom/cscs.lua
I provide a Lua modulefile for EasyBuild-custom on EIger and Pilatus.
=> [eiger pilatus] Lua modulefile for EasyBuild-custom

easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-cpeGNU-21.12-OSMesa.eb
final production release for ParaView 5.12 on Eiger 
== COMPLETED: Installation ended successfully (took 1 hour 14 mins 13 secs) == Results of the build can be found in the log file(s) /capstor/scratch/cscs/jfavre/eiger/software/ParaView/5.12.0-cpeGNU-21.12-OSMesa/easybuild/easybuild-ParaView-5.12.0-20240303.143930.log
=> [eiger, pilatus] Update ParaView-5.12.0-cpeGNU-21.12-OSMesa.eb

jenkins/JenkinsfileTestingEB
I provide a fix to the recently updated pipeline `JenkinsfileTestingEB".
=> [eiger] Fix missing newline in buildlist

jenkins/JenkinsfileTestingEB
I remove the empty line at the beginning of the test list in `JenkinsfileTestingEB`.
=> [eiger] Remove empty line 

easybuild/easyconfigs/a/adios/adios-2.9.2-cpeGNU-21.12.eb, easybuild/easyconfigs/b/blosc2/blosc2-2.9.2-cpeGNU-21.12.eb, easybuild/easyconfigs/c/Catalyst/Catalyst-2.0.0-cpeGNU-21.12-rc4.eb, easybuild/easyconfigs/c/Catalyst/Catalyst-2.0.0-rc4-cpeGNU-21.12.eb, easybuild/easyconfigs/s/sz/sz-2.1.12.2-cpeGNU-21.12.eb, easybuild/easyconfigs/z/zfp/zfp-0.5.5-cpeGNU-21.12.eb, jenkins-builds/21.12-eiger
to enable ParaView superbuild with …system-adios
=> [eiger] ADIOS2 for eiger

easybuild/cpe_external_modules_metadata-23.09.cfg, easybuild/module/EasyBuild-custom/cscs, easybuild/module/EasyBuild-custom/cscs.lua
I provide updated external metadata and `EasyBuild-custom` modulefile for CPE 23.09 available on Pilatus for testing.
=> [pilatus] Update metadata and custom modulefile for CPE 23.09

easybuild/easyconfigs/g/GREASY/GREASY-19.03-cscs-cpeGNU-21.12.eb, jenkins/JenkinsfileUpdateEB
I provide a fix to load the module `hub` on Eiger an Pilatus, together with an inline patch for `GREASY`.
=> [eiger] Fix module load hub

easybuild/easyconfigs/c/Catalyst/Catalyst-2.0.0-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 1 min 9 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/Catalyst/2.0.0-CrayGNU-21.09/easybuild/easybuild-Catalyst-2.0.0-20240327.144001.log
=> [dom] Catalyst final production release v2.0.0

easybuild/easyconfigs/a/adios/adios-2.10.0-CrayGNU-21.09.eb, easybuild/easyconfigs/b/blosc2/blosc2-2.14.3-CrayGNU-21.09.eb, jenkins-builds/7.0.UP03-21.09-daint-gpu
== COMPLETED: Installation ended successfully (took 3 mins 10 secs)
== Results of the build can be found in the log file(s) /scratch/snx3000/jfavre/daint/software/adios/2.10.0-CrayGNU-21.09/easybuild/easybuild-adios-2.10.0-20240408.104631.log
=> [daint-gpu dom-gpu] providing major ADIOS2 upgrade

easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.3-cpeGNU-23.09.eb, easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-23.09.eb, easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-23.09.eb, easybuild/easyconfigs/n/nodejs/nodejs-14.16.0-cpeGNU-23.09.eb
I provide the recipes of `jupyterlab` dependencies for CPE 23.09.
=> [pilatus] Add jupyterlab dependencies for CPE 23.09

jenkins-builds/production.sh
Fix syntax error introduced in #2990.
=> [daint dom eiger pilatus rigi] Fix syntax in production.sh

jenkins-builds/7.0.UP03-21.09-daint-mc
=> [daint-mc] Update 7.0.UP03-21.09-daint-mc

easybuild/easyconfigs/c/cpeGNU/cpeGNU-23.12.eb, jenkins-builds/23.12-pilatus
Provide missing `cpeGNU-23.12.eb` and update ReFrame modules on Pilatus.
=> [pilatus] Update modules on Pilatus

easybuild/easyconfigs/a/adios/adios-2.9.2-cpeGNU-23.12.eb, easybuild/easyconfigs/b/blosc2/blosc2-2.9.2-cpeGNU-23.12.eb, easybuild/easyconfigs/c/Catalyst/Catalyst-2.0.0-cpeGNU-23.12.eb, easybuild/easyconfigs/l/libpng/libpng-1.6.37-cpeGNU-23.12.eb, easybuild/easyconfigs/s/sz/sz-2.1.12.2-cpeGNU-23.12.eb, easybuild/easyconfigs/z/zfp/zfp-0.5.5-cpeGNU-23.12.eb, jenkins-builds/23.12-pilatus
I provide ADIOS2.9 for pilatus cpeGNU23.12
=> [pilatus] ADIOS2 with CPE 23.12

easybuild/easyconfigs/q/QuantumESPRESSO/QuantumESPRESSO-7.3.1-CrayNvidia-21.09.eb
add latest QE version for cray-nvidia.
=> [daint-gpu] QuantumESPRESSO 7.3.1

easybuild/easyconfigs/l/LLVM/LLVM-15.0.6-cpeGNU-23.12.eb, easybuild/easyconfigs/m/Mesa/Mesa-22.3.3-cpeGNU-23.12.eb, easybuild/easyconfigs/m/Meson/Meson-0.62.0-cpeGNU-23.12.eb, easybuild/easyconfigs/n/Ninja/Ninja-1.10.2-cpeGNU-23.12.eb, jenkins-builds/23.12-pilatus
== COMPLETED: Installation ended successfully (took 53 secs)
== Results of the build can be found in the log file(s) /capstor/scratch/cscs/jfavre/eiger/software/Mesa/22.3.3-cpeGNU-23.12/easybuild/easybuild-Mesa-22.3.3-20240508.143439.log
=> [pilatus] Mesa for software rendering with CPE 23.12

easybuild/easyconfigs/j/jupyter-utils/jupyter-utils-0.1-cpeGNU-23.12.eb, jenkins-builds/23.12-pilatus
I provide an updated recipe for `jupyter-utils` with COS 3.0 and CPE 23.12 on Pilatus.
=> [pilatus] Update jupyter-utils with COS 3.0 and CPE 23.12

easybuild/easyconfigs/o/ospray/ospray-2.12.0-cpeGNU-23.12.eb, easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-cpeGNU-23.12-OSMesa.eb, jenkins-builds/23.12-pilatus
= COMPLETED: Installation ended successfully (took 17 mins 44 secs)
== Results of the build can be found in the log file(s) /capstor/scratch/cscs/jfavre/eiger/software/ParaView/5.12.0-cpeGNU-23.12-OSMesa/easybuild/easybuild-ParaView-5.12.0-20240508.191422.log
=> [pilatus] adding ParaView v5.12 for pilatus

easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.2.3-cpeGNU-23.12.eb, easybuild/easyconfigs/c/configurable-http-proxy/configurable-http-proxy-4.6.1-cpeGNU-23.12.eb, easybuild/easyconfigs/g/graphviz/graphviz-11.0.0-cpeGNU-23.12.eb, easybuild/easyconfigs/g/graphviz/graphviz-2.46.1-cpeGNU-23.12.eb, easybuild/easyconfigs/l/libffi/libffi-3.3-cpeGNU-23.12.eb, easybuild/easyconfigs/l/libffi/libffi-3.4.5-cpeGNU-23.12.eb, easybuild/easyconfigs/n/nodejs/nodejs-14.16.0-cpeGNU-23.12.eb, easybuild/easyconfigs/n/nodejs/nodejs-22.1.0-cpeGNU-23.12.eb
I provide the recipes of `jupyterlab` dependencies with CPE 23.12.
=> [pilatus] Jupyterlab dependencies with CPE 23.12

easybuild/module/EasyBuild-custom/cscs, easybuild/module/EasyBuild-custom/cscs.lua
I fixed the external metadata definition on Eiger.
=> [eiger] Update external metadata on Eiger

easybuild/easyconfigs/j/jupyterlab/jupyterlab-4.2.3-cpeGNU-23.12.eb
Update Jupyterlab recipe with CPE 23.12.
=> [pilatus eiger] Update jupyterlab with CPE 23.12

easybuild/easyconfigs/g/GROMACS/GROMACS-2024-CrayGNU-21.09-cuda.eb
I provide an updated GROMACS recipe for release 2024 with CUDA support as requested by [SD-62119](https://jira.cscs.ch/browse/SD-62119).
=> [daint-gpu dom-gpu] GROMACS 2024 with CUDA

easybuild/easyconfigs/j/jupyterlab/jupyterlab-4.2.3-cpeGNU-23.12.eb
=>  [eiger] jupyterlab-4.2.3-cpeGNU-23.12

easybuild/easyconfigs/v/Visit/Visit-3.4.1-cpeGNU-23.12.eb
the internallauncher is modified to load the cpeGNU and Visit modules required for terminal-less client-server connections
=> [pilatus, eiger] making a custom Visit launcher to load modules

easybuild/easyconfigs/p/ParaView/ParaView-5.12.0-cpeGNU-23.12-OSMesa.eb
resolves https://jira.cscs.ch/browse/SD-61469
=> [eiger] enabling VisIt bridge
